module.exports = {
  ROLE: "tinglovchi",

  LISTENER_ROLE_TITLE: "malaka_tinglovchi",

  PETITION_STATUS: { PENDING: 1, ACCEPTED: 2, REJECTED: 3 },

  COURSE_STATUS: { PLANNED: 1, ACTIVE: 2, FINISHED: 3 },

  COURSE_FORM: { ONLINE: 1, OFFLINE: 2 },

  PAYMENT_METHOD: { CLICK: 1, PAYME: 2, BANK: 3 },
  PAYMENT_STATUS: { PENDING: 1, CONFIRMED: 2, REJECTED: 3 },

  TOPIC_STAGE: { NOT_STARTED: 0, LECTURE: 1, PRACTICAL: 2, VIDEO: 3, SCENARIO: 4, FINAL: 5 },

  TEST_STATUS: { ACTIVE: 1, FINISHED: 2 },

  EARNED_KIND: { CERTIFICATE: 1, REFERENCE: 2 },
};
