import { lazy } from 'react';
import {
  AppstoreOutlined,
  BarChartOutlined,
  CheckCircleOutlined,
  NotificationOutlined,
  IdcardOutlined,
  SafetyCertificateOutlined,
  TeamOutlined,
} from '@ant-design/icons';
import { Navigate } from 'react-router-dom';
import { defineModule } from '@/shared/lib/module';

const NotificationsRedirect = () => <Navigate to="/bildirishnomalar" replace />;

export default defineModule({
  name: 'council',
  menuGroup: { titleKey: 'menuGroup.council', order: 60 },
  basePath: '/kengash',
  routes: [
    { index: true, element: lazy(() => import('./pages/council-landing')) },
    { path: 'dashboard', permission: 'councilMember:readAll', element: lazy(() => import('./pages/dashboard-page')) },
    { path: 'kengash-tarkibi', permission: 'councilMember:readAll', element: lazy(() => import('./pages/kengash-tarkibi-page')) },
    { path: 'topshiriqlar', permission: 'councilTask:readAll', element: lazy(() => import('./pages/topshiriqlar-page')) },
    { path: 'unvonlar', permission: 'rankApplication:readAll', element: lazy(() => import('./pages/unvonlar-page')) },
    { path: 'unvonlar/hujjatlar', permission: 'rankApplication:readAll', element: lazy(() => import('./pages/unvonlar-page')) },
    { path: 'unvonlar/tasdiqlangan', permission: 'rankApplication:readAll', element: lazy(() => import('./pages/unvonlar-page')) },
    { path: 'unvonlar/arxiv', permission: 'rankApplication:readAll', element: lazy(() => import('./pages/unvonlar-page')) },
    { path: 'lavozimlar', permission: 'rankApplication:readAll', element: lazy(() => import('./pages/lavozimlar-page')) },
    { path: 'lavozimlar/hujjatlar', permission: 'rankApplication:readAll', element: lazy(() => import('./pages/lavozimlar-page')) },
    { path: 'lavozimlar/tasdiqlangan', permission: 'rankApplication:readAll', element: lazy(() => import('./pages/lavozimlar-page')) },
    { path: 'lavozimlar/arxiv', permission: 'rankApplication:readAll', element: lazy(() => import('./pages/lavozimlar-page')) },
    { path: 'ovoz-berish', permission: 'votingSession:readAll', element: lazy(() => import('./pages/ovoz-berish-page')) },
    { path: 'elonlar', permission: 'announcement:readAll', element: lazy(() => import('./pages/elonlar-page')) },
    { path: 'hisobotlar', permission: 'votingSession:export', element: lazy(() => import('./pages/hisobotlar-page')) },
    { path: 'bildirishnomalar', element: NotificationsRedirect },
    { path: 'sozlamalar', permission: 'councilMember:readAll', element: lazy(() => import('./pages/sozlamalar-page')) },
  ],
  menu: [
    { titleKey: 'council.nav.dashboard', icon: <AppstoreOutlined />, path: '/kengash/dashboard', order: 30, permission: 'councilMember:readAll' },
    { titleKey: 'council.nav.members', icon: <TeamOutlined />, path: '/kengash/kengash-tarkibi', order: 31, permission: 'councilMember:readAll' },
    { titleKey: 'council.nav.ranks', icon: <SafetyCertificateOutlined />, path: '/kengash/unvonlar', order: 33, permission: 'rankApplication:readAll' },
    { titleKey: 'council.nav.positions', icon: <IdcardOutlined />, path: '/kengash/lavozimlar', order: 34, permission: 'rankApplication:readAll' },
    { titleKey: 'council.nav.voting', icon: <CheckCircleOutlined />, path: '/kengash/ovoz-berish', order: 35, permission: 'votingSession:readAll' },
    { titleKey: 'council.nav.announcements', icon: <NotificationOutlined />, path: '/kengash/elonlar', order: 36, permission: 'announcement:readAll' },
    { titleKey: 'council.nav.reports', icon: <BarChartOutlined />, path: '/kengash/hisobotlar', order: 37, permission: 'votingSession:export' },
  ],
  i18n: {
    uz: {
      'menuGroup.council': 'Institut kengashi',
      'council.nav.dashboard': 'Bosh sahifa',
      'council.nav.members': 'Kengash tarkibi',
      'council.nav.tasks': 'Topshiriqlar',
      'council.nav.ranks': 'Unvonlar',
      'council.nav.positions': 'Lavozimlar',
      'council.nav.ranksDocs': 'Hujjatlar',
      'council.nav.ranksAccepted': 'Tasdiqlangan',
      'council.nav.ranksArchive': 'Arxiv',
      'council.nav.voting': 'Ovoz berish',
      'council.nav.announcements': "E'lonlar",
      'council.nav.reports': 'Hisobotlar',
      'council.nav.notifications': 'Bildirishnomalar',
      'council.nav.settings': 'Sozlamalar',
    },
    ru: {
      'menuGroup.council': 'Совет института',
      'council.nav.dashboard': 'Главная',
      'council.nav.members': 'Состав совета',
      'council.nav.tasks': 'Поручения',
      'council.nav.ranks': 'Звания',
      'council.nav.positions': 'Должности',
      'council.nav.ranksDocs': 'Документы',
      'council.nav.ranksAccepted': 'Утверждённые',
      'council.nav.ranksArchive': 'Архив',
      'council.nav.voting': 'Голосование',
      'council.nav.announcements': 'Объявления',
      'council.nav.reports': 'Отчёты',
      'council.nav.notifications': 'Уведомления',
      'council.nav.settings': 'Настройки',
    },
    en: {
      'menuGroup.council': 'Institute council',
      'council.nav.dashboard': 'Dashboard',
      'council.nav.members': 'Council members',
      'council.nav.tasks': 'Tasks',
      'council.nav.ranks': 'Academic ranks',
      'council.nav.positions': 'Positions',
      'council.nav.ranksDocs': 'Documents',
      'council.nav.ranksAccepted': 'Approved',
      'council.nav.ranksArchive': 'Archive',
      'council.nav.voting': 'Voting',
      'council.nav.announcements': 'Announcements',
      'council.nav.reports': 'Reports',
      'council.nav.notifications': 'Notifications',
      'council.nav.settings': 'Settings',
    },
  },
  permissions: [
    { key: 'councilMember:create', description: "Kengash a'zosi qo'shish" },
    { key: 'councilMember:read', description: "Kengash a'zosini ko'rish" },
    { key: 'councilMember:readAll', description: "Kengash tarkibi ro'yxati" },
    { key: 'councilMember:update', description: "A'zoni tahrirlash / ovoz huquqi" },
    { key: 'councilMember:delete', description: "A'zoni o'chirish" },
    { key: 'councilTask:create', description: 'Topshiriq berish' },
    { key: 'councilTask:read', description: "Topshiriqni ko'rish" },
    { key: 'councilTask:readAll', description: "Topshiriqlar ro'yxati" },
    { key: 'councilTask:update', description: 'Topshiriqni tahrirlash' },
    { key: 'councilTask:delete', description: "Topshiriqni o'chirish" },
    { key: 'councilTask:changeStatus', description: 'Natija yuklash' },
    { key: 'councilTask:approve', description: 'Topshiriqni tasdiqlash' },
    { key: 'councilTask:reject', description: 'Topshiriqni rad etish' },
    { key: 'councilTask:export', description: 'Topshiriq hisoboti' },
    { key: 'rankApplication:create', description: 'Unvon arizasi topshirish' },
    { key: 'rankApplication:read', description: "Arizani ko'rish" },
    { key: 'rankApplication:readAll', description: "Unvon arizalari ro'yxati" },
    { key: 'rankApplication:update', description: 'Arizani tahrirlash' },
    { key: 'rankApplication:delete', description: "Arizani o'chirish" },
    { key: 'rankApplication:approve', description: 'Arizani qabul qilish' },
    { key: 'rankApplication:reject', description: 'Arizani qaytarish' },
    { key: 'votingSession:create', description: "So'rovnoma yaratish" },
    { key: 'votingSession:read', description: "So'rovnomani ko'rish" },
    { key: 'votingSession:readAll', description: "So'rovnomalar ro'yxati" },
    { key: 'votingSession:update', description: "So'rovnomani tahrirlash" },
    { key: 'votingSession:delete', description: "So'rovnomani o'chirish" },
    { key: 'votingSession:changeStatus', description: "So'rovnomani yakunlash" },
    { key: 'votingSession:export', description: 'Ovoz berish hisoboti' },
    { key: 'anonymousVote:create', description: 'Ovoz berish' },
    { key: 'anonymousVote:readAll', description: 'Ovozlarni kuzatish' },
    { key: 'announcement:create', description: "E'lon yuborish" },
    { key: 'announcement:read', description: "E'lonni ko'rish" },
    { key: 'announcement:readAll', description: "E'lonlar ro'yxati" },
    { key: 'announcement:delete', description: "E'lonni o'chirish" },
  ],
});
