import { lazy } from 'react';
import {
  ApartmentOutlined,
  BankOutlined,
  BarChartOutlined,
  BellOutlined,
  CheckCircleOutlined,
  FileTextOutlined,
  OrderedListOutlined,
  SendOutlined,
  TeamOutlined,
} from '@ant-design/icons';
import { defineModule } from '@/shared/lib/module';

export default defineModule({
  name: 'education-quality',

  menuGroup: { titleKey: 'menuGroup.educationQuality', order: 100 },

  routes: [
    {
      path: 'indicators',
      permission: 'eqIndicator:read',
      element: lazy(() => import('./pages/indicators-page')),
    },
    {
      path: 'verification',
      permission: 'eqSubmission:read',
      element: lazy(() => import('./pages/verification-page')),
    },
    {
      path: 'announcements',
      permission: 'eqAnnouncement:read',
      element: lazy(() => import('./pages/announcements-page')),
    },
    {
      path: 'reports',
      permission: 'eqReport:read',
      element: lazy(() => import('./pages/reports-faculty-page')),
    },
    {
      path: 'reports/faculty',
      permission: 'eqReport:read',
      element: lazy(() => import('./pages/reports-faculty-page')),
    },
    {
      path: 'reports/department',
      permission: 'eqReport:read',
      element: lazy(() => import('./pages/reports-department-page')),
    },
    {
      path: 'reports/teacher',
      permission: 'eqReport:read',
      element: lazy(() => import('./pages/reports-teacher-page')),
    },
    {
      path: 'reports/teacher/:teacherId',
      permission: 'eqReport:read',
      element: lazy(() => import('./pages/teacher-detail-page')),
    },
    {
      path: 'submit',
      permission: 'eqSubmission:create',
      element: lazy(() => import('./pages/submit-page')),
    },
    {
      path: 'my-data',
      permission: 'eqSubmission:readOwn',
      element: lazy(() => import('./pages/my-data-page')),
    },
    {
      path: 'teacher-announcements',
      permission: 'eqAnnouncement:readOwn',
      element: lazy(() => import('./pages/teacher-announcements-page')),
    },
  ],

  menu: [
    {
      titleKey: 'educationQuality.nav.indicators',
      icon: <OrderedListOutlined />,
      path: '/education-quality/indicators',
      order: 120,
      permission: 'eqIndicator:read',
    },
    {
      titleKey: 'educationQuality.nav.verification',
      icon: <CheckCircleOutlined />,
      path: '/education-quality/verification',
      order: 121,
      permission: 'eqSubmission:read',
    },
    {
      titleKey: 'educationQuality.nav.announcements',
      icon: <BellOutlined />,
      path: '/education-quality/announcements',
      order: 122,
      permission: 'eqAnnouncement:read',
    },
    {
      titleKey: 'educationQuality.nav.reports',
      icon: <BarChartOutlined />,
      path: '/education-quality/reports-group',
      order: 123,
      permission: 'eqReport:read',
    },
    {
      titleKey: 'educationQuality.nav.reportFaculty',
      icon: <BankOutlined />,
      path: '/education-quality/reports/faculty',
      order: 123.1,
      permission: 'eqReport:read',
      parent: '/education-quality/reports-group',
    },
    {
      titleKey: 'educationQuality.nav.reportDepartment',
      icon: <ApartmentOutlined />,
      path: '/education-quality/reports/department',
      order: 123.2,
      permission: 'eqReport:read',
      parent: '/education-quality/reports-group',
    },
    {
      titleKey: 'educationQuality.nav.reportTeacher',
      icon: <TeamOutlined />,
      path: '/education-quality/reports/teacher',
      order: 123.3,
      permission: 'eqReport:read',
      parent: '/education-quality/reports-group',
    },
    {
      titleKey: 'educationQuality.nav.submit',
      icon: <SendOutlined />,
      path: '/education-quality/submit',
      order: 124,
      permission: 'eqSubmission:create',
    },
    {
      titleKey: 'educationQuality.nav.myData',
      icon: <FileTextOutlined />,
      path: '/education-quality/my-data',
      order: 125,
      permission: 'eqSubmission:readOwn',
    },
    {
      titleKey: 'educationQuality.nav.teacherAnnouncements',
      icon: <BellOutlined />,
      path: '/education-quality/teacher-announcements',
      order: 126,
      permission: 'eqAnnouncement:readOwn',
    },
  ],

  i18n: {
    uz: {
      'educationQuality.announcements.contentPlaceholder': "E'lon matni...",
      'educationQuality.announcements.contentRequired': 'Mazmun majburiy',
      'educationQuality.announcements.created': "E'lon yuborildi",
      'educationQuality.announcements.dateFrom': 'dan',
      'educationQuality.announcements.dateTo': 'gacha',
      'educationQuality.announcements.deleteBody': '"{{title}}" e\'loni o\'chiriladi.',
      'educationQuality.announcements.deleteTitle': "E'lonni o'chirish",
      'educationQuality.announcements.deleted': "E'lon o'chirildi",
      'educationQuality.announcements.empty': "Hozircha e'lon yo'q",
      'educationQuality.announcements.emptyFiltered': "Filtrlarga mos e'lon topilmadi",
      'educationQuality.announcements.formContent': 'Mazmuni',
      'educationQuality.announcements.formTitle': 'Sarlavha',
      'educationQuality.announcements.new': "Yangi e'lon",
      'educationQuality.announcements.searchPlaceholder': "Sarlavha yoki matn bo'yicha qidirish",
      'educationQuality.announcements.send': 'Yuborish',
      'educationQuality.announcements.subtitle': "Barcha professor-o'qituvchilarga e'lon yuborish",
      'educationQuality.announcements.title': "E'lonlar",
      'educationQuality.announcements.titlePlaceholder': "E'lon sarlavhasi",
      'educationQuality.announcements.titleRequired': 'Sarlavha majburiy',
      'educationQuality.common.academicYear': "O'quv yili",
      'educationQuality.common.actions': 'Amallar',
      'educationQuality.common.all': 'Barchasi',
      'educationQuality.common.allDepartments': 'Barcha kafedralar',
      'educationQuality.common.allFaculties': 'Barcha fakultetlar',
      'educationQuality.common.allIndicators': 'Barcha indikatorlar',
      'educationQuality.common.allSemesters': 'Barcha semestrlar',
      'educationQuality.common.allStatuses': 'Barcha holatlar',
      'educationQuality.common.allYears': "Barcha o'quv yillari",
      'educationQuality.common.apply': "Qo'llash",
      'educationQuality.common.authors': 'Mualliflar',
      'educationQuality.common.back': 'Orqaga',
      'educationQuality.common.cancel': 'Bekor qilish',
      'educationQuality.common.clear': 'Tozalash',
      'educationQuality.common.close': 'Yopish',
      'educationQuality.common.date': 'Sana',
      'educationQuality.common.delete': "O'chirish",
      'educationQuality.common.department': 'Kafedra',
      'educationQuality.common.details': 'Batafsil',
      'educationQuality.common.edit': 'Tahrirlash',
      'educationQuality.common.exportExcel': 'Excelga yuklash',
      'educationQuality.common.exportFailed': "Excelga yuklab bo'lmadi",
      'educationQuality.common.faculty': 'Fakultet',
      'educationQuality.common.filter': 'Filtr',
      'educationQuality.common.indicator': 'Indikator',
      'educationQuality.common.irreversible': "Bu amalni qaytarib bo'lmaydi.",
      'educationQuality.common.save': 'Saqlash',
      'educationQuality.common.score': 'Ball',
      'educationQuality.common.semester': 'Semestr',
      'educationQuality.common.status': 'Status',
      'educationQuality.common.teacher': "O'qituvchi",
      'educationQuality.common.total': 'Jami',
      'educationQuality.common.view': "Ko'rish",
      'educationQuality.drawer.approve': 'Tasdiqlash',
      'educationQuality.drawer.authorCount': 'Mualliflar soni',
      'educationQuality.drawer.coeffDefault': 'standart: 1 / {{count}} muallif',
      'educationQuality.drawer.coefficient': 'Koeffisient',
      'educationQuality.drawer.coefficientValue': 'koeffisient {{coeff}}',
      'educationQuality.drawer.confirmTitle': "Ma'lumotni tasdiqlaysizmi?",
      'educationQuality.drawer.estimatedNote': 'Tasdiqlanganda taxminiy ball ({{base}} bal x {{coeff}} koeffisient)',
      'educationQuality.drawer.indicatorScore': 'Indikator bali',
      'educationQuality.drawer.moneyValue': "{{amount}} so'm",
      'educationQuality.drawer.openLink': 'Havolani ochish',
      'educationQuality.drawer.pdfFile': 'PDF fayl',
      'educationQuality.drawer.points': '{{score}} ball',
      'educationQuality.drawer.reject': 'Rad etish',
      'educationQuality.drawer.rejectHint': "Rad etish sababini batafsil yozing. Sabab o'qituvchiga ko'rinadi.",
      'educationQuality.drawer.rejectPlaceholder': 'Masalan: Yuklangan fayl talabga javob bermaydi...',
      'educationQuality.drawer.rejectReason': 'Rad etish sababi',
      'educationQuality.drawer.rejectTitle': "Ma'lumotni rad etish",
      'educationQuality.drawer.scoreFormula': '{{base}} bal x {{coeff}} koeffisient',
      'educationQuality.drawer.scoreOnApproval': 'Tasdiqlangach biriktiriladigan ball',
      'educationQuality.drawer.submittedAt': 'Yuborilgan sana',
      'educationQuality.drawer.submittedBy': 'Yuborgan',
      'educationQuality.drawer.submittedData': "Yuborilgan ma'lumotlar",
      'educationQuality.drawer.title': "Ma'lumotni ko'rish",
      'educationQuality.dynamicField.currency': "so'm",
      'educationQuality.dynamicField.datePlaceholder': 'Sanani tanlang',
      'educationQuality.dynamicField.required': '{{label}} majburiy',
      'educationQuality.dynamicField.selectPlaceholder': 'Tanlang',
      'educationQuality.dynamicField.uploadPdf': 'PDF fayl yuklash',
      'educationQuality.field.activityName': 'Tadbir nomi',
      'educationQuality.field.antiplagiatReport': 'Antiplagiat hisoboti',
      'educationQuality.field.articleFile': 'Maqola fayli',
      'educationQuality.field.articleTitle': 'Maqola nomi',
      'educationQuality.field.authors': 'Mualliflar',
      'educationQuality.field.authorsCount': 'Mualliflar soni',
      'educationQuality.field.authorsName': 'Muallif(lar) F.I.Sh.',
      'educationQuality.field.basisType': 'Asos turi',
      'educationQuality.field.certificateFile': 'Sertifikat fayli',
      'educationQuality.field.certificateName': 'Sertifikat nomi',
      'educationQuality.field.citationCount': 'Iqtiboslar soni',
      'educationQuality.field.comment': 'Izoh',
      'educationQuality.field.competitionName': 'Tanlov nomi',
      'educationQuality.field.conferenceName': 'Konferensiya nomi',
      'educationQuality.field.contractFile': 'Shartnoma fayli',
      'educationQuality.field.cooperationDocName': 'Hamkorlik hujjati nomi',
      'educationQuality.field.councilCertificate': 'Kengash guvohnomasi',
      'educationQuality.field.councilDecision': 'Kengash qarori',
      'educationQuality.field.country': 'Davlat',
      'educationQuality.field.currentYearAmount': 'Joriy yildagi summa',
      'educationQuality.field.date': 'Sana',
      'educationQuality.field.departmentMinutes': 'Kafedra bayonnomasi',
      'educationQuality.field.diplomaFile': 'Diplom fayli',
      'educationQuality.field.diplomaNumber': 'Diplom raqami',
      'educationQuality.field.diplomaSeries': 'Diplom seriyasi',
      'educationQuality.field.directionName': "Yo'nalish nomi",
      'educationQuality.field.dissertationTopic': 'Dissertatsiya mavzusi',
      'educationQuality.field.doctorDiplomaNumber': 'Doktorlik diplomi raqami',
      'educationQuality.field.doctorDiplomaSeries': 'Doktorlik diplomi seriyasi',
      'educationQuality.field.dscNumber': 'DSc diplomi raqami',
      'educationQuality.field.dscSeries': 'DSc diplomi seriyasi',
      'educationQuality.field.duration': 'Davomiyligi',
      'educationQuality.field.expiryDate': 'Amal qilish muddati',
      'educationQuality.field.externalReview': 'Tashqi taqriz',
      'educationQuality.field.foreignOtm': 'Xorijiy OTM nomi',
      'educationQuality.field.googleScholarUrl': 'Google Scholar havolasi',
      'educationQuality.field.grantName': 'Grant nomi',
      'educationQuality.field.grantTopic': 'Grant mavzusi',
      'educationQuality.field.internalReview': 'Ichki taqriz',
      'educationQuality.field.invitationFile': 'Taklifnoma fayli',
      'educationQuality.field.isbn': 'ISBN',
      'educationQuality.field.issuedDate': 'Berilgan sana',
      'educationQuality.field.journalName': 'Jurnal nomi',
      'educationQuality.field.level': 'Daraja',
      'educationQuality.field.manualFile': "Qo'llanma fayli",
      'educationQuality.field.manualName': "Qo'llanma nomi",
      'educationQuality.field.ministerCertFile': 'Vazirlik sertifikati fayli',
      'educationQuality.field.ministerOrderFile': "Vazirlik buyrug'i fayli",
      'educationQuality.field.monographFile': 'Monografiya fayli',
      'educationQuality.field.monographTitle': 'Monografiya nomi',
      'educationQuality.field.orderName': 'Buyruq nomi',
      'educationQuality.field.otmName': 'OTM nomi',
      'educationQuality.field.pages': 'Sahifalar',
      'educationQuality.field.participationType': 'Ishtirok turi',
      'educationQuality.field.passportStampFile': 'Pasport shtampi fayli',
      'educationQuality.field.patentName': 'Patent nomi',
      'educationQuality.field.phdNumber': 'PhD diplomi raqami',
      'educationQuality.field.phdSeries': 'PhD diplomi seriyasi',
      'educationQuality.field.place': 'Joy',
      'educationQuality.field.professorDiplomaNumber': 'Professorlik diplomi raqami',
      'educationQuality.field.professorDiplomaSeries': 'Professorlik diplomi seriyasi',
      'educationQuality.field.programFile': 'Dastur fayli',
      'educationQuality.field.publishLicenseFile': 'Nashr litsenziyasi fayli',
      'educationQuality.field.publishYear': 'Nashr yili',
      'educationQuality.field.publisher': 'Nashriyot',
      'educationQuality.field.rankObtainedDate': 'Unvon olingan sana',
      'educationQuality.field.receiptFile': 'Kvitansiya fayli',
      'educationQuality.field.rectorOrderFile': "Rektor buyrug'i fayli",
      'educationQuality.field.referralFile': "Yo'llanma fayli",
      'educationQuality.field.registrationNumber': "Ro'yxatga olish raqami",
      'educationQuality.field.reportFile': 'Hisobot fayli',
      'educationQuality.field.rewardOrderFile': "Mukofot buyrug'i fayli",
      'educationQuality.field.scopusUrl': 'Scopus havolasi',
      'educationQuality.field.signedDate': 'Imzolangan sana',
      'educationQuality.field.specialty': 'Mutaxassislik',
      'educationQuality.field.specialtyCode': 'Mutaxassislik shifri',
      'educationQuality.field.ssvConclusion': 'SSV xulosasi',
      'educationQuality.field.studentName': 'Talaba F.I.Sh.',
      'educationQuality.field.teacherName': "O'qituvchi F.I.Sh.",
      'educationQuality.field.textbookName': 'Darslik nomi',
      'educationQuality.field.thesisFile': 'Tezis fayli',
      'educationQuality.field.thesisTitle': 'Tezis nomi',
      'educationQuality.field.titleFile': "Titul varag'i fayli",
      'educationQuality.field.topic': 'Mavzu',
      'educationQuality.field.totalAmount': 'Umumiy summa',
      'educationQuality.field.url': 'Havola',
      'educationQuality.field.venue': "O'tkazilgan joy",
      'educationQuality.field.ziyonetCert': 'Ziyonet sertifikati',
      'educationQuality.fieldOption.buyruq': 'Buyruq',
      'educationQuality.fieldOption.oflayn': 'Oflayn',
      'educationQuality.fieldOption.onlayn': 'Onlayn',
      'educationQuality.fieldOption.qaror': 'Qaror',
      'educationQuality.fieldOption.shartnoma': 'Shartnoma',
      'educationQuality.fieldType.date': 'Sana',
      'educationQuality.fieldType.file': 'Fayl (PDF)',
      'educationQuality.fieldType.money': 'Summa',
      'educationQuality.fieldType.number': 'Raqam',
      'educationQuality.fieldType.text': 'Matn',
      'educationQuality.fieldType.textarea': 'Katta matn',
      'educationQuality.fieldType.url': 'Havola (URL)',
      'educationQuality.history.empty': "Ma'lumot topilmadi",
      'educationQuality.history.exportFile': 'Malumotlar',
      'educationQuality.history.exportSheet': "Ma'lumotlar",
      'educationQuality.history.minRequired': 'Talab: kamida {{score}} ball',
      'educationQuality.history.noExportData': "Eksport uchun ma'lumot yo'q",
      'educationQuality.history.searchPlaceholder': "Indikator bo'yicha qidirish",
      'educationQuality.history.selectPeriod': "Davrni tanlang (o'quv yili + semestr)",
      'educationQuality.history.submitted': 'Yuborilgan',
      'educationQuality.history.totalScore': 'Umumiy ball',
      'educationQuality.indicatorDrawer.active': 'Faol',
      'educationQuality.indicatorDrawer.addField': "Maydon qo'shish",
      'educationQuality.indicatorDrawer.coefficientRequired': 'Bal majburiy',
      'educationQuality.indicatorDrawer.createTitle': 'Yangi indikator',
      'educationQuality.indicatorDrawer.descLabel': "Ma'nosi (tavsifi)",
      'educationQuality.indicatorDrawer.descPlaceholder': 'Indikator nimani anglatadi',
      'educationQuality.indicatorDrawer.editTitle': 'Indikatorni tahrirlash',
      'educationQuality.indicatorDrawer.fieldLabelPlaceholder': 'Maydon nomi',
      'educationQuality.indicatorDrawer.fieldsSection': "Qabul qilinadigan ma'lumot maydonlari",
      'educationQuality.indicatorDrawer.inactive': 'Nofaol',
      'educationQuality.indicatorDrawer.nameLabel': 'Indikator nomi',
      'educationQuality.indicatorDrawer.namePlaceholder': 'Masalan: Xalqaro jurnallardagi ilmiy maqolalar',
      'educationQuality.indicatorDrawer.nameRequired': 'Nomi majburiy',
      'educationQuality.indicatorDrawer.optional': 'Ixtiyoriy',
      'educationQuality.indicatorDrawer.required': 'Majburiy',
      'educationQuality.indicatorDrawer.typePlaceholder': 'Tur',
      'educationQuality.indicators.active': 'Faol',
      'educationQuality.indicators.created': "Indikator qo'shildi",
      'educationQuality.indicators.deleteBody': '"{{title}}" indikatori o\'chiriladi.',
      'educationQuality.indicators.deleteBlocked': "«{{title}}» indikatori bo'yicha {{count}} ta ma'lumot yuborilgan — o'chirib bo'lmaydi.",
      'educationQuality.indicators.deleteBlockedHint': "O'chirish o'rniga ro'yxatdagi holat tugmasi bilan nofaol qilib qo'ying — shunda yuborilgan ma'lumotlar saqlanib qoladi.",
      'educationQuality.indicators.deleteFailed': "Indikatorni o'chirib bo'lmadi",
      'educationQuality.indicators.deleteTitle': "Indikatorni o'chirish",
      'educationQuality.indicators.deleted': "Indikator o'chirildi",
      'educationQuality.indicators.desc': 'Tavsif',
      'educationQuality.indicators.exportEmpty': "Eksport uchun ma'lumot yo'q",
      'educationQuality.indicators.fieldCount': 'Maydonlar soni',
      'educationQuality.indicators.fields': 'Maydonlar',
      'educationQuality.indicators.fieldsCount': '{{count}} ta',
      'educationQuality.indicators.inactive': 'Nofaol',
      'educationQuality.indicators.name': 'Indikator nomi',
      'educationQuality.indicators.newButton': 'Yangi indikator',
      'educationQuality.indicators.searchPlaceholder': "Nomi bo'yicha qidirish",
      'educationQuality.indicators.subtitle': 'Baholash mezonlari — milliy reyting indikatorlarini boshqarish',
      'educationQuality.indicators.title': 'Indikatorlar',
      'educationQuality.indicators.totalLabel': 'Jami indikatorlar',
      'educationQuality.indicators.updated': 'Indikator yangilandi',
      'educationQuality.myData.subtitle': "Yuborilgan, tasdiqlangan va rad etilgan ma'lumotlaringiz",
      'educationQuality.myData.title': "Mening ma'lumotlarim",
      'educationQuality.nav.announcements': "E'lonlar",
      'educationQuality.nav.indicators': 'Indikatorlar',
      'educationQuality.nav.myData': "Mening ma'lumotlarim",
      'educationQuality.nav.reportDepartment': 'Kafedralar',
      'educationQuality.nav.reportFaculty': 'Fakultetlar',
      'educationQuality.nav.reportTeacher': "O'qituvchilar",
      'educationQuality.nav.reports': 'Hisobotlar',
      'educationQuality.nav.submit': "Ma'lumot yuborish",
      'educationQuality.nav.teacherAnnouncements': "E'lonlar",
      'educationQuality.nav.verification': 'Tekshirish',
      'educationQuality.pagination.rowsPerPage': 'Jadval qatorlari:',
      'educationQuality.pagination.total': 'Jami: {{count}}',
      'educationQuality.pagination.totalNamed': '{{name}}: {{count}}',
      'educationQuality.reports.active': 'Faol',
      'educationQuality.reports.activeFrom': "Faol bo'lish sanasi",
      'educationQuality.reports.allEmploymentTypes': 'Barcha turlar',
      'educationQuality.reports.avgScore': "O'rtacha ball",
      'educationQuality.reports.belowThreshold': '25 balldan past',
      'educationQuality.reports.countItems': '{{count}} ta',
      'educationQuality.reports.dateReached': 'sana keldi',
      'educationQuality.reports.departmentChartTitle': "Kafedralar reytingi (o'rtacha ball)",
      'educationQuality.reports.departmentDesc': 'Kafedralar kesimida milliy reyting ballari',
      'educationQuality.reports.departmentTitle': 'Kafedralar hisoboti',
      'educationQuality.reports.departments': 'Kafedralar',
      'educationQuality.reports.deptCount': '{{count}} ta kafedra',
      'educationQuality.reports.downloadFiles': 'Fayllarni yuklash',
      'educationQuality.reports.employmentAsosiy': 'Asosiy',
      'educationQuality.reports.employmentOrindosh': "O'rindosh",
      'educationQuality.reports.employmentType': 'Mehnat turi',
      'educationQuality.reports.exportDepartmentFile': 'Hisobot-kafedralar',
      'educationQuality.reports.exportFacultyFile': 'Hisobot-fakultetlar',
      'educationQuality.reports.exportTeacherFile': 'Hisobot-oqituvchilar',
      'educationQuality.reports.faculties': 'Fakultetlar',
      'educationQuality.reports.facultyChartTitle': "Fakultetlar reytingi (o'rtacha ball)",
      'educationQuality.reports.facultyDesc': 'Fakultetlar kesimida milliy reyting ballari',
      'educationQuality.reports.facultyTitle': 'Fakultetlar hisoboti',
      'educationQuality.reports.inactive': 'Nofaol',
      'educationQuality.reports.indicators': 'Indikatorlar',
      'educationQuality.reports.noExportData': "Eksport uchun ma'lumot yo'q",
      'educationQuality.reports.noFiles': 'Yuklangan fayl topilmadi',
      'educationQuality.reports.pickDate': 'Sanani tanlang',
      'educationQuality.reports.rank': "O'rin",
      'educationQuality.reports.redTag': '{{count}} ta · {{share}}%',
      'educationQuality.reports.scoreValue': '{{score}} ball',
      'educationQuality.reports.searchTeacher': "F.I.Sh bo'yicha qidirish",
      'educationQuality.reports.teacherDesc': "Professor-o'qituvchilar kesimida milliy reyting ballari",
      'educationQuality.reports.teacherTitle': "O'qituvchilar hisoboti",
      'educationQuality.reports.teachers': "O'qituvchilar",
      'educationQuality.reports.totalDepartments': 'Jami kafedralar',
      'educationQuality.reports.totalFaculties': 'Jami fakultetlar',
      'educationQuality.reports.totalScore': 'Jami ball',
      'educationQuality.reports.totalTeachers': "Jami o'qituvchilar",
      'educationQuality.semester.placeholder': 'Semestrni tanlang',
      'educationQuality.semester.s1': '1-semestr',
      'educationQuality.semester.s2': '2-semestr',
      'educationQuality.status.approved': 'Tasdiqlangan',
      'educationQuality.status.new': 'Yangi',
      'educationQuality.status.pending': 'Tekshirilmoqda',
      'educationQuality.status.rejected': 'Rad etilgan',
      'educationQuality.submit.authorsCount': 'Mualliflar soni',
      'educationQuality.submit.authorsTooltip': "Ball mualliflar soniga bo'linadi",
      'educationQuality.submit.dateUnset': 'belgilanmagan',
      'educationQuality.submit.pickHint': "Ma'lumot yuborish uchun chapdan indikatorni tanlang",
      'educationQuality.submit.points': '{{count}} ball',
      'educationQuality.submit.restricted': "Siz faolligingiz cheklangan, faol bo'lish sanasi: {{date}}",
      'educationQuality.submit.send': 'Yuborish',
      'educationQuality.submit.subtitle': "Indikatorni tanlang va talab qilingan ma'lumotlarni yuboring",
      'educationQuality.submit.success': "Ma'lumot yuborildi. Tekshiruvdan so'ng ball biriktiriladi.",
      'educationQuality.submit.title': "Ma'lumot yuborish",
      'educationQuality.submit.yearPlaceholder': "O'quv yilini tanlang",
      'educationQuality.teacherAnnouncements.dateFrom': 'dan',
      'educationQuality.teacherAnnouncements.dateTo': 'gacha',
      'educationQuality.teacherAnnouncements.empty': "Hozircha e'lon yo'q",
      'educationQuality.teacherAnnouncements.emptyFiltered': "Filtrlarga mos e'lon topilmadi",
      'educationQuality.teacherAnnouncements.searchPlaceholder': "Sarlavha yoki matn bo'yicha qidirish",
      'educationQuality.teacherAnnouncements.subtitle': "Ta'lim sifatini ta'minlash bo'limidan e'lonlar",
      'educationQuality.teacherAnnouncements.title': "E'lonlar",
      'educationQuality.teacherDetail.active': 'Faol',
      'educationQuality.teacherDetail.activeFrom': "Faol bo'lish sanasi: {{date}}",
      'educationQuality.teacherDetail.inactive': 'Nofaol',
      'educationQuality.teacherDetail.notFound': "O'qituvchi topilmadi",
      'educationQuality.verification.approve': 'Tasdiqlash',
      'educationQuality.verification.approveScoreLabel': 'Tasdiqlangach biriktiriladigan ball:',
      'educationQuality.verification.approveSuccess': "Ma'lumot tasdiqlandi va ball biriktirildi",
      'educationQuality.verification.approveTitle': "Ma'lumotni tasdiqlaysizmi?",
      'educationQuality.verification.empty': "Ma'lumot topilmadi",
      'educationQuality.verification.emptyPending': "Tekshirishni kutayotgan ma'lumot yo'q",
      'educationQuality.verification.exportEmpty': "Eksport uchun ma'lumot yo'q",
      'educationQuality.verification.filterTitle': 'Filtrlash',
      'educationQuality.verification.reasonPlaceholder': 'Masalan: Yuklangan fayl talabga javob bermaydi...',
      'educationQuality.verification.reject': 'Rad etish',
      'educationQuality.verification.rejectHint': "Rad etish sababini batafsil yozing. Sabab o'qituvchiga ko'rinadi.",
      'educationQuality.verification.rejectSuccess': "Ma'lumot rad etildi",
      'educationQuality.verification.rejectTitle': "Ma'lumotni rad etish",
      'educationQuality.verification.searchPlaceholder': "Ism familiya bo'yicha qidirish",
      'educationQuality.verification.submittedByLabel': 'Yuborgan:',
      'educationQuality.verification.subtitle': "Professor-o'qituvchilar yuborgan ma'lumotlarni ko'rib chiqish, tasdiqlash va arxiv",
      'educationQuality.verification.title': 'Tekshirish',
      'menuGroup.educationQuality': "Ta'lim sifati",
    },
    ru: {
      'educationQuality.announcements.contentPlaceholder': 'Текст объявления...',
      'educationQuality.announcements.contentRequired': 'Укажите содержание',
      'educationQuality.announcements.created': 'Объявление отправлено',
      'educationQuality.announcements.dateFrom': 'С',
      'educationQuality.announcements.dateTo': 'По',
      'educationQuality.announcements.deleteBody': 'Объявление «{{title}}» будет удалено.',
      'educationQuality.announcements.deleteTitle': 'Удаление объявления',
      'educationQuality.announcements.deleted': 'Объявление удалено',
      'educationQuality.announcements.empty': 'Объявлений пока нет',
      'educationQuality.announcements.emptyFiltered': 'По выбранным фильтрам объявлений нет',
      'educationQuality.announcements.formContent': 'Содержание',
      'educationQuality.announcements.formTitle': 'Заголовок',
      'educationQuality.announcements.new': 'Новое объявление',
      'educationQuality.announcements.searchPlaceholder': 'Поиск по заголовку или тексту',
      'educationQuality.announcements.send': 'Отправить',
      'educationQuality.announcements.subtitle': 'Отправка объявления всем преподавателям',
      'educationQuality.announcements.title': 'Объявления',
      'educationQuality.announcements.titlePlaceholder': 'Заголовок объявления',
      'educationQuality.announcements.titleRequired': 'Укажите заголовок',
      'educationQuality.common.academicYear': 'Учебный год',
      'educationQuality.common.actions': 'Действия',
      'educationQuality.common.all': 'Все',
      'educationQuality.common.allDepartments': 'Все кафедры',
      'educationQuality.common.allFaculties': 'Все факультеты',
      'educationQuality.common.allIndicators': 'Все индикаторы',
      'educationQuality.common.allSemesters': 'Все семестры',
      'educationQuality.common.allStatuses': 'Все статусы',
      'educationQuality.common.allYears': 'Все учебные годы',
      'educationQuality.common.apply': 'Применить',
      'educationQuality.common.authors': 'Авторы',
      'educationQuality.common.back': 'Назад',
      'educationQuality.common.cancel': 'Отмена',
      'educationQuality.common.clear': 'Сбросить',
      'educationQuality.common.close': 'Закрыть',
      'educationQuality.common.date': 'Дата',
      'educationQuality.common.delete': 'Удалить',
      'educationQuality.common.department': 'Кафедра',
      'educationQuality.common.details': 'Подробнее',
      'educationQuality.common.edit': 'Редактировать',
      'educationQuality.common.exportExcel': 'Выгрузить в Excel',
      'educationQuality.common.exportFailed': 'Не удалось выгрузить в Excel',
      'educationQuality.common.faculty': 'Факультет',
      'educationQuality.common.filter': 'Фильтр',
      'educationQuality.common.indicator': 'Индикатор',
      'educationQuality.common.irreversible': 'Это действие нельзя отменить.',
      'educationQuality.common.save': 'Сохранить',
      'educationQuality.common.score': 'Балл',
      'educationQuality.common.semester': 'Семестр',
      'educationQuality.common.status': 'Статус',
      'educationQuality.common.teacher': 'Преподаватель',
      'educationQuality.common.total': 'Всего',
      'educationQuality.common.view': 'Просмотр',
      'educationQuality.drawer.approve': 'Подтвердить',
      'educationQuality.drawer.authorCount': 'Число авторов',
      'educationQuality.drawer.coeffDefault': 'по умолчанию: 1 / {{count}} авторов',
      'educationQuality.drawer.coefficient': 'Коэффициент',
      'educationQuality.drawer.coefficientValue': 'коэффициент {{coeff}}',
      'educationQuality.drawer.confirmTitle': 'Подтвердить данные?',
      'educationQuality.drawer.estimatedNote': 'Примерный балл при подтверждении ({{base}} балл x {{coeff}} коэффициент)',
      'educationQuality.drawer.indicatorScore': 'Балл индикатора',
      'educationQuality.drawer.moneyValue': '{{amount}} сум',
      'educationQuality.drawer.openLink': 'Открыть ссылку',
      'educationQuality.drawer.pdfFile': 'PDF-файл',
      'educationQuality.drawer.points': '{{score}} балл',
      'educationQuality.drawer.reject': 'Отклонить',
      'educationQuality.drawer.rejectHint': 'Подробно укажите причину отклонения. Причина будет видна преподавателю.',
      'educationQuality.drawer.rejectPlaceholder': 'Например: загруженный файл не соответствует требованиям...',
      'educationQuality.drawer.rejectReason': 'Причина отклонения',
      'educationQuality.drawer.rejectTitle': 'Отклонить данные',
      'educationQuality.drawer.scoreFormula': '{{base}} балл x {{coeff}} коэффициент',
      'educationQuality.drawer.scoreOnApproval': 'Балл после подтверждения',
      'educationQuality.drawer.submittedAt': 'Дата отправки',
      'educationQuality.drawer.submittedBy': 'Отправил',
      'educationQuality.drawer.submittedData': 'Отправленные данные',
      'educationQuality.drawer.title': 'Просмотр данных',
      'educationQuality.dynamicField.currency': 'сум',
      'educationQuality.dynamicField.datePlaceholder': 'Выберите дату',
      'educationQuality.dynamicField.required': '{{label}} — обязательное поле',
      'educationQuality.dynamicField.selectPlaceholder': 'Выберите',
      'educationQuality.dynamicField.uploadPdf': 'Загрузить PDF-файл',
      'educationQuality.field.activityName': 'Название мероприятия',
      'educationQuality.field.antiplagiatReport': 'Отчёт «Антиплагиат»',
      'educationQuality.field.articleFile': 'Файл статьи',
      'educationQuality.field.articleTitle': 'Название статьи',
      'educationQuality.field.authors': 'Авторы',
      'educationQuality.field.authorsCount': 'Количество авторов',
      'educationQuality.field.authorsName': 'Ф.И.О. автора(ов)',
      'educationQuality.field.basisType': 'Тип основания',
      'educationQuality.field.certificateFile': 'Файл сертификата',
      'educationQuality.field.certificateName': 'Название сертификата',
      'educationQuality.field.citationCount': 'Количество цитирований',
      'educationQuality.field.comment': 'Комментарий',
      'educationQuality.field.competitionName': 'Название конкурса',
      'educationQuality.field.conferenceName': 'Название конференции',
      'educationQuality.field.contractFile': 'Файл договора',
      'educationQuality.field.cooperationDocName': 'Название документа о сотрудничестве',
      'educationQuality.field.councilCertificate': 'Свидетельство совета',
      'educationQuality.field.councilDecision': 'Решение совета',
      'educationQuality.field.country': 'Страна',
      'educationQuality.field.currentYearAmount': 'Сумма за текущий год',
      'educationQuality.field.date': 'Дата',
      'educationQuality.field.departmentMinutes': 'Протокол кафедры',
      'educationQuality.field.diplomaFile': 'Файл диплома',
      'educationQuality.field.diplomaNumber': 'Номер диплома',
      'educationQuality.field.diplomaSeries': 'Серия диплома',
      'educationQuality.field.directionName': 'Название направления',
      'educationQuality.field.dissertationTopic': 'Тема диссертации',
      'educationQuality.field.doctorDiplomaNumber': 'Номер докторского диплома',
      'educationQuality.field.doctorDiplomaSeries': 'Серия докторского диплома',
      'educationQuality.field.dscNumber': 'Номер диплома DSc',
      'educationQuality.field.dscSeries': 'Серия диплома DSc',
      'educationQuality.field.duration': 'Продолжительность',
      'educationQuality.field.expiryDate': 'Срок действия',
      'educationQuality.field.externalReview': 'Внешняя рецензия',
      'educationQuality.field.foreignOtm': 'Название зарубежного вуза',
      'educationQuality.field.googleScholarUrl': 'Ссылка Google Scholar',
      'educationQuality.field.grantName': 'Название гранта',
      'educationQuality.field.grantTopic': 'Тема гранта',
      'educationQuality.field.internalReview': 'Внутренняя рецензия',
      'educationQuality.field.invitationFile': 'Файл приглашения',
      'educationQuality.field.isbn': 'ISBN',
      'educationQuality.field.issuedDate': 'Дата выдачи',
      'educationQuality.field.journalName': 'Название журнала',
      'educationQuality.field.level': 'Уровень',
      'educationQuality.field.manualFile': 'Файл пособия',
      'educationQuality.field.manualName': 'Название пособия',
      'educationQuality.field.ministerCertFile': 'Файл сертификата министерства',
      'educationQuality.field.ministerOrderFile': 'Файл приказа министерства',
      'educationQuality.field.monographFile': 'Файл монографии',
      'educationQuality.field.monographTitle': 'Название монографии',
      'educationQuality.field.orderName': 'Название приказа',
      'educationQuality.field.otmName': 'Название вуза',
      'educationQuality.field.pages': 'Страницы',
      'educationQuality.field.participationType': 'Форма участия',
      'educationQuality.field.passportStampFile': 'Файл паспортного штампа',
      'educationQuality.field.patentName': 'Название патента',
      'educationQuality.field.phdNumber': 'Номер диплома PhD',
      'educationQuality.field.phdSeries': 'Серия диплома PhD',
      'educationQuality.field.place': 'Место',
      'educationQuality.field.professorDiplomaNumber': 'Номер профессорского диплома',
      'educationQuality.field.professorDiplomaSeries': 'Серия профессорского диплома',
      'educationQuality.field.programFile': 'Файл программы',
      'educationQuality.field.publishLicenseFile': 'Файл лицензии на издание',
      'educationQuality.field.publishYear': 'Год издания',
      'educationQuality.field.publisher': 'Издательство',
      'educationQuality.field.rankObtainedDate': 'Дата получения звания',
      'educationQuality.field.receiptFile': 'Файл квитанции',
      'educationQuality.field.rectorOrderFile': 'Файл приказа ректора',
      'educationQuality.field.referralFile': 'Файл направления',
      'educationQuality.field.registrationNumber': 'Регистрационный номер',
      'educationQuality.field.reportFile': 'Файл отчёта',
      'educationQuality.field.rewardOrderFile': 'Файл приказа о награждении',
      'educationQuality.field.scopusUrl': 'Ссылка Scopus',
      'educationQuality.field.signedDate': 'Дата подписания',
      'educationQuality.field.specialty': 'Специальность',
      'educationQuality.field.specialtyCode': 'Шифр специальности',
      'educationQuality.field.ssvConclusion': 'Заключение Минздрава',
      'educationQuality.field.studentName': 'Ф.И.О. студента',
      'educationQuality.field.teacherName': 'Ф.И.О. преподавателя',
      'educationQuality.field.textbookName': 'Название учебника',
      'educationQuality.field.thesisFile': 'Файл тезисов',
      'educationQuality.field.thesisTitle': 'Название тезисов',
      'educationQuality.field.titleFile': 'Файл титульного листа',
      'educationQuality.field.topic': 'Тема',
      'educationQuality.field.totalAmount': 'Общая сумма',
      'educationQuality.field.url': 'Ссылка',
      'educationQuality.field.venue': 'Место проведения',
      'educationQuality.field.ziyonetCert': 'Сертификат Ziyonet',
      'educationQuality.fieldOption.buyruq': 'Приказ',
      'educationQuality.fieldOption.oflayn': 'Офлайн',
      'educationQuality.fieldOption.onlayn': 'Онлайн',
      'educationQuality.fieldOption.qaror': 'Решение',
      'educationQuality.fieldOption.shartnoma': 'Договор',
      'educationQuality.fieldType.date': 'Дата',
      'educationQuality.fieldType.file': 'Файл (PDF)',
      'educationQuality.fieldType.money': 'Сумма',
      'educationQuality.fieldType.number': 'Число',
      'educationQuality.fieldType.text': 'Текст',
      'educationQuality.fieldType.textarea': 'Многострочный текст',
      'educationQuality.fieldType.url': 'Ссылка (URL)',
      'educationQuality.history.empty': 'Данные не найдены',
      'educationQuality.history.exportFile': 'Dannye',
      'educationQuality.history.exportSheet': 'Данные',
      'educationQuality.history.minRequired': 'Требование: не менее {{score}} баллов',
      'educationQuality.history.noExportData': 'Нет данных для экспорта',
      'educationQuality.history.searchPlaceholder': 'Поиск по индикатору',
      'educationQuality.history.selectPeriod': 'Выберите период (учебный год + семестр)',
      'educationQuality.history.submitted': 'Отправлено',
      'educationQuality.history.totalScore': 'Общий балл',
      'educationQuality.indicatorDrawer.active': 'Активен',
      'educationQuality.indicatorDrawer.addField': 'Добавить поле',
      'educationQuality.indicatorDrawer.coefficientRequired': 'Балл обязателен',
      'educationQuality.indicatorDrawer.createTitle': 'Новый индикатор',
      'educationQuality.indicatorDrawer.descLabel': 'Значение (описание)',
      'educationQuality.indicatorDrawer.descPlaceholder': 'Что означает индикатор',
      'educationQuality.indicatorDrawer.editTitle': 'Редактирование индикатора',
      'educationQuality.indicatorDrawer.fieldLabelPlaceholder': 'Название поля',
      'educationQuality.indicatorDrawer.fieldsSection': 'Принимаемые поля данных',
      'educationQuality.indicatorDrawer.inactive': 'Неактивен',
      'educationQuality.indicatorDrawer.nameLabel': 'Название индикатора',
      'educationQuality.indicatorDrawer.namePlaceholder': 'Например: научные статьи в международных журналах',
      'educationQuality.indicatorDrawer.nameRequired': 'Название обязательно',
      'educationQuality.indicatorDrawer.optional': 'Необязательно',
      'educationQuality.indicatorDrawer.required': 'Обязательно',
      'educationQuality.indicatorDrawer.typePlaceholder': 'Тип',
      'educationQuality.indicators.active': 'Активен',
      'educationQuality.indicators.created': 'Индикатор добавлен',
      'educationQuality.indicators.deleteBody': 'Индикатор "{{title}}" будет удалён.',
      'educationQuality.indicators.deleteBlocked': "По индикатору «{{title}}» отправлено записей: {{count}} — удалить нельзя.",
      'educationQuality.indicators.deleteBlockedHint': "Вместо удаления отключите его переключателем в списке — отправленные данные сохранятся.",
      'educationQuality.indicators.deleteFailed': "Не удалось удалить индикатор",
      'educationQuality.indicators.deleteTitle': 'Удаление индикатора',
      'educationQuality.indicators.deleted': 'Индикатор удалён',
      'educationQuality.indicators.desc': 'Описание',
      'educationQuality.indicators.exportEmpty': 'Нет данных для экспорта',
      'educationQuality.indicators.fieldCount': 'Количество полей',
      'educationQuality.indicators.fields': 'Поля',
      'educationQuality.indicators.fieldsCount': '{{count}} шт.',
      'educationQuality.indicators.inactive': 'Неактивен',
      'educationQuality.indicators.name': 'Название индикатора',
      'educationQuality.indicators.newButton': 'Новый индикатор',
      'educationQuality.indicators.searchPlaceholder': 'Поиск по названию',
      'educationQuality.indicators.subtitle': 'Критерии оценки — управление индикаторами национального рейтинга',
      'educationQuality.indicators.title': 'Индикаторы',
      'educationQuality.indicators.totalLabel': 'Всего индикаторов',
      'educationQuality.indicators.updated': 'Индикатор обновлён',
      'educationQuality.myData.subtitle': 'Ваши отправленные, подтверждённые и отклонённые данные',
      'educationQuality.myData.title': 'Мои данные',
      'educationQuality.nav.announcements': 'Объявления',
      'educationQuality.nav.indicators': 'Индикаторы',
      'educationQuality.nav.myData': 'Мои данные',
      'educationQuality.nav.reportDepartment': 'Кафедры',
      'educationQuality.nav.reportFaculty': 'Факультеты',
      'educationQuality.nav.reportTeacher': 'Преподаватели',
      'educationQuality.nav.reports': 'Отчёты',
      'educationQuality.nav.submit': 'Отправить данные',
      'educationQuality.nav.teacherAnnouncements': 'Объявления',
      'educationQuality.nav.verification': 'Проверка',
      'educationQuality.pagination.rowsPerPage': 'Строк в таблице:',
      'educationQuality.pagination.total': 'Всего: {{count}}',
      'educationQuality.pagination.totalNamed': '{{name}}: {{count}}',
      'educationQuality.reports.active': 'Активен',
      'educationQuality.reports.activeFrom': 'Дата активации',
      'educationQuality.reports.allEmploymentTypes': 'Все типы',
      'educationQuality.reports.avgScore': 'Средний балл',
      'educationQuality.reports.belowThreshold': 'Ниже 25 баллов',
      'educationQuality.reports.countItems': '{{count}} шт.',
      'educationQuality.reports.dateReached': 'дата наступила',
      'educationQuality.reports.departmentChartTitle': 'Рейтинг кафедр (средний балл)',
      'educationQuality.reports.departmentDesc': 'Баллы национального рейтинга по кафедрам',
      'educationQuality.reports.departmentTitle': 'Отчёт по кафедрам',
      'educationQuality.reports.departments': 'Кафедры',
      'educationQuality.reports.deptCount': 'кафедр: {{count}}',
      'educationQuality.reports.downloadFiles': 'Скачать файлы',
      'educationQuality.reports.employmentAsosiy': 'Основной',
      'educationQuality.reports.employmentOrindosh': 'Совместитель',
      'educationQuality.reports.employmentType': 'Тип занятости',
      'educationQuality.reports.exportDepartmentFile': 'Отчёт-кафедры',
      'educationQuality.reports.exportFacultyFile': 'Отчёт-факультеты',
      'educationQuality.reports.exportTeacherFile': 'Отчёт-преподаватели',
      'educationQuality.reports.faculties': 'Факультеты',
      'educationQuality.reports.facultyChartTitle': 'Рейтинг факультетов (средний балл)',
      'educationQuality.reports.facultyDesc': 'Баллы национального рейтинга по факультетам',
      'educationQuality.reports.facultyTitle': 'Отчёт по факультетам',
      'educationQuality.reports.inactive': 'Неактивен',
      'educationQuality.reports.indicators': 'Индикаторы',
      'educationQuality.reports.noExportData': 'Нет данных для экспорта',
      'educationQuality.reports.noFiles': 'Загруженные файлы не найдены',
      'educationQuality.reports.pickDate': 'Выберите дату',
      'educationQuality.reports.rank': 'Место',
      'educationQuality.reports.redTag': '{{count}} · {{share}}%',
      'educationQuality.reports.scoreValue': '{{score}} баллов',
      'educationQuality.reports.searchTeacher': 'Поиск по Ф.И.О.',
      'educationQuality.reports.teacherDesc': 'Баллы национального рейтинга по преподавательскому составу',
      'educationQuality.reports.teacherTitle': 'Отчёт по преподавателям',
      'educationQuality.reports.teachers': 'Преподаватели',
      'educationQuality.reports.totalDepartments': 'Всего кафедр',
      'educationQuality.reports.totalFaculties': 'Всего факультетов',
      'educationQuality.reports.totalScore': 'Всего баллов',
      'educationQuality.reports.totalTeachers': 'Всего преподавателей',
      'educationQuality.semester.placeholder': 'Выберите семестр',
      'educationQuality.semester.s1': '1-й семестр',
      'educationQuality.semester.s2': '2-й семестр',
      'educationQuality.status.approved': 'Подтверждён',
      'educationQuality.status.new': 'Новый',
      'educationQuality.status.pending': 'На проверке',
      'educationQuality.status.rejected': 'Отклонён',
      'educationQuality.submit.authorsCount': 'Количество авторов',
      'educationQuality.submit.authorsTooltip': 'Балл делится на количество авторов',
      'educationQuality.submit.dateUnset': 'не указана',
      'educationQuality.submit.pickHint': 'Выберите индикатор слева, чтобы отправить данные',
      'educationQuality.submit.points': '{{count}} балл(ов)',
      'educationQuality.submit.restricted': 'Ваша активность ограничена, дата возобновления: {{date}}',
      'educationQuality.submit.send': 'Отправить',
      'educationQuality.submit.subtitle': 'Выберите индикатор и отправьте требуемые данные',
      'educationQuality.submit.success': 'Данные отправлены. Балл будет начислен после проверки.',
      'educationQuality.submit.title': 'Отправка данных',
      'educationQuality.submit.yearPlaceholder': 'Выберите учебный год',
      'educationQuality.teacherAnnouncements.dateFrom': 'С',
      'educationQuality.teacherAnnouncements.dateTo': 'По',
      'educationQuality.teacherAnnouncements.empty': 'Объявлений пока нет',
      'educationQuality.teacherAnnouncements.emptyFiltered': 'По выбранным фильтрам объявлений нет',
      'educationQuality.teacherAnnouncements.searchPlaceholder': 'Поиск по заголовку или тексту',
      'educationQuality.teacherAnnouncements.subtitle': 'Объявления отдела обеспечения качества образования',
      'educationQuality.teacherAnnouncements.title': 'Объявления',
      'educationQuality.teacherDetail.active': 'Активен',
      'educationQuality.teacherDetail.activeFrom': 'Дата возобновления: {{date}}',
      'educationQuality.teacherDetail.inactive': 'Неактивен',
      'educationQuality.teacherDetail.notFound': 'Преподаватель не найден',
      'educationQuality.verification.approve': 'Подтвердить',
      'educationQuality.verification.approveScoreLabel': 'Балл после подтверждения:',
      'educationQuality.verification.approveSuccess': 'Данные подтверждены, балл начислен',
      'educationQuality.verification.approveTitle': 'Подтвердить данные?',
      'educationQuality.verification.empty': 'Данные не найдены',
      'educationQuality.verification.emptyPending': 'Нет данных, ожидающих проверки',
      'educationQuality.verification.exportEmpty': 'Нет данных для экспорта',
      'educationQuality.verification.filterTitle': 'Фильтры',
      'educationQuality.verification.reasonPlaceholder': 'Например: загруженный файл не соответствует требованиям...',
      'educationQuality.verification.reject': 'Отклонить',
      'educationQuality.verification.rejectHint': 'Подробно опишите причину отклонения — её увидит преподаватель.',
      'educationQuality.verification.rejectSuccess': 'Данные отклонены',
      'educationQuality.verification.rejectTitle': 'Отклонение данных',
      'educationQuality.verification.searchPlaceholder': 'Поиск по имени и фамилии',
      'educationQuality.verification.submittedByLabel': 'Отправил:',
      'educationQuality.verification.subtitle': 'Просмотр, подтверждение и архив данных, отправленных преподавателями',
      'educationQuality.verification.title': 'Проверка',
      'menuGroup.educationQuality': 'Качество образования',
    },
    en: {
      'educationQuality.announcements.contentPlaceholder': 'Announcement text...',
      'educationQuality.announcements.contentRequired': 'Content is required',
      'educationQuality.announcements.created': 'Announcement sent',
      'educationQuality.announcements.dateFrom': 'From',
      'educationQuality.announcements.dateTo': 'To',
      'educationQuality.announcements.deleteBody': 'The announcement "{{title}}" will be deleted.',
      'educationQuality.announcements.deleteTitle': 'Delete announcement',
      'educationQuality.announcements.deleted': 'Announcement deleted',
      'educationQuality.announcements.empty': 'No announcements yet',
      'educationQuality.announcements.emptyFiltered': 'No announcements match the filters',
      'educationQuality.announcements.formContent': 'Content',
      'educationQuality.announcements.formTitle': 'Title',
      'educationQuality.announcements.new': 'New announcement',
      'educationQuality.announcements.searchPlaceholder': 'Search by title or text',
      'educationQuality.announcements.send': 'Send',
      'educationQuality.announcements.subtitle': 'Send an announcement to all faculty members',
      'educationQuality.announcements.title': 'Announcements',
      'educationQuality.announcements.titlePlaceholder': 'Announcement title',
      'educationQuality.announcements.titleRequired': 'Title is required',
      'educationQuality.common.academicYear': 'Academic year',
      'educationQuality.common.actions': 'Actions',
      'educationQuality.common.all': 'All',
      'educationQuality.common.allDepartments': 'All departments',
      'educationQuality.common.allFaculties': 'All faculties',
      'educationQuality.common.allIndicators': 'All indicators',
      'educationQuality.common.allSemesters': 'All semesters',
      'educationQuality.common.allStatuses': 'All statuses',
      'educationQuality.common.allYears': 'All academic years',
      'educationQuality.common.apply': 'Apply',
      'educationQuality.common.authors': 'Authors',
      'educationQuality.common.back': 'Back',
      'educationQuality.common.cancel': 'Cancel',
      'educationQuality.common.clear': 'Clear',
      'educationQuality.common.close': 'Close',
      'educationQuality.common.date': 'Date',
      'educationQuality.common.delete': 'Delete',
      'educationQuality.common.department': 'Department',
      'educationQuality.common.details': 'Details',
      'educationQuality.common.edit': 'Edit',
      'educationQuality.common.exportExcel': 'Export to Excel',
      'educationQuality.common.exportFailed': 'Export failed',
      'educationQuality.common.faculty': 'Faculty',
      'educationQuality.common.filter': 'Filter',
      'educationQuality.common.indicator': 'Indicator',
      'educationQuality.common.irreversible': 'This action cannot be undone.',
      'educationQuality.common.save': 'Save',
      'educationQuality.common.score': 'Score',
      'educationQuality.common.semester': 'Semester',
      'educationQuality.common.status': 'Status',
      'educationQuality.common.teacher': 'Teacher',
      'educationQuality.common.total': 'Total',
      'educationQuality.common.view': 'View',
      'educationQuality.drawer.approve': 'Approve',
      'educationQuality.drawer.authorCount': 'Number of authors',
      'educationQuality.drawer.coeffDefault': 'default: 1 / {{count}} authors',
      'educationQuality.drawer.coefficient': 'Coefficient',
      'educationQuality.drawer.coefficientValue': 'coefficient {{coeff}}',
      'educationQuality.drawer.confirmTitle': 'Approve this submission?',
      'educationQuality.drawer.estimatedNote': 'Estimated score on approval ({{base}} points x {{coeff}} coefficient)',
      'educationQuality.drawer.indicatorScore': 'Indicator score',
      'educationQuality.drawer.moneyValue': '{{amount}} UZS',
      'educationQuality.drawer.openLink': 'Open link',
      'educationQuality.drawer.pdfFile': 'PDF file',
      'educationQuality.drawer.points': '{{score}} points',
      'educationQuality.drawer.reject': 'Reject',
      'educationQuality.drawer.rejectHint': 'Describe the reason for rejection in detail. The teacher will see it.',
      'educationQuality.drawer.rejectPlaceholder': 'For example: the uploaded file does not meet the requirements...',
      'educationQuality.drawer.rejectReason': 'Rejection reason',
      'educationQuality.drawer.rejectTitle': 'Reject submission',
      'educationQuality.drawer.scoreFormula': '{{base}} points x {{coeff}} coefficient',
      'educationQuality.drawer.scoreOnApproval': 'Score on approval',
      'educationQuality.drawer.submittedAt': 'Submitted on',
      'educationQuality.drawer.submittedBy': 'Submitted by',
      'educationQuality.drawer.submittedData': 'Submitted data',
      'educationQuality.drawer.title': 'View submission',
      'educationQuality.dynamicField.currency': 'UZS',
      'educationQuality.dynamicField.datePlaceholder': 'Select a date',
      'educationQuality.dynamicField.required': '{{label}} is required',
      'educationQuality.dynamicField.selectPlaceholder': 'Select',
      'educationQuality.dynamicField.uploadPdf': 'Upload a PDF file',
      'educationQuality.field.activityName': 'Activity name',
      'educationQuality.field.antiplagiatReport': 'Anti-plagiarism report',
      'educationQuality.field.articleFile': 'Article file',
      'educationQuality.field.articleTitle': 'Article title',
      'educationQuality.field.authors': 'Authors',
      'educationQuality.field.authorsCount': 'Number of authors',
      'educationQuality.field.authorsName': 'Author(s) full name',
      'educationQuality.field.basisType': 'Basis type',
      'educationQuality.field.certificateFile': 'Certificate file',
      'educationQuality.field.certificateName': 'Certificate name',
      'educationQuality.field.citationCount': 'Citation count',
      'educationQuality.field.comment': 'Comment',
      'educationQuality.field.competitionName': 'Competition name',
      'educationQuality.field.conferenceName': 'Conference name',
      'educationQuality.field.contractFile': 'Contract file',
      'educationQuality.field.cooperationDocName': 'Cooperation document name',
      'educationQuality.field.councilCertificate': 'Council certificate',
      'educationQuality.field.councilDecision': 'Council decision',
      'educationQuality.field.country': 'Country',
      'educationQuality.field.currentYearAmount': 'Current year amount',
      'educationQuality.field.date': 'Date',
      'educationQuality.field.departmentMinutes': 'Department minutes',
      'educationQuality.field.diplomaFile': 'Diploma file',
      'educationQuality.field.diplomaNumber': 'Diploma number',
      'educationQuality.field.diplomaSeries': 'Diploma series',
      'educationQuality.field.directionName': 'Programme name',
      'educationQuality.field.dissertationTopic': 'Dissertation topic',
      'educationQuality.field.doctorDiplomaNumber': 'Doctoral diploma number',
      'educationQuality.field.doctorDiplomaSeries': 'Doctoral diploma series',
      'educationQuality.field.dscNumber': 'DSc diploma number',
      'educationQuality.field.dscSeries': 'DSc diploma series',
      'educationQuality.field.duration': 'Duration',
      'educationQuality.field.expiryDate': 'Expiry date',
      'educationQuality.field.externalReview': 'External review',
      'educationQuality.field.foreignOtm': 'Foreign university name',
      'educationQuality.field.googleScholarUrl': 'Google Scholar link',
      'educationQuality.field.grantName': 'Grant name',
      'educationQuality.field.grantTopic': 'Grant topic',
      'educationQuality.field.internalReview': 'Internal review',
      'educationQuality.field.invitationFile': 'Invitation file',
      'educationQuality.field.isbn': 'ISBN',
      'educationQuality.field.issuedDate': 'Issue date',
      'educationQuality.field.journalName': 'Journal name',
      'educationQuality.field.level': 'Level',
      'educationQuality.field.manualFile': 'Manual file',
      'educationQuality.field.manualName': 'Manual name',
      'educationQuality.field.ministerCertFile': 'Ministry certificate file',
      'educationQuality.field.ministerOrderFile': 'Ministry order file',
      'educationQuality.field.monographFile': 'Monograph file',
      'educationQuality.field.monographTitle': 'Monograph title',
      'educationQuality.field.orderName': 'Order name',
      'educationQuality.field.otmName': 'University name',
      'educationQuality.field.pages': 'Pages',
      'educationQuality.field.participationType': 'Participation type',
      'educationQuality.field.passportStampFile': 'Passport stamp file',
      'educationQuality.field.patentName': 'Patent name',
      'educationQuality.field.phdNumber': 'PhD diploma number',
      'educationQuality.field.phdSeries': 'PhD diploma series',
      'educationQuality.field.place': 'Place',
      'educationQuality.field.professorDiplomaNumber': 'Professor diploma number',
      'educationQuality.field.professorDiplomaSeries': 'Professor diploma series',
      'educationQuality.field.programFile': 'Programme file',
      'educationQuality.field.publishLicenseFile': 'Publishing licence file',
      'educationQuality.field.publishYear': 'Publication year',
      'educationQuality.field.publisher': 'Publisher',
      'educationQuality.field.rankObtainedDate': 'Rank award date',
      'educationQuality.field.receiptFile': 'Receipt file',
      'educationQuality.field.rectorOrderFile': 'Rector order file',
      'educationQuality.field.referralFile': 'Referral file',
      'educationQuality.field.registrationNumber': 'Registration number',
      'educationQuality.field.reportFile': 'Report file',
      'educationQuality.field.rewardOrderFile': 'Award order file',
      'educationQuality.field.scopusUrl': 'Scopus link',
      'educationQuality.field.signedDate': 'Signing date',
      'educationQuality.field.specialty': 'Speciality',
      'educationQuality.field.specialtyCode': 'Speciality code',
      'educationQuality.field.ssvConclusion': 'Ministry of Health conclusion',
      'educationQuality.field.studentName': 'Student full name',
      'educationQuality.field.teacherName': 'Teacher full name',
      'educationQuality.field.textbookName': 'Textbook name',
      'educationQuality.field.thesisFile': 'Thesis file',
      'educationQuality.field.thesisTitle': 'Thesis title',
      'educationQuality.field.titleFile': 'Title page file',
      'educationQuality.field.topic': 'Topic',
      'educationQuality.field.totalAmount': 'Total amount',
      'educationQuality.field.url': 'Link',
      'educationQuality.field.venue': 'Venue',
      'educationQuality.field.ziyonetCert': 'Ziyonet certificate',
      'educationQuality.fieldOption.buyruq': 'Order',
      'educationQuality.fieldOption.oflayn': 'Offline',
      'educationQuality.fieldOption.onlayn': 'Online',
      'educationQuality.fieldOption.qaror': 'Decision',
      'educationQuality.fieldOption.shartnoma': 'Contract',
      'educationQuality.fieldType.date': 'Date',
      'educationQuality.fieldType.file': 'File (PDF)',
      'educationQuality.fieldType.money': 'Amount',
      'educationQuality.fieldType.number': 'Number',
      'educationQuality.fieldType.text': 'Text',
      'educationQuality.fieldType.textarea': 'Long text',
      'educationQuality.fieldType.url': 'Link (URL)',
      'educationQuality.history.empty': 'No data found',
      'educationQuality.history.exportFile': 'Data',
      'educationQuality.history.exportSheet': 'Data',
      'educationQuality.history.minRequired': 'Required: at least {{score}} points',
      'educationQuality.history.noExportData': 'No data to export',
      'educationQuality.history.searchPlaceholder': 'Search by indicator',
      'educationQuality.history.selectPeriod': 'Select a period (academic year + semester)',
      'educationQuality.history.submitted': 'Submitted',
      'educationQuality.history.totalScore': 'Total score',
      'educationQuality.indicatorDrawer.active': 'Active',
      'educationQuality.indicatorDrawer.addField': 'Add field',
      'educationQuality.indicatorDrawer.coefficientRequired': 'Score is required',
      'educationQuality.indicatorDrawer.createTitle': 'New indicator',
      'educationQuality.indicatorDrawer.descLabel': 'Meaning (description)',
      'educationQuality.indicatorDrawer.descPlaceholder': 'What the indicator means',
      'educationQuality.indicatorDrawer.editTitle': 'Edit indicator',
      'educationQuality.indicatorDrawer.fieldLabelPlaceholder': 'Field name',
      'educationQuality.indicatorDrawer.fieldsSection': 'Accepted data fields',
      'educationQuality.indicatorDrawer.inactive': 'Inactive',
      'educationQuality.indicatorDrawer.nameLabel': 'Indicator name',
      'educationQuality.indicatorDrawer.namePlaceholder': 'For example: research papers in international journals',
      'educationQuality.indicatorDrawer.nameRequired': 'Name is required',
      'educationQuality.indicatorDrawer.optional': 'Optional',
      'educationQuality.indicatorDrawer.required': 'Required',
      'educationQuality.indicatorDrawer.typePlaceholder': 'Type',
      'educationQuality.indicators.active': 'Active',
      'educationQuality.indicators.created': 'Indicator added',
      'educationQuality.indicators.deleteBody': 'The indicator "{{title}}" will be deleted.',
      'educationQuality.indicators.deleteBlocked': "Indicator «{{title}}» has {{count}} submission(s) — it cannot be deleted.",
      'educationQuality.indicators.deleteBlockedHint': "Deactivate it with the status switch in the list instead — the submitted data stays intact.",
      'educationQuality.indicators.deleteFailed': "Could not delete the indicator",
      'educationQuality.indicators.deleteTitle': 'Delete indicator',
      'educationQuality.indicators.deleted': 'Indicator deleted',
      'educationQuality.indicators.desc': 'Description',
      'educationQuality.indicators.exportEmpty': 'No data to export',
      'educationQuality.indicators.fieldCount': 'Number of fields',
      'educationQuality.indicators.fields': 'Fields',
      'educationQuality.indicators.fieldsCount': '{{count}}',
      'educationQuality.indicators.inactive': 'Inactive',
      'educationQuality.indicators.name': 'Indicator name',
      'educationQuality.indicators.newButton': 'New indicator',
      'educationQuality.indicators.searchPlaceholder': 'Search by name',
      'educationQuality.indicators.subtitle': 'Assessment criteria — manage national rating indicators',
      'educationQuality.indicators.title': 'Indicators',
      'educationQuality.indicators.totalLabel': 'Total indicators',
      'educationQuality.indicators.updated': 'Indicator updated',
      'educationQuality.myData.subtitle': 'Your submitted, approved and rejected data',
      'educationQuality.myData.title': 'My data',
      'educationQuality.nav.announcements': 'Announcements',
      'educationQuality.nav.indicators': 'Indicators',
      'educationQuality.nav.myData': 'My data',
      'educationQuality.nav.reportDepartment': 'Departments',
      'educationQuality.nav.reportFaculty': 'Faculties',
      'educationQuality.nav.reportTeacher': 'Teachers',
      'educationQuality.nav.reports': 'Reports',
      'educationQuality.nav.submit': 'Submit data',
      'educationQuality.nav.teacherAnnouncements': 'Announcements',
      'educationQuality.nav.verification': 'Verification',
      'educationQuality.pagination.rowsPerPage': 'Rows per page:',
      'educationQuality.pagination.total': 'Total: {{count}}',
      'educationQuality.pagination.totalNamed': '{{name}}: {{count}}',
      'educationQuality.reports.active': 'Active',
      'educationQuality.reports.activeFrom': 'Activation date',
      'educationQuality.reports.allEmploymentTypes': 'All types',
      'educationQuality.reports.avgScore': 'Average score',
      'educationQuality.reports.belowThreshold': 'Below 25 points',
      'educationQuality.reports.countItems': '{{count}}',
      'educationQuality.reports.dateReached': 'date reached',
      'educationQuality.reports.departmentChartTitle': 'Department ranking (average score)',
      'educationQuality.reports.departmentDesc': 'National rating scores by department',
      'educationQuality.reports.departmentTitle': 'Department report',
      'educationQuality.reports.departments': 'Departments',
      'educationQuality.reports.deptCount': '{{count}} departments',
      'educationQuality.reports.downloadFiles': 'Download files',
      'educationQuality.reports.employmentAsosiy': 'Primary',
      'educationQuality.reports.employmentOrindosh': 'Concurrent',
      'educationQuality.reports.employmentType': 'Employment type',
      'educationQuality.reports.exportDepartmentFile': 'Report-departments',
      'educationQuality.reports.exportFacultyFile': 'Report-faculties',
      'educationQuality.reports.exportTeacherFile': 'Report-teachers',
      'educationQuality.reports.faculties': 'Faculties',
      'educationQuality.reports.facultyChartTitle': 'Faculty ranking (average score)',
      'educationQuality.reports.facultyDesc': 'National rating scores by faculty',
      'educationQuality.reports.facultyTitle': 'Faculty report',
      'educationQuality.reports.inactive': 'Inactive',
      'educationQuality.reports.indicators': 'Indicators',
      'educationQuality.reports.noExportData': 'No data to export',
      'educationQuality.reports.noFiles': 'No uploaded files found',
      'educationQuality.reports.pickDate': 'Select date',
      'educationQuality.reports.rank': 'Rank',
      'educationQuality.reports.redTag': '{{count}} · {{share}}%',
      'educationQuality.reports.scoreValue': '{{score}} pts',
      'educationQuality.reports.searchTeacher': 'Search by full name',
      'educationQuality.reports.teacherDesc': 'National rating scores by academic staff',
      'educationQuality.reports.teacherTitle': 'Teacher report',
      'educationQuality.reports.teachers': 'Teachers',
      'educationQuality.reports.totalDepartments': 'Total departments',
      'educationQuality.reports.totalFaculties': 'Total faculties',
      'educationQuality.reports.totalScore': 'Total score',
      'educationQuality.reports.totalTeachers': 'Total teachers',
      'educationQuality.semester.placeholder': 'Select semester',
      'educationQuality.semester.s1': 'Semester 1',
      'educationQuality.semester.s2': 'Semester 2',
      'educationQuality.status.approved': 'Approved',
      'educationQuality.status.new': 'New',
      'educationQuality.status.pending': 'Under review',
      'educationQuality.status.rejected': 'Rejected',
      'educationQuality.submit.authorsCount': 'Number of authors',
      'educationQuality.submit.authorsTooltip': 'The score is divided by the number of authors',
      'educationQuality.submit.dateUnset': 'not set',
      'educationQuality.submit.pickHint': 'Select an indicator on the left to submit data',
      'educationQuality.submit.points': '{{count}} points',
      'educationQuality.submit.restricted': 'Your submissions are restricted; active from: {{date}}',
      'educationQuality.submit.send': 'Submit',
      'educationQuality.submit.subtitle': 'Select an indicator and submit the required data',
      'educationQuality.submit.success': 'Data submitted. The score will be assigned after review.',
      'educationQuality.submit.title': 'Submit data',
      'educationQuality.submit.yearPlaceholder': 'Select an academic year',
      'educationQuality.teacherAnnouncements.dateFrom': 'From',
      'educationQuality.teacherAnnouncements.dateTo': 'To',
      'educationQuality.teacherAnnouncements.empty': 'No announcements yet',
      'educationQuality.teacherAnnouncements.emptyFiltered': 'No announcements match the filters',
      'educationQuality.teacherAnnouncements.searchPlaceholder': 'Search by title or text',
      'educationQuality.teacherAnnouncements.subtitle': 'Announcements from the Education Quality Assurance Office',
      'educationQuality.teacherAnnouncements.title': 'Announcements',
      'educationQuality.teacherDetail.active': 'Active',
      'educationQuality.teacherDetail.activeFrom': 'Active from: {{date}}',
      'educationQuality.teacherDetail.inactive': 'Inactive',
      'educationQuality.teacherDetail.notFound': 'Teacher not found',
      'educationQuality.verification.approve': 'Approve',
      'educationQuality.verification.approveScoreLabel': 'Score on approval:',
      'educationQuality.verification.approveSuccess': 'Submission approved and score awarded',
      'educationQuality.verification.approveTitle': 'Approve this submission?',
      'educationQuality.verification.empty': 'No data found',
      'educationQuality.verification.emptyPending': 'Nothing awaiting review',
      'educationQuality.verification.exportEmpty': 'No data to export',
      'educationQuality.verification.filterTitle': 'Filters',
      'educationQuality.verification.reasonPlaceholder': 'For example: the uploaded file does not meet the requirements...',
      'educationQuality.verification.reject': 'Reject',
      'educationQuality.verification.rejectHint': 'Describe the reason for rejection in detail. The teacher will see it.',
      'educationQuality.verification.rejectSuccess': 'Submission rejected',
      'educationQuality.verification.rejectTitle': 'Reject submission',
      'educationQuality.verification.searchPlaceholder': 'Search by name',
      'educationQuality.verification.submittedByLabel': 'Submitted by:',
      'educationQuality.verification.subtitle': 'Review, approve and archive data submitted by faculty members',
      'educationQuality.verification.title': 'Verification',
      'menuGroup.educationQuality': 'Education quality',
    },
  },

  permissions: [
    { key: 'eqIndicator:read', description: 'View indicators' },
    { key: 'eqIndicator:create', description: 'Create indicator' },
    { key: 'eqIndicator:update', description: 'Update indicator' },
    { key: 'eqIndicator:delete', description: 'Delete indicator' },
    { key: 'eqSubmission:read', description: 'View all submissions (QA)' },
    { key: 'eqSubmission:create', description: 'Submit data (teacher)' },
    { key: 'eqSubmission:readOwn', description: 'View own submissions' },
    { key: 'eqSubmission:review', description: 'Approve/reject submissions' },
    { key: 'eqAnnouncement:read', description: 'Manage announcements (QA)' },
    { key: 'eqAnnouncement:readOwn', description: 'View announcements (teacher)' },
    { key: 'eqAnnouncement:create', description: 'Create announcement' },
    { key: 'eqAnnouncement:delete', description: 'Delete announcement' },
    { key: 'eqReport:read', description: 'View reports' },
  ],
});
