import { lazy, type ComponentType, type ReactNode } from 'react';
import { Navigate } from 'react-router-dom';
import {
  SettingOutlined,
  TeamOutlined,
  ApartmentOutlined,
  FileSearchOutlined,
  BankOutlined,
  ReadOutlined,
  IdcardOutlined,
  DeploymentUnitOutlined,
  CalendarOutlined,
  TrophyOutlined,
  FormOutlined,
  TranslationOutlined,
  FieldTimeOutlined,
  ClusterOutlined,
  PartitionOutlined,
  ExperimentOutlined,
  SolutionOutlined,
  BranchesOutlined,
  ScheduleOutlined,
  ProjectOutlined,
  BookOutlined,
  CheckSquareOutlined,
} from '@ant-design/icons';
import { defineModule } from '@/shared/lib/module';

interface RefEntity {
  slug: string;
  section: string;
  navKey: string;
  icon: ReactNode;
  order: number;
  list: ComponentType;
  routePermission?: string;
}

const REFERENCE_ENTITIES: RefEntity[] = [
  { slug: 'faculties',       section: 'faculty',               navKey: 'admin.nav.faculties',       icon: <BankOutlined />,           order: 32, list: lazy(() => import('./faculties/pages/faculties-list-page')) },
  { slug: 'courses',         section: 'course',                navKey: 'admin.nav.courses',         icon: <ReadOutlined />,           order: 33, list: lazy(() => import('./courses/pages/courses-list-page')) },
  { slug: 'positions',       section: 'position',              navKey: 'admin.nav.positions',       icon: <IdcardOutlined />,         order: 34, list: lazy(() => import('./positions/pages/positions-list-page')) },
  { slug: 'specializations', section: 'specialization',        navKey: 'admin.nav.specializations', icon: <DeploymentUnitOutlined />, order: 35, list: lazy(() => import('./specializations/pages/specializations-list-page')) },
  { slug: 'study-periods',   section: 'studyPeriod',           navKey: 'admin.nav.studyPeriods',    icon: <CalendarOutlined />,       order: 36, list: lazy(() => import('./study-periods/pages/study-periods-list-page')) },
  { slug: 'academic-levels', section: 'academicLevel',         navKey: 'admin.nav.academicLevels',  icon: <TrophyOutlined />,         order: 37, list: lazy(() => import('./academic-levels/pages/academic-levels-list-page')) },
  { slug: 'education-forms', section: 'educationForm',         navKey: 'admin.nav.educationForms',  icon: <FormOutlined />,           order: 38, list: lazy(() => import('./education-forms/pages/education-forms-list-page')) },
  { slug: 'reading-forms',   section: 'readingForm',           navKey: 'admin.nav.readingForms',    icon: <BookOutlined />,           order: 38.5, list: lazy(() => import('./reading-forms/pages/reading-forms-list-page')) },
  { slug: 'assessment-types',section: 'assessmentType',        navKey: 'admin.nav.assessmentTypes', icon: <CheckSquareOutlined />,    order: 38.7, list: lazy(() => import('./assessment-types/pages/assessment-types-list-page')) },
  { slug: 'languages',       section: 'languageOfInstruction', navKey: 'admin.nav.languages',       icon: <TranslationOutlined />,    order: 39, list: lazy(() => import('./languages/pages/languages-list-page')) },
  { slug: 'auditorium-hours',section: 'auditoriumHour',        navKey: 'admin.nav.auditoriumHours', icon: <FieldTimeOutlined />,      order: 40, list: lazy(() => import('./auditorium-hours/pages/auditorium-hours-list-page')) },
  { slug: 'academic-years',  section: 'academicYear',          navKey: 'admin.nav.academicYears',   icon: <ScheduleOutlined />,       order: 48, list: lazy(() => import('./academic-years/pages/academic-years-list-page')) },
  { slug: 'education-activity-types', section: 'educationActivityType', navKey: 'admin.nav.educationActivityTypes', icon: <ProjectOutlined />, order: 49, list: lazy(() => import('./education-activity-types/pages/education-activity-types-list-page')) },
  { slug: 'departments',     section: 'department',            navKey: 'admin.nav.departments',     icon: <ClusterOutlined />,        order: 41, list: lazy(() => import('./departments/pages/departments-list-page')) },
  { slug: 'divisions',       section: 'division',              navKey: 'admin.nav.divisions',       icon: <PartitionOutlined />,      order: 42, list: lazy(() => import('./divisions/pages/divisions-list-page')) },
  { slug: 'sciences',        section: 'science',               navKey: 'admin.nav.sciences',        icon: <ExperimentOutlined />,     order: 43, list: lazy(() => import('./sciences/pages/sciences-list-page')) },
  { slug: 'science-branches', section: 'scienceBranch',          navKey: 'admin.nav.scienceBranches', icon: <ApartmentOutlined />,      order: 43.5, routePermission: 'scienceBranch:create', list: lazy(() => import('./science-branches/pages/science-branches-list-page')) },
  { slug: 'academic-titles', section: 'academicTitle',         navKey: 'admin.nav.academicTitles',  icon: <SolutionOutlined />,       order: 44, list: lazy(() => import('./academic-titles/pages/academic-titles-list-page')) },
  { slug: 'directions',      section: 'direction',             navKey: 'admin.nav.directions',      icon: <BranchesOutlined />,       order: 46, list: lazy(() => import('./directions/pages/directions-list-page')) },
];

const refRoutes = REFERENCE_ENTITIES.map((e) => ({
  path: e.slug,
  permission: e.routePermission ?? `${e.section}:readAll`,
  element: e.list,
}));

const refMenu = REFERENCE_ENTITIES.map((e) => ({
  titleKey: e.navKey,
  icon: e.icon,
  path: `/admin/${e.slug}`,
  parent: '/admin/structure',
  order: e.order,
  permission: 'direction:create',
}));

const refPermissions = REFERENCE_ENTITIES.flatMap((e) => [
  { key: `${e.section}:create`, description: `Create ${e.section}` },
  { key: `${e.section}:read`, description: `View one ${e.section}` },
  { key: `${e.section}:readAll`, description: `List ${e.section}` },
  { key: `${e.section}:update`, description: `Update ${e.section}` },
  { key: `${e.section}:delete`, description: `Delete ${e.section}` },
]);

const AdminLanding = () => <Navigate to="/admin/users" replace />;

export default defineModule({
  name: 'admin',
  menuGroup: { titleKey: 'menuGroup.admin', order: 10 },
  routes: [
    { index: true, permission: 'user:create', element: AdminLanding },
    { path: 'users', permission: 'user:create', element: lazy(() => import('./users/pages/users-list-page')) },

    { path: 'roles', permission: 'role:create', element: lazy(() => import('./roles/pages/roles-list-page')) },
    { path: 'roles/new', permission: 'role:create', element: lazy(() => import('./roles/pages/roles-form-page')) },
    { path: 'roles/:id/edit', permission: 'role:update', element: lazy(() => import('./roles/pages/roles-form-page')) },

    ...refRoutes,

    { path: 'audit-logs', permission: 'auditLog:readAll', element: lazy(() => import('./audit-logs/pages/audit-logs-list-page')) },
  ],

  menu: [
    { titleKey: 'admin.nav.users', icon: <TeamOutlined />, path: '/admin/users', order: 10, permission: 'user:create' },
    { titleKey: 'admin.nav.roles', icon: <SettingOutlined />, path: '/admin/roles', order: 20, permission: 'role:create' },
    { titleKey: 'admin.nav.auditLogs', icon: <FileSearchOutlined />, path: '/admin/audit-logs', order: 25, permission: 'auditLog:readAll' },

    { titleKey: 'admin.nav.structure', icon: <ApartmentOutlined />, path: '/admin/structure', order: 30, permission: 'direction:create' },
    ...refMenu,
  ],

  i18n: {
    uz: {
      'menuGroup.admin': 'Administratsiya',
      'admin.nav.users': 'Foydalanuvchilar',
      'admin.nav.roles': 'Rollar va vakolatlar',
      'admin.nav.auditLogs': 'Loglar',
      'admin.nav.structure': "Ta’lim tuzilmasi",
      'admin.nav.faculties': 'Fakultetlar',
      'admin.nav.courses': 'Kurslar',
      'admin.nav.positions': 'Lavozimlar',
      'admin.nav.specializations': 'Mutaxassisliklar',
      'admin.nav.studyPeriods': "O'qish davrlari",
      'admin.nav.academicLevels': 'Akademik darajalar',
      'admin.nav.scienceBranches': "Fan tarmoqlari",
      'admin.nav.educationForms': "Ta'lim shakllari",
      'admin.nav.readingForms': "O'qish shakllari",
      'admin.nav.assessmentTypes': 'Yakuniy baholash turlari',
      'admin.nav.languages': "Ta'lim tillari",
      'admin.nav.auditoriumHours': 'Auditoriya normalari',
      'admin.nav.departments': 'Kafedralar',
      'admin.nav.divisions': "Bo'limlar",
      'admin.nav.sciences': 'Fanlar',
      'admin.nav.academicTitles': 'Akademik unvonlar',
      'admin.nav.directions': "Yo'nalishlar",
      'admin.nav.academicYears': "O'quv yillari",
      'admin.nav.educationActivityTypes': "Ta'lim faoliyat turlari",

      'admin.common.actions': 'Amallar',
      'admin.common.index': '#',
      'admin.common.deleteConfirmTitle': "{{title}} — o'chirish",
      'admin.common.deleteConfirmContent': "\"{{title}}\" o'chirilsinmi? Bu amalni qaytarib bo'lmaydi.",
      'admin.common.deleteConfirmOk': "O'chirish",
      'admin.common.cancel': 'Bekor qilish',
      'admin.common.deleted': "O'chirildi",
      'admin.common.updated': 'Yangilandi',
      'admin.common.created': 'Yaratildi',
      'admin.common.required': 'Majburiy',
      'admin.common.save': 'Saqlash',
      'admin.common.create': 'Yaratish',
      'admin.common.dateColumn': "Qo'shilgan sana",

      'admin.user.newButton': 'Yangi foydalanuvchi',
      'admin.user.createTitle': "Foydalanuvchi qo'shish",
      'admin.user.editTitle': 'Foydalanuvchini tahrirlash',
      'admin.user.created': 'Foydalanuvchi yaratildi',
      'admin.user.updated': 'Foydalanuvchi yangilandi',
      'admin.user.deleteConfirmTitle': "Foydalanuvchini o'chirish",
      'admin.user.deleteConfirmContent': '"{{name}}" o\'chirilsinmi?',
      'admin.user.blocked': 'Bloklandi',
      'admin.user.activated': 'Faollashtirildi',
      'admin.user.statusActive': 'Faol',
      'admin.user.statusBlocked': 'Bloklangan',
      'admin.user.searchPlaceholder': "Ism/Familiya bo'yicha qidirish",
      'admin.user.allRoles': 'Barcha rollar',
      'admin.user.allStatuses': 'Barcha holatlar',
      'admin.user.columns.fullName': 'F.I.SH',
      'admin.user.columns.position': 'Lavozim',
      'admin.user.columns.division': "Bo'lim",
      'admin.user.columns.role': 'Rol',
      'admin.user.columns.email': 'E-mail',
      'admin.user.columns.phone': 'Telefon',
      'admin.user.columns.status': 'Status',
      'admin.user.fields.firstName.label': 'Ism',
      'admin.user.fields.firstName.placeholder': 'Alisher',
      'admin.user.fields.lastName.label': 'Familiya',
      'admin.user.fields.lastName.placeholder': 'Karimov',
      'admin.user.fields.middleName.label': 'Sharifi',
      'admin.user.fields.middleName.placeholder': 'Soliyevich',
      'admin.user.fields.passport.label': 'Passport seriya va raqami',
      'admin.user.fields.passportSeria.lenError': 'Aniq 2 ta harf',
      'admin.user.fields.passportNumber.lenError': 'Aniq 7 ta raqam',
      'admin.user.fields.oneIdPin.label': 'JSHSHIR (login uchun ID raqami)',
      'admin.user.fields.oneIdPin.extra': "14 xonali JSHSHIR — foydalanuvchi tizimga shu raqam bilan kiradi",
      'admin.user.fields.oneIdPin.lenError': 'Aniq 14 ta raqam',
      'admin.user.fields.position.label': 'Lavozim',
      'admin.user.fields.position.placeholder': 'Lavozimni tanlang',
      'admin.user.fields.phone.label': 'Telefon',
      'admin.user.fields.employmentType.label': 'Mehnat turi',
      'admin.user.fields.employmentType.placeholder': 'Mehnat turini tanlang',
      'admin.user.fields.employmentType.asosiy': 'Asosiy',
      "admin.user.fields.employmentType.orindosh": "O'rindosh",
      'admin.user.fields.academicTitle.label': 'Ilmiy unvon',
      'admin.user.fields.academicTitle.placeholder': 'Ilmiy unvonni tanlang',
      'admin.user.fields.publications.label': 'Nashrlar soni',
      'admin.user.fields.hIndex.label': 'H-index',
      'admin.user.fields.workingHours.label': 'Ish vaqti',
      'admin.user.fields.workingHours.placeholder': 'Dush–Juma 9:00–17:00',
      'admin.user.fields.office.label': 'Xona',
      'admin.user.fields.office.placeholder': 'A-201',
      'admin.user.fields.email.label': 'Email',
      'admin.user.fields.email.placeholder': 'example@platform.uz',
      'admin.user.fields.email.invalid': "Email noto'g'ri",
      'admin.user.fields.numericPlaceholder': '0',
      'admin.user.fields.division.label': "Bo'lim",
      'admin.user.fields.division.placeholder': "Bo'limni tanlang",
      'admin.user.fields.faculty.label': 'Fakultet',
      'admin.user.fields.faculty.placeholder': 'Fakultetni tanlang',
      'admin.user.fields.department.label': 'Kafedra',
      'admin.user.fields.department.placeholder': 'Kafedrani tanlang',
      'admin.user.fields.department.placeholderDisabled': 'Avval fakultet tanlang',
      'admin.user.fields.role.label': 'Rol',
      'admin.user.fields.role.placeholder': 'Rolni tanlang',
      'admin.user.fields.status.label': 'Status belgilang',

      'admin.role.newButton': 'Yangi rol',
      'admin.role.createTitle': "Yangi rol qo'shish",
      'admin.role.editTitle': 'Rolni tahrirlash',
      'admin.role.created': 'Rol yaratildi',
      'admin.role.updated': 'Rol yangilandi',
      'admin.role.deleted': '"{{title}}" o\'chirildi',
      'admin.role.systemRoleCannotDelete': "Tizim rolini o'chirib bo'lmaydi",
      'admin.role.deleteConfirmTitle': "Rolni o'chirish",
      'admin.role.deleteConfirmContent': '"{{title}}" rolini o\'chirasizmi? Bu rolga biriktirilgan foydalanuvchilar rolsiz qoladi.',
      'admin.role.searchPlaceholder': "Rol nomi bo'yicha qidirish",
      'admin.role.statusActive': 'Faol',
      'admin.role.statusInactive': 'Nofaol',
      'admin.role.permissionsCount': '{{count}} ta',
      'admin.role.back': 'Orqaga',
      'admin.role.basicInfoTitle': "Asosiy ma'lumotlar",
      'admin.role.modulesTitle': 'Modullar',
      'admin.role.modulesNotLoaded': 'Modullar yuklanmadi',
      'admin.role.permissionsTitle': 'Ruxsatlar',
      'admin.role.selectModuleHint': 'Chap tomondan modulni tanlang',
      'admin.role.selectAll': 'Barchasini belgilash',
      'admin.role.columns.title': 'Rol nomi',
      'admin.role.columns.desc': 'Tavsif',
      'admin.role.columns.permissions': 'Ruxsatlar',
      'admin.role.columns.scope': "Ko'rinish",
      'admin.role.columns.active': 'Holat',
      'admin.role.fields.title.label': 'Rol nomi',
      'admin.role.fields.title.placeholder': "Masalan: O'qituvchi, Talaba, Administrator",
      'admin.role.fields.scopeLevel.label': "Ma'lumot ko'rish doirasi",
      'admin.role.fields.scopeLevel.extra': "Bu roldagi foydalanuvchi qaysi hajmdagi ma'lumotni ko'radi. Shubha bo'lsa — eng tor variantni tanlang.",
      'admin.role.scope.self.label': "Faqat o'zi",
      'admin.role.scope.self.hint': "Bu roldagi foydalanuvchi faqat o'ziga tegishli ma'lumotni ko'radi.",
      'admin.role.scope.department.label': "Kafedra / bo'lim",
      'admin.role.scope.department.hint': "Bu roldagi foydalanuvchi o'z kafedrasi/bo'limi doirasidagi ma'lumotni ko'radi.",
      'admin.role.scope.faculty.label': 'Fakultet',
      'admin.role.scope.faculty.hint': "Bu roldagi foydalanuvchi o'z fakulteti doirasidagi ma'lumotni ko'radi.",
      'admin.role.scope.global.label': 'Butun institut',
      'admin.role.scope.global.hint': "Bu roldagi foydalanuvchi butun institut bo'yicha barcha ma'lumotni ko'radi.",
      'admin.role.warning.bannerTitle': "{{count}} ta bo'limda ro'yxat sahifasi ochilmaydi",
      'admin.role.warning.bannerDetail': '{{sections}} — bu bo\'limlarda "{{readLabel}}" belgilangan, lekin "{{readAllLabel}}" yo\'q.',
      'admin.role.warning.missingReadAll': 'Ro\'yxat sahifasi ochilmaydi — "{{action}}" ham kerak',
      'admin.role.warning.missingRead': 'Yozuv kartochkasi ochilmaydi — "{{action}}" ham kerak',
      'admin.role.permissionSections.empty': "Bu modul uchun ruxsatlar yo'q",
      'admin.role.permissionSections.noneTooltip': 'Vakolat berilmagan',
      'admin.role.permissionSections.countTooltip': '{{selected}} ta amal belgilangan (jami {{total}})',
      'admin.role.permissionSections.open': 'Ochish',
      'admin.role.permissionSections.close': 'Yopish',
      'admin.role.moduleList.noneTooltip': '{{title}} — vakolat berilmagan',
      'admin.role.moduleList.countTooltip': '{{title}} — {{selected}} ta ruxsat (jami {{total}})',
      'admin.role.statsCard.title': 'Tanlangan ruxsatlar',
      'admin.role.statsCard.subtitle': 'Jami {{total}} ta ruxsatdan',
      'admin.action.create': 'Yaratish',
      'admin.action.read': "Ko'rish",
      'admin.action.readAll': "Ro'yxat ko'rish",
      'admin.action.readOwn': "O'zinikini ko'rish",
      'admin.action.update': 'Tahrirlash',
      'admin.action.delete': "O'chirish",
      'admin.action.search': 'Qidirish',
      'admin.action.filter': 'Filtrlash',
      'admin.action.idFilter': "ID bo'yicha filtrlash",
      'admin.action.changeStatus': "Holatni o'zgartirish",
      'admin.action.approve': 'Tasdiqlash',
      'admin.action.reject': 'Rad etish',
      'admin.action.verifyDoc': 'Hujjat tasdiqlash',
      'admin.action.sign': 'Imzolash',
      'admin.action.review': "Ko'rib chiqish",
      'admin.action.score': "Ball qo'yish",
      'admin.action.export': 'Eksport',
      'admin.action.import': 'Import',
      'admin.action.assign': 'Biriktirish',
      'admin.action.publish': 'Nashr etish',
      'admin.action.archive': 'Arxivlash',
      'admin.action.dashboard': 'Boshqaruv paneli',
      'admin.action.manageMembers': "A'zolarni boshqarish",
      'admin.action.submitWork': 'Ish topshirish',
      'admin.action.notifications': 'Bildirishnomalar',
      'admin.action.grantAny': 'Barcha vakolatlarni belgilash',

      'admin.auditLog.pageTitle': 'Loglar (audit jurnali)',
      'admin.auditLog.searchPlaceholder': "Foydalanuvchi, yo'l yoki amal bo'yicha qidirish",
      'admin.auditLog.allModules': "Barcha bo'limlar",
      'admin.auditLog.allMethods': 'Barcha amallar',
      'admin.auditLog.onlyMutations': 'Faqat o‘zgarishlar',
      'admin.auditLog.excelButton': 'Excel',
      'admin.auditLog.pdfButton': 'PDF',
      'admin.auditLog.pdfDownloaded': 'PDF yuklandi',
      'admin.auditLog.excelDownloaded': 'Excel yuklandi',
      'admin.auditLog.denied': 'ruxsat berilmadi',
      'admin.auditLog.columns.createdAt': 'Sana va vaqt',
      'admin.auditLog.columns.userName': 'Foydalanuvchi',
      'admin.auditLog.columns.action': 'Nima qildi',
      'admin.auditLog.columns.method': 'Turi',
      'admin.auditLog.columns.files': 'Fayl',
      'admin.auditLog.columns.ip': 'IP',
      'admin.auditLog.columns.statusCode': 'Natija',
      'admin.auditLog.columns.responseTime': 'Vaqt',
      'admin.auditLog.sentence': '"{{section}}" — {{verb}}',
      'admin.auditLog.section.system': 'Tizim',
      'admin.auditLog.section.eri': 'ERI',
      'admin.auditLog.section.files': 'Fayllar',
      'admin.auditLog.section.unknown': 'Nomaʼlum bo‘lim',
      'admin.auditLog.action.login': 'tizimga kirdi',
      'admin.auditLog.action.logout': 'tizimdan chiqdi',
      'admin.auditLog.action.refresh': 'sessiyasini yangiladi',
      'admin.auditLog.action.viewProfile': 'o‘z profilini ko‘rdi',
      'admin.auditLog.action.eriAttach': 'elektron imzo biriktirdi',
      'admin.auditLog.action.eriDetach': 'elektron imzoni uzdi',
      'admin.auditLog.action.fileFallbackName': 'fayl',
      'admin.auditLog.action.fileDownload': '"{{name}}" faylini yuklab oldi',
      'admin.auditLog.verb.approve': 'tasdiqladi',
      'admin.auditLog.verb.reject': 'rad etdi',
      'admin.auditLog.verb.return': 'qaytardi',
      'admin.auditLog.verb.sign': 'imzoladi',
      'admin.auditLog.verb.submit': 'tasdiqlashga yubordi',
      'admin.auditLog.verb.generate': 'shakllantirdi',
      'admin.auditLog.verb.export': 'eksport qildi',
      'admin.auditLog.verb.pdf': 'PDF yuklab oldi',
      'admin.auditLog.verb.complete': 'bajarildi deb belgiladi',
      'admin.auditLog.verb.reopen': 'qayta ochdi',
      'admin.auditLog.verb.accept': 'qabul qildi',
      'admin.auditLog.verb.changeStatus': 'holatini o‘zgartirdi',
      'admin.auditLog.verb.create': 'yangi yozuv qo‘shdi',
      'admin.auditLog.verb.update': 'o‘zgartirdi',
      'admin.auditLog.verb.delete': 'o‘chirdi',
      'admin.auditLog.verb.viewOne': 'yozuvini ko‘rdi',
      'admin.auditLog.verb.viewList': 'ro‘yxatini ko‘rdi',

      'admin.academicLevel.listTitle': 'Akademik darajalar',
      'admin.academicLevel.newButton': 'Yangi daraja',
      'admin.academicLevel.createTitle': "Akademik daraja qo'shish",
      'admin.academicLevel.editTitle': 'Akademik darajani tahrirlash',
      'admin.academicLevel.searchPlaceholder': "Daraja nomi bo'yicha qidirish",
      'admin.academicLevel.columns.title': 'Akademik daraja',
      'admin.academicLevel.fields.title.label': 'Akademik daraja nomi',
      'admin.academicLevel.fields.title.placeholder': 'Masalan: Bakalavr',
      'admin.academicLevel.fields.desc.label': 'Tavsif',
      'admin.academicLevel.fields.desc.placeholder': 'Qisqa tavsif',

      'admin.academicTitle.listTitle': 'Akademik unvonlar',
      'admin.academicTitle.newButton': 'Yangi unvon',
      'admin.academicTitle.createTitle': "Akademik unvon qo'shish",
      'admin.academicTitle.editTitle': 'Akademik unvonni tahrirlash',
      'admin.academicTitle.searchPlaceholder': "Unvon nomi bo'yicha qidirish",
      'admin.academicTitle.columns.title': 'Unvon nomi',
      'admin.academicTitle.columns.position': 'Lavozim',
      'admin.academicTitle.columns.rateTime': 'Stavka vaqti',
      'admin.academicTitle.fields.title.label': 'Unvon nomi',
      'admin.academicTitle.fields.title.placeholder': 'Masalan: Dotsent',
      'admin.academicTitle.fields.position.label': 'Lavozim',
      'admin.academicTitle.fields.position.placeholder': 'Lavozimni tanlang',
      'admin.academicTitle.fields.rateTime.label': 'Stavka vaqti',
      'admin.academicTitle.fields.rateTime.placeholder': 'Masalan: 1',

      'admin.academicYear.listTitle': "O'quv yillari",
      'admin.academicYear.newButton': "Yangi o'quv yili",
      'admin.academicYear.createTitle': "O'quv yili qo'shish",
      'admin.academicYear.editTitle': "O'quv yilini tahrirlash",
      'admin.academicYear.searchPlaceholder': "Yil bo'yicha qidirish",
      'admin.academicYear.columns.title': "O'quv yili",
      'admin.academicYear.fields.title.label': "O'quv yili",
      'admin.academicYear.fields.title.placeholder': 'Masalan: 2024/2025',

      'admin.assessmentType.listTitle': 'Yakuniy baholash turlari',
      'admin.assessmentType.newButton': 'Yangi baholash turi',
      'admin.assessmentType.createTitle': "Yakuniy baholash turi qo'shish",
      'admin.assessmentType.editTitle': 'Yakuniy baholash turini tahrirlash',
      'admin.assessmentType.searchPlaceholder': "Baholash turi nomi bo'yicha qidirish",
      'admin.assessmentType.columns.title': 'Yakuniy baholash turi',
      'admin.assessmentType.fields.title.label': 'Yakuniy baholash turi nomi',
      'admin.assessmentType.fields.title.placeholder': "Masalan: Imtihon (og'zaki)",
      'admin.assessmentType.fields.desc.label': 'Tavsif',
      'admin.assessmentType.fields.desc.placeholder': 'Qisqa tavsif',

      'admin.auditoriumHour.listTitle': 'Auditoriya soat normalari',
      'admin.auditoriumHour.newButton': 'Yangi norma',
      'admin.auditoriumHour.createTitle': "Auditoriya soat normasi qo'shish",
      'admin.auditoriumHour.editTitle': 'Auditoriya soat normasini tahrirlash',
      'admin.auditoriumHour.searchPlaceholder': 'Qidirish',
      'admin.auditoriumHour.columns.auditoriumHour': 'Soat normasi (1.0 stavka)',
      'admin.auditoriumHour.columns.allowedStakes': 'Ruxsat etilgan stavkalar',
      'admin.auditoriumHour.fields.auditoriumHour.label': 'Soat normasi (1.0 stavka uchun)',
      'admin.auditoriumHour.fields.auditoriumHour.placeholder': 'Masalan: 700',
      'admin.auditoriumHour.fields.allowedStakes.label': 'Ruxsat etilgan stavkalar',
      'admin.auditoriumHour.fields.allowedStakes.placeholder': '0.25, 0.5, 0.75, 1',

      'admin.course.listTitle': 'Kurslar',
      'admin.course.newButton': 'Yangi kurs',
      'admin.course.createTitle': "Kurs qo'shish",
      'admin.course.editTitle': 'Kursni tahrirlash',
      'admin.course.searchPlaceholder': "Kurs nomi bo'yicha qidirish",
      'admin.course.columns.title': 'Kurs nomi',
      'admin.course.fields.title.label': 'Kurs nomi',
      'admin.course.fields.title.placeholder': 'Masalan: 1-kurs',
      'admin.course.fields.desc.label': 'Tavsif',
      'admin.course.fields.desc.placeholder': 'Qisqa tavsif',

      'admin.department.listTitle': 'Kafedralar',
      'admin.department.newButton': 'Yangi kafedra',
      'admin.department.createTitle': "Kafedra qo'shish",
      'admin.department.editTitle': 'Kafedrani tahrirlash',
      'admin.department.searchPlaceholder': "Kafedra nomi bo'yicha qidirish",
      'admin.department.columns.title': 'Kafedra nomi',
      'admin.department.columns.faculty': 'Fakultet',
      'admin.department.fields.title.label': 'Kafedra nomi',
      'admin.department.fields.title.placeholder': 'Kafedra nomini kiriting',
      'admin.department.fields.faculty.label': 'Fakultet',
      'admin.department.fields.faculty.placeholder': 'Fakultetni tanlang',
      'admin.department.fields.desc.label': 'Tavsif',
      'admin.department.fields.desc.placeholder': 'Qisqa tavsif',

      'admin.direction.listTitle': "Yo'nalishlar",
      'admin.direction.newButton': "Yangi yo'nalish",
      'admin.direction.createTitle': "Yo'nalish qo'shish",
      'admin.direction.editTitle': "Yo'nalishni tahrirlash",
      'admin.direction.searchPlaceholder': "Yo'nalish nomi bo'yicha qidirish",
      'admin.direction.columns.directionCode': 'Kodi',
      'admin.direction.columns.title': "Yo'nalish nomi",
      'admin.direction.columns.faculty': 'Fakultet',
      'admin.direction.columns.level': 'Daraja',
      'admin.direction.columns.practiceDepartment': 'Amaliyot kafedrasi',
      'admin.direction.fields.title.label': "Yo'nalish nomi",
      'admin.direction.fields.title.placeholder': "Yo'nalish nomini kiriting",
      'admin.direction.fields.directionCode.label': "Yo'nalish kodi",
      'admin.direction.fields.directionCode.placeholder': 'Masalan: 60910200',
      'admin.direction.fields.knowledgeArea.label': 'Bilim sohasi',
      'admin.direction.fields.knowledgeArea.placeholder': "Masalan: 900000 – Sog'liqni saqlash va ijtimoiy ta'minot",
      'admin.direction.fields.educationArea.label': "Ta'lim sohasi",
      'admin.direction.fields.educationArea.placeholder': "Masalan: 910000 – Sog'liqni saqlash",
      'admin.direction.fields.level.label': 'Akademik daraja',
      'admin.direction.fields.level.placeholder': 'Darajani tanlang',
      'admin.direction.fields.faculty.label': 'Fakultet',
      'admin.direction.fields.faculty.placeholder': 'Fakultetni tanlang',
      'admin.direction.fields.educationForm.label': "Ta'lim shakli",
      'admin.direction.fields.educationForm.placeholder': 'Shaklni tanlang',
      'admin.direction.fields.specialization.label': 'Mutaxassislik',
      'admin.direction.fields.specialization.placeholder': 'Mutaxassislikni tanlang',
      'admin.direction.fields.studyPeriod.label': "O'qish muddati (yil)",
      'admin.direction.fields.studyPeriod.placeholder': 'Masalan: 4',
      'admin.direction.fields.teachingLanguages.label': "Ta'lim tillari",
      'admin.direction.fields.teachingLanguages.placeholder': 'Tillarni tanlang',
      'admin.direction.fields.international.label': "Xalqaro yo'nalish",
      'admin.direction.fields.practiceDepartment.label': "Amaliyotga mas'ul kafedra",
      'admin.direction.fields.practiceDepartment.placeholder': 'Kafedrani tanlang',
      'admin.direction.fields.desc.label': 'Tavsif',
      'admin.direction.fields.desc.placeholder': 'Qisqa tavsif',

      'admin.division.listTitle': "Bo'limlar",
      'admin.division.newButton': "Yangi bo'lim",
      'admin.division.createTitle': "Bo'lim qo'shish",
      'admin.division.editTitle': "Bo'limni tahrirlash",
      'admin.division.searchPlaceholder': "Bo'lim nomi bo'yicha qidirish",
      'admin.division.columns.title': "Bo'lim nomi",
      'admin.division.columns.faculty': 'Fakultet',
      'admin.division.columns.department': 'Kafedra',
      'admin.division.fields.title.label': "Bo'lim nomi",
      'admin.division.fields.title.placeholder': "Bo'lim nomini kiriting",
      'admin.division.fields.faculty.label': 'Fakultet',
      'admin.division.fields.faculty.placeholder': 'Fakultetni tanlang',
      'admin.division.fields.department.label': 'Kafedra',
      'admin.division.fields.department.placeholder': 'Kafedrani tanlang',
      'admin.division.fields.desc.label': 'Tavsif',
      'admin.division.fields.desc.placeholder': 'Qisqa tavsif',

      'admin.educationActivityType.listTitle': "Ta'lim faoliyat turlari",
      'admin.educationActivityType.newButton': 'Yangi faoliyat turi',
      'admin.educationActivityType.createTitle': "Ta'lim faoliyat turi qo'shish",
      'admin.educationActivityType.editTitle': "Ta'lim faoliyat turini tahrirlash",
      'admin.educationActivityType.searchPlaceholder': "Nom bo'yicha qidirish",
      'admin.educationActivityType.columns.title': 'Faoliyat turi',
      'admin.educationActivityType.columns.flow': "Oqim ko'rsatkichi",
      'admin.educationActivityType.fields.title.label': 'Faoliyat turi nomi',
      'admin.educationActivityType.fields.title.placeholder': 'Masalan: Maʼruza',
      'admin.educationActivityType.fields.desc.label': 'Tavsif',
      'admin.educationActivityType.fields.desc.placeholder': 'Qisqa tavsif',
      'admin.educationActivityType.fields.flow.label': 'Oqim sifatida ishlashi mumkin',

      'admin.educationForm.listTitle': "Ta'lim shakllari",
      'admin.educationForm.newButton': 'Yangi shakl',
      'admin.educationForm.createTitle': "Ta'lim shakli qo'shish",
      'admin.educationForm.editTitle': "Ta'lim shaklini tahrirlash",
      'admin.educationForm.searchPlaceholder': "Shakl nomi bo'yicha qidirish",
      'admin.educationForm.columns.title': "Ta'lim shakli",
      'admin.educationForm.columns.isInternational': 'Xalqaro',
      'admin.educationForm.fields.title.label': "Ta'lim shakli nomi",
      'admin.educationForm.fields.title.placeholder': 'Masalan: Kunduzgi',
      'admin.educationForm.fields.desc.label': 'Tavsif',
      'admin.educationForm.fields.desc.placeholder': 'Qisqa tavsif',
      'admin.educationForm.fields.isInternational.label': 'Xalqaro talabalar uchun',

      'admin.faculty.listTitle': 'Fakultetlar',
      'admin.faculty.newButton': 'Yangi fakultet',
      'admin.faculty.createTitle': "Fakultet qo'shish",
      'admin.faculty.editTitle': 'Fakultetni tahrirlash',
      'admin.faculty.searchPlaceholder': "Fakultet nomi bo'yicha qidirish",
      'admin.faculty.columns.title': 'Fakultet nomi',
      'admin.faculty.fields.title.label': 'Fakultet nomi',
      'admin.faculty.fields.title.placeholder': 'Fakultet nomini kiriting',
      'admin.faculty.fields.desc.label': 'Tavsif',
      'admin.faculty.fields.desc.placeholder': 'Qisqa tavsif',

      'admin.language.listTitle': "Ta'lim tillari",
      'admin.language.newButton': 'Yangi til',
      'admin.language.createTitle': "Ta'lim tili qo'shish",
      'admin.language.editTitle': "Ta'lim tilini tahrirlash",
      'admin.language.searchPlaceholder': "Til nomi bo'yicha qidirish",
      'admin.language.columns.title': "Ta'lim tili",
      'admin.language.fields.title.label': 'Til nomi',
      'admin.language.fields.title.placeholder': "Masalan: O'zbek tili",

      'admin.position.listTitle': 'Lavozimlar',
      'admin.position.newButton': 'Yangi lavozim',
      'admin.position.createTitle': "Lavozim qo'shish",
      'admin.position.editTitle': 'Lavozimni tahrirlash',
      'admin.position.searchPlaceholder': "Lavozim nomi bo'yicha qidirish",
      'admin.position.columns.title': 'Lavozim nomi',
      'admin.position.fields.title.label': 'Lavozim nomi',
      'admin.position.fields.title.placeholder': 'Masalan: Dotsent',
      'admin.position.fields.desc.label': 'Tavsif',
      'admin.position.fields.desc.placeholder': 'Qisqa tavsif',

      'admin.readingForm.listTitle': "O'qish shakllari",
      'admin.readingForm.newButton': 'Yangi shakl',
      'admin.readingForm.createTitle': "O'qish shakli qo'shish",
      'admin.readingForm.editTitle': "O'qish shaklini tahrirlash",
      'admin.readingForm.searchPlaceholder': "Shakl nomi bo'yicha qidirish",
      'admin.readingForm.columns.title': "O'qish shakli",
      'admin.readingForm.fields.title.label': "O'qish shakli nomi",
      'admin.readingForm.fields.title.placeholder': 'Masalan: Kunduzgi',
      'admin.readingForm.fields.desc.label': 'Tavsif',
      'admin.readingForm.fields.desc.placeholder': 'Qisqa tavsif',

      'admin.scienceBranch.listTitle': 'Fan tarmoqlari',
      'admin.scienceBranch.newButton': 'Yangi tarmoq',
      'admin.scienceBranch.createTitle': "Fan tarmog'i qo'shish",
      'admin.scienceBranch.editTitle': "Fan tarmog'ini tahrirlash",
      'admin.scienceBranch.searchPlaceholder': "Shifr yoki nom bo'yicha qidirish",
      'admin.scienceBranch.columns.code': 'Shifr',
      'admin.scienceBranch.columns.title': "Fan tarmog'i",
      'admin.scienceBranch.fields.code.label': 'Shifr',
      'admin.scienceBranch.fields.code.placeholder': '14.00.00',
      'admin.scienceBranch.fields.title.label': "Fan tarmog'i nomi",
      'admin.scienceBranch.fields.title.placeholder': 'Masalan: Biologiya fanlari',
      'admin.scienceBranch.fields.desc.label': 'Tavsif',
      'admin.scienceBranch.fields.desc.placeholder': 'Qisqa tavsif',

      'admin.science.listTitle': 'Fanlar',
      'admin.science.newButton': 'Yangi fan',
      'admin.science.createTitle': "Fan qo'shish",
      'admin.science.editTitle': 'Fanni tahrirlash',
      'admin.science.searchPlaceholder': "Fan nomi bo'yicha qidirish",
      'admin.science.columns.scienceCode': 'Fan kodi',
      'admin.science.columns.title': 'Fan nomi',
      'admin.science.columns.department': 'Kafedra',
      'admin.science.fields.title.label': 'Fan nomi',
      'admin.science.fields.title.placeholder': 'Fan nomini kiriting',
      'admin.science.fields.scienceCode.label': 'Fan kodi',
      'admin.science.fields.scienceCode.placeholder': 'Masalan: MAT101',
      'admin.science.fields.department.label': 'Kafedra',
      'admin.science.fields.department.placeholder': 'Kafedrani tanlang',
      'admin.science.fields.desc.label': 'Tavsif',
      'admin.science.fields.desc.placeholder': 'Qisqa tavsif',
      'admin.science.columns.isElective': 'Tanlov fani',
      'admin.science.fields.isElective.label': 'Tanlov fani',

      'admin.specialization.listTitle': 'Mutaxassisliklar',
      'admin.specialization.newButton': 'Yangi mutaxassislik',
      'admin.specialization.createTitle': "Mutaxassislik qo'shish",
      'admin.specialization.editTitle': 'Mutaxassislikni tahrirlash',
      'admin.specialization.searchPlaceholder': "Mutaxassislik nomi bo'yicha qidirish",
      'admin.specialization.columns.title': 'Mutaxassislik nomi',
      'admin.specialization.fields.title.label': 'Mutaxassislik nomi',
      'admin.specialization.fields.title.placeholder': 'Mutaxassislik nomini kiriting',
      'admin.specialization.fields.desc.label': 'Tavsif',
      'admin.specialization.fields.desc.placeholder': 'Qisqa tavsif',

      'admin.studyPeriod.listTitle': "O'qish davrlari",
      'admin.studyPeriod.newButton': 'Yangi davr',
      'admin.studyPeriod.createTitle': "O'qish davri qo'shish",
      'admin.studyPeriod.editTitle': "O'qish davrini tahrirlash",
      'admin.studyPeriod.searchPlaceholder': "Davr nomi bo'yicha qidirish",
      'admin.studyPeriod.columns.title': "O'qish davri",
      'admin.studyPeriod.fields.title.label': "O'qish davri nomi",
      'admin.studyPeriod.fields.title.placeholder': 'Masalan: 1-semestr',
      'admin.studyPeriod.fields.desc.label': 'Tavsif',
      'admin.studyPeriod.fields.desc.placeholder': 'Qisqa tavsif',
    },
    ru: {
      'menuGroup.admin': 'Администрация',
      'admin.nav.users': 'Пользователи',
      'admin.nav.roles': 'Роли и полномочия',
      'admin.nav.auditLogs': 'Журнал действий',
      'admin.nav.structure': 'Структура образования',
      'admin.nav.faculties': 'Факультеты',
      'admin.nav.courses': 'Курсы',
      'admin.nav.positions': 'Должности',
      'admin.nav.specializations': 'Специализации',
      'admin.nav.studyPeriods': 'Учебные периоды',
      'admin.nav.academicLevels': 'Академические уровни',
      'admin.nav.scienceBranches': 'Отрасли науки',
      'admin.nav.educationForms': 'Формы обучения',
      'admin.nav.readingForms': 'Формы чтения',
      'admin.nav.assessmentTypes': 'Виды итогового оценивания',
      'admin.nav.languages': 'Языки обучения',
      'admin.nav.auditoriumHours': 'Аудиторные нормы',
      'admin.nav.departments': 'Кафедры',
      'admin.nav.divisions': 'Отделы',
      'admin.nav.sciences': 'Предметы',
      'admin.nav.academicTitles': 'Учёные звания',
      'admin.nav.directions': 'Направления',
      'admin.nav.academicYears': 'Учебные годы',
      'admin.nav.educationActivityTypes': 'Типы учебной деятельности',

      'admin.common.actions': 'Действия',
      'admin.common.index': '#',
      'admin.common.deleteConfirmTitle': 'Удаление — {{title}}',
      'admin.common.deleteConfirmContent': 'Удалить "{{title}}"? Это действие невозможно отменить.',
      'admin.common.deleteConfirmOk': 'Удалить',
      'admin.common.cancel': 'Отмена',
      'admin.common.deleted': 'Удалено',
      'admin.common.updated': 'Обновлено',
      'admin.common.created': 'Создано',
      'admin.common.required': 'Обязательно',
      'admin.common.save': 'Сохранить',
      'admin.common.create': 'Создать',
      'admin.common.dateColumn': 'Дата добавления',

      'admin.user.newButton': 'Новый пользователь',
      'admin.user.createTitle': 'Добавить пользователя',
      'admin.user.editTitle': 'Редактировать пользователя',
      'admin.user.created': 'Пользователь создан',
      'admin.user.updated': 'Пользователь обновлён',
      'admin.user.deleteConfirmTitle': 'Удаление пользователя',
      'admin.user.deleteConfirmContent': 'Удалить "{{name}}"?',
      'admin.user.blocked': 'Блокирован',
      'admin.user.activated': 'Активирован',
      'admin.user.statusActive': 'Активен',
      'admin.user.statusBlocked': 'Блокирован',
      'admin.user.searchPlaceholder': 'Поиск по имени/фамилии',
      'admin.user.allRoles': 'Все роли',
      'admin.user.allStatuses': 'Все статусы',
      'admin.user.columns.fullName': 'Ф.И.О.',
      'admin.user.columns.position': 'Должность',
      'admin.user.columns.division': 'Отдел',
      'admin.user.columns.role': 'Роль',
      'admin.user.columns.email': 'E-mail',
      'admin.user.columns.phone': 'Телефон',
      'admin.user.columns.status': 'Статус',
      'admin.user.fields.firstName.label': 'Имя',
      'admin.user.fields.firstName.placeholder': 'Алишер',
      'admin.user.fields.lastName.label': 'Фамилия',
      'admin.user.fields.lastName.placeholder': 'Каримов',
      'admin.user.fields.middleName.label': 'Отчество',
      'admin.user.fields.middleName.placeholder': 'Солиевич',
      'admin.user.fields.passport.label': 'Серия и номер паспорта',
      'admin.user.fields.passportSeria.lenError': 'Ровно 2 буквы',
      'admin.user.fields.passportNumber.lenError': 'Ровно 7 цифр',
      'admin.user.fields.oneIdPin.label': 'ПИНФЛ (ID для входа)',
      'admin.user.fields.oneIdPin.extra': '14-значный ПИНФЛ — пользователь входит в систему этим номером',
      'admin.user.fields.oneIdPin.lenError': 'Ровно 14 цифр',
      'admin.user.fields.position.label': 'Должность',
      'admin.user.fields.position.placeholder': 'Выберите должность',
      'admin.user.fields.phone.label': 'Телефон',
      'admin.user.fields.employmentType.label': 'Тип занятости',
      'admin.user.fields.employmentType.placeholder': 'Выберите тип занятости',
      'admin.user.fields.employmentType.asosiy': 'Основной',
      "admin.user.fields.employmentType.orindosh": "Совместитель",
      'admin.user.fields.academicTitle.label': 'Учёное звание',
      'admin.user.fields.academicTitle.placeholder': 'Выберите учёное звание',
      'admin.user.fields.publications.label': 'Количество публикаций',
      'admin.user.fields.hIndex.label': 'H-индекс',
      'admin.user.fields.workingHours.label': 'Рабочее время',
      'admin.user.fields.workingHours.placeholder': 'Пн–Пт 9:00–17:00',
      'admin.user.fields.office.label': 'Кабинет',
      'admin.user.fields.office.placeholder': 'A-201',
      'admin.user.fields.email.label': 'Email',
      'admin.user.fields.email.placeholder': 'example@platform.uz',
      'admin.user.fields.email.invalid': 'Неверный email',
      'admin.user.fields.numericPlaceholder': '0',
      'admin.user.fields.division.label': 'Отдел',
      'admin.user.fields.division.placeholder': 'Выберите отдел',
      'admin.user.fields.faculty.label': 'Факультет',
      'admin.user.fields.faculty.placeholder': 'Выберите факультет',
      'admin.user.fields.department.label': 'Кафедра',
      'admin.user.fields.department.placeholder': 'Выберите кафедру',
      'admin.user.fields.department.placeholderDisabled': 'Сначала выберите факультет',
      'admin.user.fields.role.label': 'Роль',
      'admin.user.fields.role.placeholder': 'Выберите роль',
      'admin.user.fields.status.label': 'Укажите статус',

      'admin.role.newButton': 'Новая роль',
      'admin.role.createTitle': 'Добавить новую роль',
      'admin.role.editTitle': 'Редактировать роль',
      'admin.role.created': 'Роль создана',
      'admin.role.updated': 'Роль обновлена',
      'admin.role.deleted': '"{{title}}" удалена',
      'admin.role.systemRoleCannotDelete': 'Системную роль невозможно удалить',
      'admin.role.deleteConfirmTitle': 'Удаление роли',
      'admin.role.deleteConfirmContent': 'Удалить роль "{{title}}"? Пользователи с этой ролью останутся без роли.',
      'admin.role.searchPlaceholder': 'Поиск по названию роли',
      'admin.role.statusActive': 'Активна',
      'admin.role.statusInactive': 'Неактивна',
      'admin.role.permissionsCount': '{{count}} шт.',
      'admin.role.back': 'Назад',
      'admin.role.basicInfoTitle': 'Основная информация',
      'admin.role.modulesTitle': 'Модули',
      'admin.role.modulesNotLoaded': 'Модули не загружены',
      'admin.role.permissionsTitle': 'Права',
      'admin.role.selectModuleHint': 'Выберите модуль слева',
      'admin.role.selectAll': 'Выбрать всё',
      'admin.role.columns.title': 'Название роли',
      'admin.role.columns.desc': 'Описание',
      'admin.role.columns.permissions': 'Права',
      'admin.role.columns.scope': 'Область видимости',
      'admin.role.columns.active': 'Статус',
      'admin.role.fields.title.label': 'Название роли',
      'admin.role.fields.title.placeholder': 'Например: Преподаватель, Студент, Администратор',
      'admin.role.fields.scopeLevel.label': 'Область видимости данных',
      'admin.role.fields.scopeLevel.extra': 'Какой объём данных видит пользователь с этой ролью. Если не уверены — выберите самый узкий вариант.',
      'admin.role.scope.self.label': 'Только себя',
      'admin.role.scope.self.hint': 'Пользователь с этой ролью видит только свои данные.',
      'admin.role.scope.department.label': 'Кафедра / отдел',
      'admin.role.scope.department.hint': 'Пользователь с этой ролью видит данные в рамках своей кафедры/отдела.',
      'admin.role.scope.faculty.label': 'Факультет',
      'admin.role.scope.faculty.hint': 'Пользователь с этой ролью видит данные в рамках своего факультета.',
      'admin.role.scope.global.label': 'Весь институт',
      'admin.role.scope.global.hint': 'Пользователь с этой ролью видит все данные по институту.',
      'admin.role.warning.bannerTitle': 'В {{count}} разделах страница списка не открывается',
      'admin.role.warning.bannerDetail': '{{sections}} — в этих разделах отмечено "{{readLabel}}", но нет "{{readAllLabel}}".',
      'admin.role.warning.missingReadAll': 'Страница списка не откроется — нужен также "{{action}}"',
      'admin.role.warning.missingRead': 'Карточка записи не откроется — нужен также "{{action}}"',
      'admin.role.permissionSections.empty': 'Для этого модуля нет прав',
      'admin.role.permissionSections.noneTooltip': 'Права не назначены',
      'admin.role.permissionSections.countTooltip': 'Назначено {{selected}} действий (всего {{total}})',
      'admin.role.permissionSections.open': 'Открыть',
      'admin.role.permissionSections.close': 'Закрыть',
      'admin.role.moduleList.noneTooltip': '{{title}} — права не назначены',
      'admin.role.moduleList.countTooltip': '{{title}} — {{selected}} прав (всего {{total}})',
      'admin.role.statsCard.title': 'Выбранные права',
      'admin.role.statsCard.subtitle': 'Всего из {{total}} прав',
      'admin.action.create': 'Создать',
      'admin.action.read': 'Просмотр',
      'admin.action.readAll': 'Список',
      'admin.action.readOwn': 'Просмотр своих',
      'admin.action.update': 'Изменить',
      'admin.action.delete': 'Удалить',
      'admin.action.search': 'Поиск',
      'admin.action.filter': 'Фильтрация',
      'admin.action.idFilter': 'Фильтр по ID',
      'admin.action.changeStatus': 'Изменить статус',
      'admin.action.approve': 'Одобрить',
      'admin.action.reject': 'Отклонить',
      'admin.action.verifyDoc': 'Подтвердить документ',
      'admin.action.sign': 'Подписать',
      'admin.action.review': 'Рассмотреть',
      'admin.action.score': 'Оценить',
      'admin.action.export': 'Экспорт',
      'admin.action.import': 'Импорт',
      'admin.action.assign': 'Назначить',
      'admin.action.publish': 'Опубликовать',
      'admin.action.archive': 'Архивировать',
      'admin.action.dashboard': 'Панель управления',
      'admin.action.manageMembers': 'Управление членами',
      'admin.action.submitWork': 'Подать работу',
      'admin.action.notifications': 'Уведомления',
      'admin.action.grantAny': 'Назначать любые права',

      'admin.auditLog.pageTitle': 'Журнал действий',
      'admin.auditLog.searchPlaceholder': 'Поиск по пользователю, пути или действию',
      'admin.auditLog.allModules': 'Все разделы',
      'admin.auditLog.allMethods': 'Все действия',
      'admin.auditLog.onlyMutations': 'Только изменения',
      'admin.auditLog.excelButton': 'Excel',
      'admin.auditLog.pdfButton': 'PDF',
      'admin.auditLog.pdfDownloaded': 'PDF скачан',
      'admin.auditLog.excelDownloaded': 'Excel скачан',
      'admin.auditLog.denied': 'доступ запрещён',
      'admin.auditLog.columns.createdAt': 'Дата и время',
      'admin.auditLog.columns.userName': 'Пользователь',
      'admin.auditLog.columns.action': 'Что сделал',
      'admin.auditLog.columns.method': 'Тип',
      'admin.auditLog.columns.files': 'Файл',
      'admin.auditLog.columns.ip': 'IP',
      'admin.auditLog.columns.statusCode': 'Результат',
      'admin.auditLog.columns.responseTime': 'Время',
      'admin.auditLog.sentence': '"{{section}}" — {{verb}}',
      'admin.auditLog.section.system': 'Система',
      'admin.auditLog.section.eri': 'ЭЦП',
      'admin.auditLog.section.files': 'Файлы',
      'admin.auditLog.section.unknown': 'Неизвестный раздел',
      'admin.auditLog.action.login': 'вошёл в систему',
      'admin.auditLog.action.logout': 'вышел из системы',
      'admin.auditLog.action.refresh': 'обновил сессию',
      'admin.auditLog.action.viewProfile': 'просмотрел свой профиль',
      'admin.auditLog.action.eriAttach': 'подключил электронную подпись',
      'admin.auditLog.action.eriDetach': 'отключил электронную подпись',
      'admin.auditLog.action.fileFallbackName': 'файл',
      'admin.auditLog.action.fileDownload': 'скачал файл "{{name}}"',
      'admin.auditLog.verb.approve': 'одобрил',
      'admin.auditLog.verb.reject': 'отклонил',
      'admin.auditLog.verb.return': 'вернул',
      'admin.auditLog.verb.sign': 'подписал',
      'admin.auditLog.verb.submit': 'отправил на подтверждение',
      'admin.auditLog.verb.generate': 'сформировал',
      'admin.auditLog.verb.export': 'экспортировал',
      'admin.auditLog.verb.pdf': 'скачал PDF',
      'admin.auditLog.verb.complete': 'отметил как завершённое',
      'admin.auditLog.verb.reopen': 'заново открыл',
      'admin.auditLog.verb.accept': 'принял',
      'admin.auditLog.verb.changeStatus': 'изменил статус',
      'admin.auditLog.verb.create': 'добавил новую запись',
      'admin.auditLog.verb.update': 'изменил',
      'admin.auditLog.verb.delete': 'удалил',
      'admin.auditLog.verb.viewOne': 'просмотрел запись',
      'admin.auditLog.verb.viewList': 'просмотрел список',

      'admin.academicLevel.listTitle': 'Академические степени',
      'admin.academicLevel.newButton': 'Новая степень',
      'admin.academicLevel.createTitle': 'Добавить академическую степень',
      'admin.academicLevel.editTitle': 'Редактировать академическую степень',
      'admin.academicLevel.searchPlaceholder': 'Поиск по названию степени',
      'admin.academicLevel.columns.title': 'Академическая степень',
      'admin.academicLevel.fields.title.label': 'Название академической степени',
      'admin.academicLevel.fields.title.placeholder': 'Например: Бакалавр',
      'admin.academicLevel.fields.desc.label': 'Описание',
      'admin.academicLevel.fields.desc.placeholder': 'Краткое описание',

      'admin.academicTitle.listTitle': 'Академические звания',
      'admin.academicTitle.newButton': 'Новое звание',
      'admin.academicTitle.createTitle': 'Добавить академическое звание',
      'admin.academicTitle.editTitle': 'Редактировать академическое звание',
      'admin.academicTitle.searchPlaceholder': 'Поиск по названию звания',
      'admin.academicTitle.columns.title': 'Название звания',
      'admin.academicTitle.columns.position': 'Должность',
      'admin.academicTitle.columns.rateTime': 'Коэффициент ставки',
      'admin.academicTitle.fields.title.label': 'Название звания',
      'admin.academicTitle.fields.title.placeholder': 'Например: Доцент',
      'admin.academicTitle.fields.position.label': 'Должность',
      'admin.academicTitle.fields.position.placeholder': 'Выберите должность',
      'admin.academicTitle.fields.rateTime.label': 'Коэффициент ставки',
      'admin.academicTitle.fields.rateTime.placeholder': 'Например: 1',

      'admin.academicYear.listTitle': 'Учебные годы',
      'admin.academicYear.newButton': 'Новый учебный год',
      'admin.academicYear.createTitle': 'Добавить учебный год',
      'admin.academicYear.editTitle': 'Редактировать учебный год',
      'admin.academicYear.searchPlaceholder': 'Поиск по году',
      'admin.academicYear.columns.title': 'Учебный год',
      'admin.academicYear.fields.title.label': 'Учебный год',
      'admin.academicYear.fields.title.placeholder': 'Например: 2024/2025',

      'admin.assessmentType.listTitle': 'Виды итогового оценивания',
      'admin.assessmentType.newButton': 'Новый вид оценивания',
      'admin.assessmentType.createTitle': 'Добавить вид итогового оценивания',
      'admin.assessmentType.editTitle': 'Редактировать вид итогового оценивания',
      'admin.assessmentType.searchPlaceholder': 'Поиск по названию вида оценивания',
      'admin.assessmentType.columns.title': 'Вид итогового оценивания',
      'admin.assessmentType.fields.title.label': 'Название вида итогового оценивания',
      'admin.assessmentType.fields.title.placeholder': 'Например: Экзамен (устный)',
      'admin.assessmentType.fields.desc.label': 'Описание',
      'admin.assessmentType.fields.desc.placeholder': 'Краткое описание',

      'admin.auditoriumHour.listTitle': 'Аудиторные нормы часов',
      'admin.auditoriumHour.newButton': 'Новая норма',
      'admin.auditoriumHour.createTitle': 'Добавить аудиторную норму часов',
      'admin.auditoriumHour.editTitle': 'Редактировать аудиторную норму часов',
      'admin.auditoriumHour.searchPlaceholder': 'Поиск',
      'admin.auditoriumHour.columns.auditoriumHour': 'Норма часов (ставка 1.0)',
      'admin.auditoriumHour.columns.allowedStakes': 'Разрешённые ставки',
      'admin.auditoriumHour.fields.auditoriumHour.label': 'Норма часов (для ставки 1.0)',
      'admin.auditoriumHour.fields.auditoriumHour.placeholder': 'Например: 700',
      'admin.auditoriumHour.fields.allowedStakes.label': 'Разрешённые ставки',
      'admin.auditoriumHour.fields.allowedStakes.placeholder': '0.25, 0.5, 0.75, 1',

      'admin.course.listTitle': 'Курсы',
      'admin.course.newButton': 'Новый курс',
      'admin.course.createTitle': 'Добавить курс',
      'admin.course.editTitle': 'Редактировать курс',
      'admin.course.searchPlaceholder': 'Поиск по названию курса',
      'admin.course.columns.title': 'Название курса',
      'admin.course.fields.title.label': 'Название курса',
      'admin.course.fields.title.placeholder': 'Например: 1 курс',
      'admin.course.fields.desc.label': 'Описание',
      'admin.course.fields.desc.placeholder': 'Краткое описание',

      'admin.department.listTitle': 'Кафедры',
      'admin.department.newButton': 'Новая кафедра',
      'admin.department.createTitle': 'Добавить кафедру',
      'admin.department.editTitle': 'Редактировать кафедру',
      'admin.department.searchPlaceholder': 'Поиск по названию кафедры',
      'admin.department.columns.title': 'Название кафедры',
      'admin.department.columns.faculty': 'Факультет',
      'admin.department.fields.title.label': 'Название кафедры',
      'admin.department.fields.title.placeholder': 'Введите название кафедры',
      'admin.department.fields.faculty.label': 'Факультет',
      'admin.department.fields.faculty.placeholder': 'Выберите факультет',
      'admin.department.fields.desc.label': 'Описание',
      'admin.department.fields.desc.placeholder': 'Краткое описание',

      'admin.direction.listTitle': 'Направления',
      'admin.direction.newButton': 'Новое направление',
      'admin.direction.createTitle': 'Добавить направление',
      'admin.direction.editTitle': 'Редактировать направление',
      'admin.direction.searchPlaceholder': 'Поиск по названию направления',
      'admin.direction.columns.directionCode': 'Код',
      'admin.direction.columns.title': 'Название направления',
      'admin.direction.columns.faculty': 'Факультет',
      'admin.direction.columns.level': 'Степень',
      'admin.direction.columns.practiceDepartment': 'Кафедра практики',
      'admin.direction.fields.title.label': 'Название направления',
      'admin.direction.fields.title.placeholder': 'Введите название направления',
      'admin.direction.fields.directionCode.label': 'Код направления',
      'admin.direction.fields.directionCode.placeholder': 'Например: 60910200',
      'admin.direction.fields.knowledgeArea.label': 'Область знаний',
      'admin.direction.fields.knowledgeArea.placeholder': "Например: 900000 – Sog'liqni saqlash va ijtimoiy ta'minot",
      'admin.direction.fields.educationArea.label': 'Область образования',
      'admin.direction.fields.educationArea.placeholder': "Например: 910000 – Sog'liqni saqlash",
      'admin.direction.fields.level.label': 'Академическая степень',
      'admin.direction.fields.level.placeholder': 'Выберите степень',
      'admin.direction.fields.faculty.label': 'Факультет',
      'admin.direction.fields.faculty.placeholder': 'Выберите факультет',
      'admin.direction.fields.educationForm.label': 'Форма обучения',
      'admin.direction.fields.educationForm.placeholder': 'Выберите форму',
      'admin.direction.fields.specialization.label': 'Специализация',
      'admin.direction.fields.specialization.placeholder': 'Выберите специализацию',
      'admin.direction.fields.studyPeriod.label': 'Срок обучения (лет)',
      'admin.direction.fields.studyPeriod.placeholder': 'Например: 4',
      'admin.direction.fields.teachingLanguages.label': 'Языки обучения',
      'admin.direction.fields.teachingLanguages.placeholder': 'Выберите языки',
      'admin.direction.fields.international.label': 'Международное направление',
      'admin.direction.fields.practiceDepartment.label': 'Кафедра, ответственная за практику',
      'admin.direction.fields.practiceDepartment.placeholder': 'Выберите кафедру',
      'admin.direction.fields.desc.label': 'Описание',
      'admin.direction.fields.desc.placeholder': 'Краткое описание',

      'admin.division.listTitle': 'Отделы',
      'admin.division.newButton': 'Новый отдел',
      'admin.division.createTitle': 'Добавить отдел',
      'admin.division.editTitle': 'Редактировать отдел',
      'admin.division.searchPlaceholder': 'Поиск по названию отдела',
      'admin.division.columns.title': 'Название отдела',
      'admin.division.columns.faculty': 'Факультет',
      'admin.division.columns.department': 'Кафедра',
      'admin.division.fields.title.label': 'Название отдела',
      'admin.division.fields.title.placeholder': 'Введите название отдела',
      'admin.division.fields.faculty.label': 'Факультет',
      'admin.division.fields.faculty.placeholder': 'Выберите факультет',
      'admin.division.fields.department.label': 'Кафедра',
      'admin.division.fields.department.placeholder': 'Выберите кафедру',
      'admin.division.fields.desc.label': 'Описание',
      'admin.division.fields.desc.placeholder': 'Краткое описание',

      'admin.educationActivityType.listTitle': 'Типы учебной деятельности',
      'admin.educationActivityType.newButton': 'Новый тип деятельности',
      'admin.educationActivityType.createTitle': 'Добавить тип учебной деятельности',
      'admin.educationActivityType.editTitle': 'Редактировать тип учебной деятельности',
      'admin.educationActivityType.searchPlaceholder': 'Поиск по названию',
      'admin.educationActivityType.columns.title': 'Тип деятельности',
      'admin.educationActivityType.columns.flow': 'Признак потока',
      'admin.educationActivityType.fields.title.label': 'Название типа деятельности',
      'admin.educationActivityType.fields.title.placeholder': 'Например: Лекция',
      'admin.educationActivityType.fields.desc.label': 'Описание',
      'admin.educationActivityType.fields.desc.placeholder': 'Краткое описание',
      'admin.educationActivityType.fields.flow.label': 'Может работать как поток',

      'admin.educationForm.listTitle': 'Формы обучения',
      'admin.educationForm.newButton': 'Новая форма',
      'admin.educationForm.createTitle': 'Добавить форму обучения',
      'admin.educationForm.editTitle': 'Редактировать форму обучения',
      'admin.educationForm.searchPlaceholder': 'Поиск по названию формы',
      'admin.educationForm.columns.title': 'Форма обучения',
      'admin.educationForm.columns.isInternational': 'Международная',
      'admin.educationForm.fields.title.label': 'Название формы обучения',
      'admin.educationForm.fields.title.placeholder': 'Например: Очная',
      'admin.educationForm.fields.desc.label': 'Описание',
      'admin.educationForm.fields.desc.placeholder': 'Краткое описание',
      'admin.educationForm.fields.isInternational.label': 'Для иностранных студентов',

      'admin.faculty.listTitle': 'Факультеты',
      'admin.faculty.newButton': 'Новый факультет',
      'admin.faculty.createTitle': 'Добавить факультет',
      'admin.faculty.editTitle': 'Редактировать факультет',
      'admin.faculty.searchPlaceholder': 'Поиск по названию факультета',
      'admin.faculty.columns.title': 'Название факультета',
      'admin.faculty.fields.title.label': 'Название факультета',
      'admin.faculty.fields.title.placeholder': 'Введите название факультета',
      'admin.faculty.fields.desc.label': 'Описание',
      'admin.faculty.fields.desc.placeholder': 'Краткое описание',

      'admin.language.listTitle': 'Языки обучения',
      'admin.language.newButton': 'Новый язык',
      'admin.language.createTitle': 'Добавить язык обучения',
      'admin.language.editTitle': 'Редактировать язык обучения',
      'admin.language.searchPlaceholder': 'Поиск по названию языка',
      'admin.language.columns.title': 'Язык обучения',
      'admin.language.fields.title.label': 'Название языка',
      'admin.language.fields.title.placeholder': 'Например: Узбекский язык',

      'admin.position.listTitle': 'Должности',
      'admin.position.newButton': 'Новая должность',
      'admin.position.createTitle': 'Добавить должность',
      'admin.position.editTitle': 'Редактировать должность',
      'admin.position.searchPlaceholder': 'Поиск по названию должности',
      'admin.position.columns.title': 'Название должности',
      'admin.position.fields.title.label': 'Название должности',
      'admin.position.fields.title.placeholder': 'Например: Доцент',
      'admin.position.fields.desc.label': 'Описание',
      'admin.position.fields.desc.placeholder': 'Краткое описание',

      'admin.readingForm.listTitle': 'Формы чтения',
      'admin.readingForm.newButton': 'Новая форма',
      'admin.readingForm.createTitle': 'Добавить форму чтения',
      'admin.readingForm.editTitle': 'Редактировать форму чтения',
      'admin.readingForm.searchPlaceholder': 'Поиск по названию формы',
      'admin.readingForm.columns.title': 'Форма чтения',
      'admin.readingForm.fields.title.label': 'Название формы чтения',
      'admin.readingForm.fields.title.placeholder': 'Например: Очная',
      'admin.readingForm.fields.desc.label': 'Описание',
      'admin.readingForm.fields.desc.placeholder': 'Краткое описание',

      'admin.scienceBranch.listTitle': 'Отрасли науки',
      'admin.scienceBranch.newButton': 'Новая отрасль',
      'admin.scienceBranch.createTitle': 'Добавить отрасль науки',
      'admin.scienceBranch.editTitle': 'Редактировать отрасль науки',
      'admin.scienceBranch.searchPlaceholder': 'Поиск по шифру или названию',
      'admin.scienceBranch.columns.code': 'Шифр',
      'admin.scienceBranch.columns.title': 'Отрасль науки',
      'admin.scienceBranch.fields.code.label': 'Шифр',
      'admin.scienceBranch.fields.code.placeholder': '14.00.00',
      'admin.scienceBranch.fields.title.label': 'Название отрасли науки',
      'admin.scienceBranch.fields.title.placeholder': 'Например: Биологические науки',
      'admin.scienceBranch.fields.desc.label': 'Описание',
      'admin.scienceBranch.fields.desc.placeholder': 'Краткое описание',

      'admin.science.listTitle': 'Предметы',
      'admin.science.newButton': 'Новый предмет',
      'admin.science.createTitle': 'Добавить предмет',
      'admin.science.editTitle': 'Редактировать предмет',
      'admin.science.searchPlaceholder': 'Поиск по названию предмета',
      'admin.science.columns.scienceCode': 'Код предмета',
      'admin.science.columns.title': 'Название предмета',
      'admin.science.columns.department': 'Кафедра',
      'admin.science.fields.title.label': 'Название предмета',
      'admin.science.fields.title.placeholder': 'Введите название предмета',
      'admin.science.fields.scienceCode.label': 'Код предмета',
      'admin.science.fields.scienceCode.placeholder': 'Например: MAT101',
      'admin.science.fields.department.label': 'Кафедра',
      'admin.science.fields.department.placeholder': 'Выберите кафедру',
      'admin.science.fields.desc.label': 'Описание',
      'admin.science.fields.desc.placeholder': 'Краткое описание',
      'admin.science.columns.isElective': 'Предмет по выбору',
      'admin.science.fields.isElective.label': 'Предмет по выбору',

      'admin.specialization.listTitle': 'Специализации',
      'admin.specialization.newButton': 'Новая специализация',
      'admin.specialization.createTitle': 'Добавить специализацию',
      'admin.specialization.editTitle': 'Редактировать специализацию',
      'admin.specialization.searchPlaceholder': 'Поиск по названию специализации',
      'admin.specialization.columns.title': 'Название специализации',
      'admin.specialization.fields.title.label': 'Название специализации',
      'admin.specialization.fields.title.placeholder': 'Введите название специализации',
      'admin.specialization.fields.desc.label': 'Описание',
      'admin.specialization.fields.desc.placeholder': 'Краткое описание',

      'admin.studyPeriod.listTitle': 'Учебные периоды',
      'admin.studyPeriod.newButton': 'Новый период',
      'admin.studyPeriod.createTitle': 'Добавить учебный период',
      'admin.studyPeriod.editTitle': 'Редактировать учебный период',
      'admin.studyPeriod.searchPlaceholder': 'Поиск по названию периода',
      'admin.studyPeriod.columns.title': 'Учебный период',
      'admin.studyPeriod.fields.title.label': 'Название учебного периода',
      'admin.studyPeriod.fields.title.placeholder': 'Например: 1 семестр',
      'admin.studyPeriod.fields.desc.label': 'Описание',
      'admin.studyPeriod.fields.desc.placeholder': 'Краткое описание',
    },
    en: {
      'menuGroup.admin': 'Administration',
      'admin.nav.users': 'Users',
      'admin.nav.roles': 'Roles and authorities',
      'admin.nav.auditLogs': 'Audit log',
      'admin.nav.structure': 'Educational structure',
      'admin.nav.faculties': 'Faculties',
      'admin.nav.courses': 'Courses',
      'admin.nav.positions': 'Positions',
      'admin.nav.specializations': 'Specializations',
      'admin.nav.studyPeriods': 'Study periods',
      'admin.nav.academicLevels': 'Academic levels',
      'admin.nav.scienceBranches': 'Fields of science',
      'admin.nav.educationForms': 'Education forms',
      'admin.nav.readingForms': 'Reading forms',
      'admin.nav.assessmentTypes': 'Final assessment types',
      'admin.nav.languages': 'Languages',
      'admin.nav.auditoriumHours': 'Auditorium norms',
      'admin.nav.departments': 'Chairs',
      'admin.nav.divisions': 'Divisions',
      'admin.nav.sciences': 'Sciences',
      'admin.nav.academicTitles': 'Academic titles',
      'admin.nav.directions': 'Directions',
      'admin.nav.academicYears': 'Academic years',
      'admin.nav.educationActivityTypes': 'Education activity types',

      'admin.common.actions': 'Actions',
      'admin.common.index': '#',
      'admin.common.deleteConfirmTitle': 'Delete {{title}}',
      'admin.common.deleteConfirmContent': 'Delete "{{title}}"? This action cannot be undone.',
      'admin.common.deleteConfirmOk': 'Delete',
      'admin.common.cancel': 'Cancel',
      'admin.common.deleted': 'Deleted',
      'admin.common.updated': 'Updated',
      'admin.common.created': 'Created',
      'admin.common.required': 'Required',
      'admin.common.save': 'Save',
      'admin.common.create': 'Create',
      'admin.common.dateColumn': 'Date added',

      'admin.user.newButton': 'New user',
      'admin.user.createTitle': 'Add user',
      'admin.user.editTitle': 'Edit user',
      'admin.user.created': 'User created',
      'admin.user.updated': 'User updated',
      'admin.user.deleteConfirmTitle': 'Delete user',
      'admin.user.deleteConfirmContent': 'Delete "{{name}}"?',
      'admin.user.blocked': 'Blocked',
      'admin.user.activated': 'Activated',
      'admin.user.statusActive': 'Active',
      'admin.user.statusBlocked': 'Blocked',
      'admin.user.searchPlaceholder': 'Search by first/last name',
      'admin.user.allRoles': 'All roles',
      'admin.user.allStatuses': 'All statuses',
      'admin.user.columns.fullName': 'Full name',
      'admin.user.columns.position': 'Position',
      'admin.user.columns.division': 'Division',
      'admin.user.columns.role': 'Role',
      'admin.user.columns.email': 'E-mail',
      'admin.user.columns.phone': 'Phone',
      'admin.user.columns.status': 'Status',
      'admin.user.fields.firstName.label': 'First name',
      'admin.user.fields.firstName.placeholder': 'Alisher',
      'admin.user.fields.lastName.label': 'Last name',
      'admin.user.fields.lastName.placeholder': 'Karimov',
      'admin.user.fields.middleName.label': 'Middle name',
      'admin.user.fields.middleName.placeholder': 'Soliyevich',
      'admin.user.fields.passport.label': 'Passport series and number',
      'admin.user.fields.passportSeria.lenError': 'Exactly 2 letters',
      'admin.user.fields.passportNumber.lenError': 'Exactly 7 digits',
      'admin.user.fields.oneIdPin.label': 'PINFL (login ID number)',
      'admin.user.fields.oneIdPin.extra': '14-digit PINFL — the user logs in with this number',
      'admin.user.fields.oneIdPin.lenError': 'Exactly 14 digits',
      'admin.user.fields.position.label': 'Position',
      'admin.user.fields.position.placeholder': 'Select a position',
      'admin.user.fields.phone.label': 'Phone',
      'admin.user.fields.employmentType.label': 'Employment type',
      'admin.user.fields.employmentType.placeholder': 'Select employment type',
      'admin.user.fields.employmentType.asosiy': 'Primary',
      "admin.user.fields.employmentType.orindosh": "Concurrent",
      'admin.user.fields.academicTitle.label': 'Academic title',
      'admin.user.fields.academicTitle.placeholder': 'Select an academic title',
      'admin.user.fields.publications.label': 'Number of publications',
      'admin.user.fields.hIndex.label': 'H-index',
      'admin.user.fields.workingHours.label': 'Working hours',
      'admin.user.fields.workingHours.placeholder': 'Mon–Fri 9:00–17:00',
      'admin.user.fields.office.label': 'Office',
      'admin.user.fields.office.placeholder': 'A-201',
      'admin.user.fields.email.label': 'Email',
      'admin.user.fields.email.placeholder': 'example@platform.uz',
      'admin.user.fields.email.invalid': 'Invalid email',
      'admin.user.fields.numericPlaceholder': '0',
      'admin.user.fields.division.label': 'Division',
      'admin.user.fields.division.placeholder': 'Select a division',
      'admin.user.fields.faculty.label': 'Faculty',
      'admin.user.fields.faculty.placeholder': 'Select a faculty',
      'admin.user.fields.department.label': 'Department',
      'admin.user.fields.department.placeholder': 'Select a department',
      'admin.user.fields.department.placeholderDisabled': 'Select a faculty first',
      'admin.user.fields.role.label': 'Role',
      'admin.user.fields.role.placeholder': 'Select a role',
      'admin.user.fields.status.label': 'Set status',

      'admin.role.newButton': 'New role',
      'admin.role.createTitle': 'Add new role',
      'admin.role.editTitle': 'Edit role',
      'admin.role.created': 'Role created',
      'admin.role.updated': 'Role updated',
      'admin.role.deleted': '"{{title}}" deleted',
      'admin.role.systemRoleCannotDelete': 'A system role cannot be deleted',
      'admin.role.deleteConfirmTitle': 'Delete role',
      'admin.role.deleteConfirmContent': 'Delete role "{{title}}"? Users assigned to this role will be left without a role.',
      'admin.role.searchPlaceholder': 'Search by role name',
      'admin.role.statusActive': 'Active',
      'admin.role.statusInactive': 'Inactive',
      'admin.role.permissionsCount': '{{count}}',
      'admin.role.back': 'Back',
      'admin.role.basicInfoTitle': 'Basic information',
      'admin.role.modulesTitle': 'Modules',
      'admin.role.modulesNotLoaded': 'Modules did not load',
      'admin.role.permissionsTitle': 'Permissions',
      'admin.role.selectModuleHint': 'Select a module on the left',
      'admin.role.selectAll': 'Select all',
      'admin.role.columns.title': 'Role name',
      'admin.role.columns.desc': 'Description',
      'admin.role.columns.permissions': 'Permissions',
      'admin.role.columns.scope': 'Scope',
      'admin.role.columns.active': 'Status',
      'admin.role.fields.title.label': 'Role name',
      'admin.role.fields.title.placeholder': 'e.g. Teacher, Student, Administrator',
      'admin.role.fields.scopeLevel.label': 'Data visibility scope',
      'admin.role.fields.scopeLevel.extra': 'Which scope of data a user with this role sees. If unsure — pick the narrowest option.',
      'admin.role.scope.self.label': 'Self only',
      'admin.role.scope.self.hint': 'A user with this role sees only their own data.',
      'admin.role.scope.department.label': 'Department / division',
      'admin.role.scope.department.hint': 'A user with this role sees data within their department/division.',
      'admin.role.scope.faculty.label': 'Faculty',
      'admin.role.scope.faculty.hint': 'A user with this role sees data within their faculty.',
      'admin.role.scope.global.label': 'Entire institute',
      'admin.role.scope.global.hint': 'A user with this role sees all data across the institute.',
      'admin.role.warning.bannerTitle': 'The list page will not open in {{count}} section(s)',
      'admin.role.warning.bannerDetail': '{{sections}} — these sections have "{{readLabel}}" checked, but not "{{readAllLabel}}".',
      'admin.role.warning.missingReadAll': 'The list page will not open — "{{action}}" is also required',
      'admin.role.warning.missingRead': 'The record card will not open — "{{action}}" is also required',
      'admin.role.permissionSections.empty': 'This module has no permissions',
      'admin.role.permissionSections.noneTooltip': 'No permissions granted',
      'admin.role.permissionSections.countTooltip': '{{selected}} actions selected (of {{total}})',
      'admin.role.permissionSections.open': 'Open',
      'admin.role.permissionSections.close': 'Close',
      'admin.role.moduleList.noneTooltip': '{{title}} — no permissions granted',
      'admin.role.moduleList.countTooltip': '{{title}} — {{selected}} permissions (of {{total}})',
      'admin.role.statsCard.title': 'Selected permissions',
      'admin.role.statsCard.subtitle': 'Out of {{total}} total',
      'admin.action.create': 'Create',
      'admin.action.read': 'View',
      'admin.action.readAll': 'List',
      'admin.action.readOwn': 'View own',
      'admin.action.update': 'Edit',
      'admin.action.delete': 'Delete',
      'admin.action.search': 'Search',
      'admin.action.filter': 'Filter',
      'admin.action.idFilter': 'Filter by ID',
      'admin.action.changeStatus': 'Change status',
      'admin.action.approve': 'Approve',
      'admin.action.reject': 'Reject',
      'admin.action.verifyDoc': 'Verify document',
      'admin.action.sign': 'Sign',
      'admin.action.review': 'Review',
      'admin.action.score': 'Score',
      'admin.action.export': 'Export',
      'admin.action.import': 'Import',
      'admin.action.assign': 'Assign',
      'admin.action.publish': 'Publish',
      'admin.action.archive': 'Archive',
      'admin.action.dashboard': 'Dashboard',
      'admin.action.manageMembers': 'Manage members',
      'admin.action.submitWork': 'Submit work',
      'admin.action.notifications': 'Notifications',
      'admin.action.grantAny': 'Grant any permission',

      'admin.auditLog.pageTitle': 'Audit log',
      'admin.auditLog.searchPlaceholder': 'Search by user, path or action',
      'admin.auditLog.allModules': 'All sections',
      'admin.auditLog.allMethods': 'All actions',
      'admin.auditLog.onlyMutations': 'Changes only',
      'admin.auditLog.excelButton': 'Excel',
      'admin.auditLog.pdfButton': 'PDF',
      'admin.auditLog.pdfDownloaded': 'PDF downloaded',
      'admin.auditLog.excelDownloaded': 'Excel downloaded',
      'admin.auditLog.denied': 'access denied',
      'admin.auditLog.columns.createdAt': 'Date and time',
      'admin.auditLog.columns.userName': 'User',
      'admin.auditLog.columns.action': 'Action',
      'admin.auditLog.columns.method': 'Type',
      'admin.auditLog.columns.files': 'File',
      'admin.auditLog.columns.ip': 'IP',
      'admin.auditLog.columns.statusCode': 'Result',
      'admin.auditLog.columns.responseTime': 'Time',
      'admin.auditLog.sentence': '"{{section}}" — {{verb}}',
      'admin.auditLog.section.system': 'System',
      'admin.auditLog.section.eri': 'E-signature',
      'admin.auditLog.section.files': 'Files',
      'admin.auditLog.section.unknown': 'Unknown section',
      'admin.auditLog.action.login': 'logged in',
      'admin.auditLog.action.logout': 'logged out',
      'admin.auditLog.action.refresh': 'refreshed session',
      'admin.auditLog.action.viewProfile': 'viewed own profile',
      'admin.auditLog.action.eriAttach': 'attached an e-signature',
      'admin.auditLog.action.eriDetach': 'detached the e-signature',
      'admin.auditLog.action.fileFallbackName': 'file',
      'admin.auditLog.action.fileDownload': 'downloaded file "{{name}}"',
      'admin.auditLog.verb.approve': 'approved',
      'admin.auditLog.verb.reject': 'rejected',
      'admin.auditLog.verb.return': 'returned',
      'admin.auditLog.verb.sign': 'signed',
      'admin.auditLog.verb.submit': 'submitted for approval',
      'admin.auditLog.verb.generate': 'generated',
      'admin.auditLog.verb.export': 'exported',
      'admin.auditLog.verb.pdf': 'downloaded PDF',
      'admin.auditLog.verb.complete': 'marked as complete',
      'admin.auditLog.verb.reopen': 'reopened',
      'admin.auditLog.verb.accept': 'accepted',
      'admin.auditLog.verb.changeStatus': 'changed status',
      'admin.auditLog.verb.create': 'added a new record',
      'admin.auditLog.verb.update': 'updated',
      'admin.auditLog.verb.delete': 'deleted',
      'admin.auditLog.verb.viewOne': 'viewed a record',
      'admin.auditLog.verb.viewList': 'viewed the list',

      'admin.academicLevel.listTitle': 'Academic levels',
      'admin.academicLevel.newButton': 'New level',
      'admin.academicLevel.createTitle': 'Add academic level',
      'admin.academicLevel.editTitle': 'Edit academic level',
      'admin.academicLevel.searchPlaceholder': 'Search by level name',
      'admin.academicLevel.columns.title': 'Academic level',
      'admin.academicLevel.fields.title.label': 'Academic level name',
      'admin.academicLevel.fields.title.placeholder': 'e.g. Bachelor',
      'admin.academicLevel.fields.desc.label': 'Description',
      'admin.academicLevel.fields.desc.placeholder': 'Short description',

      'admin.academicTitle.listTitle': 'Academic titles',
      'admin.academicTitle.newButton': 'New title',
      'admin.academicTitle.createTitle': 'Add academic title',
      'admin.academicTitle.editTitle': 'Edit academic title',
      'admin.academicTitle.searchPlaceholder': 'Search by title name',
      'admin.academicTitle.columns.title': 'Title name',
      'admin.academicTitle.columns.position': 'Position',
      'admin.academicTitle.columns.rateTime': 'Rate coefficient',
      'admin.academicTitle.fields.title.label': 'Title name',
      'admin.academicTitle.fields.title.placeholder': 'e.g. Associate professor',
      'admin.academicTitle.fields.position.label': 'Position',
      'admin.academicTitle.fields.position.placeholder': 'Select a position',
      'admin.academicTitle.fields.rateTime.label': 'Rate coefficient',
      'admin.academicTitle.fields.rateTime.placeholder': 'e.g. 1',

      'admin.academicYear.listTitle': 'Academic years',
      'admin.academicYear.newButton': 'New academic year',
      'admin.academicYear.createTitle': 'Add academic year',
      'admin.academicYear.editTitle': 'Edit academic year',
      'admin.academicYear.searchPlaceholder': 'Search by year',
      'admin.academicYear.columns.title': 'Academic year',
      'admin.academicYear.fields.title.label': 'Academic year',
      'admin.academicYear.fields.title.placeholder': 'e.g. 2024/2025',

      'admin.assessmentType.listTitle': 'Final assessment types',
      'admin.assessmentType.newButton': 'New assessment type',
      'admin.assessmentType.createTitle': 'Add final assessment type',
      'admin.assessmentType.editTitle': 'Edit final assessment type',
      'admin.assessmentType.searchPlaceholder': 'Search by assessment type name',
      'admin.assessmentType.columns.title': 'Final assessment type',
      'admin.assessmentType.fields.title.label': 'Final assessment type name',
      'admin.assessmentType.fields.title.placeholder': 'e.g. Exam (oral)',
      'admin.assessmentType.fields.desc.label': 'Description',
      'admin.assessmentType.fields.desc.placeholder': 'Short description',

      'admin.auditoriumHour.listTitle': 'Auditorium hour norms',
      'admin.auditoriumHour.newButton': 'New norm',
      'admin.auditoriumHour.createTitle': 'Add auditorium hour norm',
      'admin.auditoriumHour.editTitle': 'Edit auditorium hour norm',
      'admin.auditoriumHour.searchPlaceholder': 'Search',
      'admin.auditoriumHour.columns.auditoriumHour': 'Hour norm (1.0 rate)',
      'admin.auditoriumHour.columns.allowedStakes': 'Allowed rates',
      'admin.auditoriumHour.fields.auditoriumHour.label': 'Hour norm (for 1.0 rate)',
      'admin.auditoriumHour.fields.auditoriumHour.placeholder': 'e.g. 700',
      'admin.auditoriumHour.fields.allowedStakes.label': 'Allowed rates',
      'admin.auditoriumHour.fields.allowedStakes.placeholder': '0.25, 0.5, 0.75, 1',

      'admin.course.listTitle': 'Courses',
      'admin.course.newButton': 'New course',
      'admin.course.createTitle': 'Add course',
      'admin.course.editTitle': 'Edit course',
      'admin.course.searchPlaceholder': 'Search by course name',
      'admin.course.columns.title': 'Course name',
      'admin.course.fields.title.label': 'Course name',
      'admin.course.fields.title.placeholder': 'e.g. Year 1',
      'admin.course.fields.desc.label': 'Description',
      'admin.course.fields.desc.placeholder': 'Short description',

      'admin.department.listTitle': 'Departments',
      'admin.department.newButton': 'New department',
      'admin.department.createTitle': 'Add department',
      'admin.department.editTitle': 'Edit department',
      'admin.department.searchPlaceholder': 'Search by department name',
      'admin.department.columns.title': 'Department name',
      'admin.department.columns.faculty': 'Faculty',
      'admin.department.fields.title.label': 'Department name',
      'admin.department.fields.title.placeholder': 'Enter department name',
      'admin.department.fields.faculty.label': 'Faculty',
      'admin.department.fields.faculty.placeholder': 'Select a faculty',
      'admin.department.fields.desc.label': 'Description',
      'admin.department.fields.desc.placeholder': 'Short description',

      'admin.direction.listTitle': 'Directions',
      'admin.direction.newButton': 'New direction',
      'admin.direction.createTitle': 'Add direction',
      'admin.direction.editTitle': 'Edit direction',
      'admin.direction.searchPlaceholder': 'Search by direction name',
      'admin.direction.columns.directionCode': 'Code',
      'admin.direction.columns.title': 'Direction name',
      'admin.direction.columns.faculty': 'Faculty',
      'admin.direction.columns.level': 'Level',
      'admin.direction.columns.practiceDepartment': 'Practice department',
      'admin.direction.fields.title.label': 'Direction name',
      'admin.direction.fields.title.placeholder': 'Enter direction name',
      'admin.direction.fields.directionCode.label': 'Direction code',
      'admin.direction.fields.directionCode.placeholder': 'e.g. 60910200',
      'admin.direction.fields.knowledgeArea.label': 'Field of knowledge',
      'admin.direction.fields.knowledgeArea.placeholder': "e.g. 900000 – Sog'liqni saqlash va ijtimoiy ta'minot",
      'admin.direction.fields.educationArea.label': 'Field of education',
      'admin.direction.fields.educationArea.placeholder': "e.g. 910000 – Sog'liqni saqlash",
      'admin.direction.fields.level.label': 'Academic level',
      'admin.direction.fields.level.placeholder': 'Select a level',
      'admin.direction.fields.faculty.label': 'Faculty',
      'admin.direction.fields.faculty.placeholder': 'Select a faculty',
      'admin.direction.fields.educationForm.label': 'Education form',
      'admin.direction.fields.educationForm.placeholder': 'Select a form',
      'admin.direction.fields.specialization.label': 'Specialization',
      'admin.direction.fields.specialization.placeholder': 'Select a specialization',
      'admin.direction.fields.studyPeriod.label': 'Study duration (years)',
      'admin.direction.fields.studyPeriod.placeholder': 'e.g. 4',
      'admin.direction.fields.teachingLanguages.label': 'Teaching languages',
      'admin.direction.fields.teachingLanguages.placeholder': 'Select languages',
      'admin.direction.fields.international.label': 'International direction',
      'admin.direction.fields.practiceDepartment.label': 'Department responsible for practice',
      'admin.direction.fields.practiceDepartment.placeholder': 'Select a department',
      'admin.direction.fields.desc.label': 'Description',
      'admin.direction.fields.desc.placeholder': 'Short description',

      'admin.division.listTitle': 'Divisions',
      'admin.division.newButton': 'New division',
      'admin.division.createTitle': 'Add division',
      'admin.division.editTitle': 'Edit division',
      'admin.division.searchPlaceholder': 'Search by division name',
      'admin.division.columns.title': 'Division name',
      'admin.division.columns.faculty': 'Faculty',
      'admin.division.columns.department': 'Department',
      'admin.division.fields.title.label': 'Division name',
      'admin.division.fields.title.placeholder': 'Enter division name',
      'admin.division.fields.faculty.label': 'Faculty',
      'admin.division.fields.faculty.placeholder': 'Select a faculty',
      'admin.division.fields.department.label': 'Department',
      'admin.division.fields.department.placeholder': 'Select a department',
      'admin.division.fields.desc.label': 'Description',
      'admin.division.fields.desc.placeholder': 'Short description',

      'admin.educationActivityType.listTitle': 'Education activity types',
      'admin.educationActivityType.newButton': 'New activity type',
      'admin.educationActivityType.createTitle': 'Add education activity type',
      'admin.educationActivityType.editTitle': 'Edit education activity type',
      'admin.educationActivityType.searchPlaceholder': 'Search by name',
      'admin.educationActivityType.columns.title': 'Activity type',
      'admin.educationActivityType.columns.flow': 'Flow indicator',
      'admin.educationActivityType.fields.title.label': 'Activity type name',
      'admin.educationActivityType.fields.title.placeholder': 'e.g. Lecture',
      'admin.educationActivityType.fields.desc.label': 'Description',
      'admin.educationActivityType.fields.desc.placeholder': 'Short description',
      'admin.educationActivityType.fields.flow.label': 'Can function as a flow',

      'admin.educationForm.listTitle': 'Education forms',
      'admin.educationForm.newButton': 'New form',
      'admin.educationForm.createTitle': 'Add education form',
      'admin.educationForm.editTitle': 'Edit education form',
      'admin.educationForm.searchPlaceholder': 'Search by form name',
      'admin.educationForm.columns.title': 'Education form',
      'admin.educationForm.columns.isInternational': 'International',
      'admin.educationForm.fields.title.label': 'Education form name',
      'admin.educationForm.fields.title.placeholder': 'e.g. Full-time',
      'admin.educationForm.fields.desc.label': 'Description',
      'admin.educationForm.fields.desc.placeholder': 'Short description',
      'admin.educationForm.fields.isInternational.label': 'For international students',

      'admin.faculty.listTitle': 'Faculties',
      'admin.faculty.newButton': 'New faculty',
      'admin.faculty.createTitle': 'Add faculty',
      'admin.faculty.editTitle': 'Edit faculty',
      'admin.faculty.searchPlaceholder': 'Search by faculty name',
      'admin.faculty.columns.title': 'Faculty name',
      'admin.faculty.fields.title.label': 'Faculty name',
      'admin.faculty.fields.title.placeholder': 'Enter faculty name',
      'admin.faculty.fields.desc.label': 'Description',
      'admin.faculty.fields.desc.placeholder': 'Short description',

      'admin.language.listTitle': 'Languages of instruction',
      'admin.language.newButton': 'New language',
      'admin.language.createTitle': 'Add language of instruction',
      'admin.language.editTitle': 'Edit language of instruction',
      'admin.language.searchPlaceholder': 'Search by language name',
      'admin.language.columns.title': 'Language of instruction',
      'admin.language.fields.title.label': 'Language name',
      'admin.language.fields.title.placeholder': 'e.g. Uzbek',

      'admin.position.listTitle': 'Positions',
      'admin.position.newButton': 'New position',
      'admin.position.createTitle': 'Add position',
      'admin.position.editTitle': 'Edit position',
      'admin.position.searchPlaceholder': 'Search by position name',
      'admin.position.columns.title': 'Position name',
      'admin.position.fields.title.label': 'Position name',
      'admin.position.fields.title.placeholder': 'e.g. Associate professor',
      'admin.position.fields.desc.label': 'Description',
      'admin.position.fields.desc.placeholder': 'Short description',

      'admin.readingForm.listTitle': 'Reading forms',
      'admin.readingForm.newButton': 'New form',
      'admin.readingForm.createTitle': 'Add reading form',
      'admin.readingForm.editTitle': 'Edit reading form',
      'admin.readingForm.searchPlaceholder': 'Search by form name',
      'admin.readingForm.columns.title': 'Reading form',
      'admin.readingForm.fields.title.label': 'Reading form name',
      'admin.readingForm.fields.title.placeholder': 'e.g. Full-time',
      'admin.readingForm.fields.desc.label': 'Description',
      'admin.readingForm.fields.desc.placeholder': 'Short description',

      'admin.scienceBranch.listTitle': 'Fields of science',
      'admin.scienceBranch.newButton': 'New field',
      'admin.scienceBranch.createTitle': 'Add field of science',
      'admin.scienceBranch.editTitle': 'Edit field of science',
      'admin.scienceBranch.searchPlaceholder': 'Search by code or name',
      'admin.scienceBranch.columns.code': 'Code',
      'admin.scienceBranch.columns.title': 'Field of science',
      'admin.scienceBranch.fields.code.label': 'Code',
      'admin.scienceBranch.fields.code.placeholder': '14.00.00',
      'admin.scienceBranch.fields.title.label': 'Field of science name',
      'admin.scienceBranch.fields.title.placeholder': 'e.g. Biological sciences',
      'admin.scienceBranch.fields.desc.label': 'Description',
      'admin.scienceBranch.fields.desc.placeholder': 'Short description',

      'admin.science.listTitle': 'Sciences',
      'admin.science.newButton': 'New science',
      'admin.science.createTitle': 'Add science',
      'admin.science.editTitle': 'Edit science',
      'admin.science.searchPlaceholder': 'Search by science name',
      'admin.science.columns.scienceCode': 'Science code',
      'admin.science.columns.title': 'Science name',
      'admin.science.columns.department': 'Department',
      'admin.science.fields.title.label': 'Science name',
      'admin.science.fields.title.placeholder': 'Enter science name',
      'admin.science.fields.scienceCode.label': 'Science code',
      'admin.science.fields.scienceCode.placeholder': 'e.g. MAT101',
      'admin.science.fields.department.label': 'Department',
      'admin.science.fields.department.placeholder': 'Select a department',
      'admin.science.fields.desc.label': 'Description',
      'admin.science.fields.desc.placeholder': 'Short description',
      'admin.science.columns.isElective': 'Elective',
      'admin.science.fields.isElective.label': 'Elective subject',

      'admin.specialization.listTitle': 'Specializations',
      'admin.specialization.newButton': 'New specialization',
      'admin.specialization.createTitle': 'Add specialization',
      'admin.specialization.editTitle': 'Edit specialization',
      'admin.specialization.searchPlaceholder': 'Search by specialization name',
      'admin.specialization.columns.title': 'Specialization name',
      'admin.specialization.fields.title.label': 'Specialization name',
      'admin.specialization.fields.title.placeholder': 'Enter specialization name',
      'admin.specialization.fields.desc.label': 'Description',
      'admin.specialization.fields.desc.placeholder': 'Short description',

      'admin.studyPeriod.listTitle': 'Study periods',
      'admin.studyPeriod.newButton': 'New period',
      'admin.studyPeriod.createTitle': 'Add study period',
      'admin.studyPeriod.editTitle': 'Edit study period',
      'admin.studyPeriod.searchPlaceholder': 'Search by period name',
      'admin.studyPeriod.columns.title': 'Study period',
      'admin.studyPeriod.fields.title.label': 'Study period name',
      'admin.studyPeriod.fields.title.placeholder': 'e.g. Semester 1',
      'admin.studyPeriod.fields.desc.label': 'Description',
      'admin.studyPeriod.fields.desc.placeholder': 'Short description',
    },
  },

  permissions: [
    { key: 'user:create',       description: 'Create users' },
    { key: 'user:read',         description: 'View one user' },
    { key: 'user:readAll',      description: 'List users' },
    { key: 'user:update',       description: 'Update user' },
    { key: 'user:delete',       description: 'Delete user' },
    { key: 'user:changeStatus', description: 'Block/unblock user' },
    { key: 'role:create',       description: 'Create roles' },
    { key: 'role:read',         description: 'View one role' },
    { key: 'role:readAll',      description: 'List roles' },
    { key: 'role:update',       description: 'Update role permissions' },
    { key: 'role:delete',       description: 'Delete role' },
    { key: 'auditLog:read',     description: 'View one audit log entry' },
    { key: 'auditLog:readAll',  description: 'List audit logs' },
    { key: 'auditLog:search',   description: 'Search audit logs' },
    { key: 'auditLog:filter',   description: 'Filter audit logs' },
    { key: 'auditLog:export',   description: 'Export audit logs' },
    ...refPermissions,
  ],
});
