import {
  BellOutlined,
  CheckCircleOutlined,
  CheckSquareOutlined,
  ClockCircleOutlined,
  CloseCircleOutlined,
  FileAddOutlined,
  FileProtectOutlined,
  FileTextOutlined,
  MinusCircleOutlined,
  RedoOutlined,
  SafetyCertificateOutlined,
  SendOutlined,
  SoundOutlined,
  SyncOutlined,
  TrophyOutlined,
  WarningOutlined,
} from '@ant-design/icons';
import { createElement } from 'react';
import type { RendererDescriptor } from './types';

const icon = (Component: typeof BellOutlined) => createElement(Component);

export const COUNCIL_VARIANT_SUFFIX = '__council';

export const COLLIDING_EVENT_TYPES: ReadonlySet<string> = new Set([
  'task_assigned',
  'task_completed',
]);

export const EVENT_REGISTRY: Record<string, RendererDescriptor> = {
  eri_expiring: {
    shape: 'multiline',
    emphasis: 'title',
    tone: 'warning',
    icon: icon(SafetyCertificateOutlined),
    moduleLabelKey: 'notif.mod.system',
    metaFields: [
      { key: 'serialNumber', labelKey: 'notif.meta.serialNumber', fmt: 'text' },
      { key: 'daysLeft', labelKey: 'notif.meta.daysLeft', fmt: 'count' },
    ],
    bodySanitizer: (body) => body.replace(/^(Sertifikat seriya: )undefined$/m, "$1noma'lum"),
  },
  eri_expired: {
    shape: 'multiline',
    emphasis: 'title',
    tone: 'danger',
    icon: icon(SafetyCertificateOutlined),
    moduleLabelKey: 'notif.mod.system',
  },
  sla_overdue: {
    shape: 'multiline',
    emphasis: 'title',
    tone: 'warning',
    icon: icon(ClockCircleOutlined),
    moduleLabelKey: 'notif.mod.system',
    metaFields: [
      { key: 'chainId', labelKey: 'notif.meta.chainId', fmt: 'id' },
      { key: 'daysOverdue', labelKey: 'notif.meta.daysOverdue', fmt: 'count' },
    ],
  },
  sla_escalated: {
    shape: 'multiline',
    emphasis: 'title',
    tone: 'danger',
    icon: icon(WarningOutlined),
    moduleLabelKey: 'notif.mod.system',
    metaFields: [
      { key: 'chainId', labelKey: 'notif.meta.chainId', fmt: 'id' },
      { key: 'originalRole', labelKey: 'notif.meta.originalRole', fmt: 'text' },
    ],
  },

  vacancy_reassigned: {
    shape: 'multiline',
    emphasis: 'title',
    tone: 'info',
    icon: icon(FileAddOutlined),
    moduleLabelKey: 'notif.mod.studyLoad',
    metaFields: [
      { key: 'distributionId', labelKey: 'notif.meta.distributionId', fmt: 'id' },
      { key: 'entryId', labelKey: 'notif.meta.entryId', fmt: 'id' },
      { key: 'previousTeacher', labelKey: 'notif.meta.previousTeacher', fmt: 'id' },
    ],
  },
  recalc_required: {
    shape: 'multiline',
    emphasis: 'title',
    tone: 'warning',
    icon: icon(SyncOutlined),
    moduleLabelKey: 'notif.mod.studyLoad',
    metaFields: [
      { key: 'groupId', labelKey: 'notif.meta.groupId', fmt: 'id' },
      { key: 'oldCount', labelKey: 'notif.meta.oldCount', fmt: 'count' },
      { key: 'newCount', labelKey: 'notif.meta.newCount', fmt: 'count' },
      { key: 'affectedWorkloads', labelKey: 'notif.meta.affectedWorkloads', fmt: 'arrayCount' },
    ],
  },

  residency_attendance_warning: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'warning',
    icon: icon(WarningOutlined),
    moduleLabelKey: 'notif.mod.residency',
    metaFields: [
      {
        key: 'totalUnexcusedHours',
        labelKey: 'notif.meta.totalUnexcusedHours',
        fmt: 'count',
      },
    ],
  },
  residency_attendance_warning_supervisor: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'warning',
    icon: icon(WarningOutlined),
    moduleLabelKey: 'notif.mod.residency',
  },
  residency_expulsion: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'warning',
    icon: icon(CloseCircleOutlined),
    moduleLabelKey: 'notif.mod.residency',
    metaFields: [
      { key: 'residentId', labelKey: 'notif.meta.residentId', fmt: 'id' },
      { key: 'orderId', labelKey: 'notif.meta.orderId', fmt: 'id' },
    ],
  },
  residency_expulsion_draft_office: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'warning',
    icon: icon(FileProtectOutlined),
    moduleLabelKey: 'notif.mod.residency',
    metaFields: [
      { key: 'reminderStage', labelKey: 'notif.meta.reminderStage', fmt: 'count' },
      { key: 'orderId', labelKey: 'notif.meta.orderId', fmt: 'id' },
      { key: 'residentId', labelKey: 'notif.meta.residentId', fmt: 'id' },
    ],
  },
  residency_expulsion_signed: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'danger',
    icon: icon(CloseCircleOutlined),
    moduleLabelKey: 'notif.mod.residency',
    metaFields: [
      { key: 'orderId', labelKey: 'notif.meta.orderId', fmt: 'id' },
      { key: 'residentId', labelKey: 'notif.meta.residentId', fmt: 'id' },
    ],
  },
  residency_expulsion_rejected: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'info',
    icon: icon(FileTextOutlined),
    moduleLabelKey: 'notif.mod.residency',
    metaFields: [
      { key: 'orderId', labelKey: 'notif.meta.orderId', fmt: 'id' },
      { key: 'residentId', labelKey: 'notif.meta.residentId', fmt: 'id' },
    ],
  },
  residency_expulsion_basis_lost_office: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'warning',
    icon: icon(WarningOutlined),
    moduleLabelKey: 'notif.mod.residency',
    metaFields: [
      { key: 'orderId', labelKey: 'notif.meta.orderId', fmt: 'id' },
      { key: 'residentId', labelKey: 'notif.meta.residentId', fmt: 'id' },
    ],
  },
  residency_absence_notice_auto: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'warning',
    icon: icon(FileAddOutlined),
    moduleLabelKey: 'notif.mod.residency',
    metaFields: [
      { key: 'noticeId', labelKey: 'notif.meta.noticeId', fmt: 'id' },
      { key: 'residentId', labelKey: 'notif.meta.residentId', fmt: 'id' },
    ],
  },
  residency_sams_digest: {
    shape: 'multiline',
    emphasis: 'title',
    tone: 'warning',
    icon: icon(SyncOutlined),
    moduleLabelKey: 'notif.mod.residency',
    metaFields: [{ key: 'digestDay', labelKey: 'notif.meta.digestDay', fmt: 'text' }],
  },
  residency_sams_tenants_changed: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'warning',
    icon: icon(WarningOutlined),
    moduleLabelKey: 'notif.mod.residency',
    metaFields: [{ key: 'digestDay', labelKey: 'notif.meta.digestDay', fmt: 'text' }],
  },
  residency_daily_log_reviewed: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'info',
    icon: icon(FileTextOutlined),
    moduleLabelKey: 'notif.mod.residency',
  },
  residency_plan_reviewed: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'info',
    icon: icon(FileTextOutlined),
    moduleLabelKey: 'notif.mod.residency',
    missingReason: true,
  },
  residency_announcement_published: {
    shape: 'single-line',
    emphasis: 'body',
    tone: 'info',
    icon: icon(SoundOutlined),
    moduleLabelKey: 'notif.mod.residency',
  },

  task_assigned: {
    shape: 'single-line',
    emphasis: 'body',
    tone: 'info',
    icon: icon(FileAddOutlined),
    moduleLabelKey: 'notif.mod.task',
    codeKind: 'docNumber',
    metaFields: [{ key: 'taskId', labelKey: 'notif.meta.taskId', fmt: 'id' }],
  },
  task_deadline_changed: {
    shape: 'single-line',
    emphasis: 'body',
    tone: 'warning',
    icon: icon(ClockCircleOutlined),
    moduleLabelKey: 'notif.mod.task',
    codeKind: 'docNumber',
    metaFields: [{ key: 'taskId', labelKey: 'notif.meta.taskId', fmt: 'id' }],
  },
  task_rejected_by_executor: {
    shape: 'single-line',
    emphasis: 'body',
    tone: 'danger',
    icon: icon(CloseCircleOutlined),
    moduleLabelKey: 'notif.mod.task',
    codeKind: 'docNumber',
    metaFields: [{ key: 'taskId', labelKey: 'notif.meta.taskId', fmt: 'id' }],
    missingReason: true,
  },
  task_submitted: {
    shape: 'single-line',
    emphasis: 'body',
    tone: 'info',
    icon: icon(SendOutlined),
    moduleLabelKey: 'notif.mod.task',
    codeKind: 'docNumber',
    metaFields: [{ key: 'taskId', labelKey: 'notif.meta.taskId', fmt: 'id' }],
  },
  task_completed: {
    shape: 'single-line',
    emphasis: 'body',
    tone: 'success',
    icon: icon(CheckCircleOutlined),
    moduleLabelKey: 'notif.mod.task',
    codeKind: 'docNumber',
    metaFields: [{ key: 'taskId', labelKey: 'notif.meta.taskId', fmt: 'id' }],
  },
  task_not_needed: {
    shape: 'single-line',
    emphasis: 'body',
    tone: 'neutral',
    icon: icon(MinusCircleOutlined),
    moduleLabelKey: 'notif.mod.task',
    codeKind: 'docNumber',
    metaFields: [{ key: 'taskId', labelKey: 'notif.meta.taskId', fmt: 'id' }],
  },
  task_reopened: {
    shape: 'single-line',
    emphasis: 'body',
    tone: 'warning',
    icon: icon(RedoOutlined),
    moduleLabelKey: 'notif.mod.task',
    codeKind: 'docNumber',
    metaFields: [{ key: 'taskId', labelKey: 'notif.meta.taskId', fmt: 'id' }],
  },

  announcement_new: {
    shape: 'multiline',
    emphasis: 'title',
    tone: 'info',
    icon: icon(SoundOutlined),
    moduleLabelKey: 'notif.mod.council',
    codeKind: 'letter',
    metaFields: [{ key: 'announcementId', labelKey: 'notif.meta.announcementId', fmt: 'id' }],
    truncatedUpstream: true,
  },
  [`task_assigned${COUNCIL_VARIANT_SUFFIX}`]: {
    shape: 'title-only',
    emphasis: 'title',
    tone: 'info',
    icon: icon(FileAddOutlined),
    moduleLabelKey: 'notif.mod.council',
    codeKind: 'letter',
    metaFields: [{ key: 'taskId', labelKey: 'notif.meta.taskId', fmt: 'id' }],
  },
  [`task_completed${COUNCIL_VARIANT_SUFFIX}`]: {
    shape: 'title-only',
    emphasis: 'title',
    tone: 'success',
    icon: icon(CheckCircleOutlined),
    moduleLabelKey: 'notif.mod.council',
    codeKind: 'letter',
    metaFields: [{ key: 'taskId', labelKey: 'notif.meta.taskId', fmt: 'id' }],
  },
  council_task_overdue: {
    shape: 'title-only',
    emphasis: 'title',
    tone: 'warning',
    icon: icon(ClockCircleOutlined),
    moduleLabelKey: 'notif.mod.council',
    codeKind: 'letter',
    metaFields: [{ key: 'taskId', labelKey: 'notif.meta.taskId', fmt: 'id' }],
  },
  council_rank_accepted: {
    shape: 'title-only',
    emphasis: 'title',
    tone: 'success',
    icon: icon(TrophyOutlined),
    moduleLabelKey: 'notif.mod.council',
    codeKind: 'letter',
    metaFields: [{ key: 'applicationId', labelKey: 'notif.meta.applicationId', fmt: 'id' }],
  },
  council_rank_returned: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'danger',
    icon: icon(CloseCircleOutlined),
    moduleLabelKey: 'notif.mod.council',
    codeKind: 'letter',
    metaFields: [{ key: 'applicationId', labelKey: 'notif.meta.applicationId', fmt: 'id' }],
  },
  council_voting_started: {
    shape: 'title-only',
    emphasis: 'title',
    tone: 'info',
    icon: icon(CheckSquareOutlined),
    moduleLabelKey: 'notif.mod.council',
    codeKind: 'letter',
    metaFields: [{ key: 'sessionId', labelKey: 'notif.meta.sessionId', fmt: 'id' }],
  },
  council_voting_finished: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'info',
    icon: icon(CheckSquareOutlined),
    moduleLabelKey: 'notif.mod.council',
  },

  science_work_submitted: {
    shape: 'title-only',
    emphasis: 'title',
    tone: 'info',
    icon: icon(FileAddOutlined),
    moduleLabelKey: 'notif.mod.scienceCouncil',
    metaFields: [{ key: 'workId', labelKey: 'notif.meta.workId', fmt: 'id' }],
  },
  science_work_status_changed: {
    shape: 'title-only',
    emphasis: 'title',
    tone: 'info',
    icon: icon(SyncOutlined),
    moduleLabelKey: 'notif.mod.scienceCouncil',
    metaFields: [{ key: 'workId', labelKey: 'notif.meta.workId', fmt: 'id' }],
  },
  science_decision_made: {
    shape: 'title-only',
    emphasis: 'title',
    tone: 'info',
    icon: icon(FileProtectOutlined),
    moduleLabelKey: 'notif.mod.scienceCouncil',
    metaFields: [{ key: 'workId', labelKey: 'notif.meta.workId', fmt: 'id' }],
  },
  science_seminar_result_set: {
    shape: 'title-only',
    emphasis: 'title',
    tone: 'info',
    icon: icon(TrophyOutlined),
    moduleLabelKey: 'notif.mod.scienceCouncil',
    metaFields: [{ key: 'workId', labelKey: 'notif.meta.workId', fmt: 'id' }],
  },
  science_review_added: {
    shape: 'title-only',
    emphasis: 'title',
    tone: 'info',
    icon: icon(FileTextOutlined),
    moduleLabelKey: 'notif.mod.scienceCouncil',
    metaFields: [
      { key: 'workId', labelKey: 'notif.meta.workId', fmt: 'id' },
      { key: 'reviewId', labelKey: 'notif.meta.reviewId', fmt: 'id' },
    ],
  },
  science_member_added: {
    shape: 'title-only',
    emphasis: 'title',
    tone: 'success',
    icon: icon(CheckCircleOutlined),
    moduleLabelKey: 'notif.mod.scienceCouncil',
    metaFields: [{ key: 'memberId', labelKey: 'notif.meta.memberId', fmt: 'id' }],
  },
  science_member_removed: {
    shape: 'title-only',
    emphasis: 'title',
    tone: 'neutral',
    icon: icon(CloseCircleOutlined),
    moduleLabelKey: 'notif.mod.scienceCouncil',
    metaFields: [{ key: 'memberId', labelKey: 'notif.meta.memberId', fmt: 'id' }],
  },
  science_application_accepted: {
    shape: 'title-only',
    emphasis: 'title',
    tone: 'success',
    icon: icon(CheckCircleOutlined),
    moduleLabelKey: 'notif.mod.scienceCouncil',
    metaFields: [{ key: 'workId', labelKey: 'notif.meta.workId', fmt: 'id' }],
  },
  science_application_rejected: {
    shape: 'multiline',
    emphasis: 'title',
    tone: 'danger',
    icon: icon(CloseCircleOutlined),
    moduleLabelKey: 'notif.mod.scienceCouncil',
    metaFields: [{ key: 'workId', labelKey: 'notif.meta.workId', fmt: 'id' }],
  },

  eq_submission_created: {
    shape: 'title-only',
    emphasis: 'title',
    tone: 'info',
    icon: icon(SendOutlined),
    moduleLabelKey: 'notif.mod.qualityAssurance',
    metaFields: [
      { key: 'submissionId', labelKey: 'notif.meta.submissionId', fmt: 'id' },
      { key: 'indicatorId', labelKey: 'notif.meta.indicatorId', fmt: 'id' },
    ],
  },
  eq_submission_reviewed: {
    shape: 'title-only',
    emphasis: 'title',
    tone: 'info',
    icon: icon(CheckCircleOutlined),
    moduleLabelKey: 'notif.mod.qualityAssurance',
    metaFields: [{ key: 'submissionId', labelKey: 'notif.meta.submissionId', fmt: 'id' }],
  },

  qualifying_applicant: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'info',
    icon: icon(FileProtectOutlined),
    moduleLabelKey: 'notif.mod.science',
    metaFields: [{ key: 'applicantId', labelKey: 'notif.meta.applicantId', fmt: 'id' }],
  },
  scientific_post: {
    shape: 'multiline',
    emphasis: 'title',
    tone: 'info',
    icon: icon(SoundOutlined),
    moduleLabelKey: 'notif.mod.science',
    metaFields: [
      { key: 'postId', labelKey: 'notif.meta.postId', fmt: 'id' },
      { key: 'specialtyCode', labelKey: 'notif.meta.specialtyCode', fmt: 'text' },
    ],
  },

  contract_sent_to_rector: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'info',
    icon: icon(SendOutlined),
    moduleLabelKey: 'notif.mod.practice',
    metaFields: [{ key: 'contractId', labelKey: 'notif.meta.contractId', fmt: 'id' }],
  },
  contract_rektor_approved: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'info',
    icon: icon(CheckCircleOutlined),
    moduleLabelKey: 'notif.mod.practice',
    metaFields: [{ key: 'contractId', labelKey: 'notif.meta.contractId', fmt: 'id' }],
  },
  contract_both_approved: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'success',
    icon: icon(CheckCircleOutlined),
    moduleLabelKey: 'notif.mod.practice',
    metaFields: [{ key: 'contractId', labelKey: 'notif.meta.contractId', fmt: 'id' }],
  },
  contract_rejected: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'danger',
    icon: icon(CloseCircleOutlined),
    moduleLabelKey: 'notif.mod.practice',
    metaFields: [{ key: 'contractId', labelKey: 'notif.meta.contractId', fmt: 'id' }],
  },

  personalWorkPlan_submitted: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'info',
    icon: icon(SendOutlined),
    moduleLabelKey: 'notif.mod.teacher',
    metaFields: [{ key: 'planId', labelKey: 'notif.meta.planId', fmt: 'id' }],
  },
  personalWorkPlan_stepPending: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'info',
    icon: icon(ClockCircleOutlined),
    moduleLabelKey: 'notif.mod.teacher',
    metaFields: [{ key: 'planId', labelKey: 'notif.meta.planId', fmt: 'id' }],
  },
  personalWorkPlan_approved: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'success',
    icon: icon(CheckCircleOutlined),
    moduleLabelKey: 'notif.mod.teacher',
    metaFields: [{ key: 'planId', labelKey: 'notif.meta.planId', fmt: 'id' }],
  },
  personalWorkPlan_rejected: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'danger',
    icon: icon(CloseCircleOutlined),
    moduleLabelKey: 'notif.mod.teacher',
    metaFields: [{ key: 'planId', labelKey: 'notif.meta.planId', fmt: 'id' }],
  },
  personalReport_submitted: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'info',
    icon: icon(SendOutlined),
    moduleLabelKey: 'notif.mod.teacher',
    metaFields: [
      { key: 'reportId', labelKey: 'notif.meta.reportId', fmt: 'id' },
      { key: 'planId', labelKey: 'notif.meta.planId', fmt: 'id' },
    ],
  },
  personalReport_approved: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'success',
    icon: icon(CheckCircleOutlined),
    moduleLabelKey: 'notif.mod.teacher',
    metaFields: [
      { key: 'reportId', labelKey: 'notif.meta.reportId', fmt: 'id' },
      { key: 'planId', labelKey: 'notif.meta.planId', fmt: 'id' },
    ],
  },
  personalReport_rejected: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'danger',
    icon: icon(CloseCircleOutlined),
    moduleLabelKey: 'notif.mod.teacher',
    metaFields: [
      { key: 'reportId', labelKey: 'notif.meta.reportId', fmt: 'id' },
      { key: 'planId', labelKey: 'notif.meta.planId', fmt: 'id' },
    ],
  },
  teacherProfile_approved: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'success',
    icon: icon(SafetyCertificateOutlined),
    moduleLabelKey: 'notif.mod.teacher',
    metaFields: [{ key: 'profileId', labelKey: 'notif.meta.profileId', fmt: 'id' }],
  },
  teacherProfile_rejected: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'danger',
    icon: icon(CloseCircleOutlined),
    moduleLabelKey: 'notif.mod.teacher',
    metaFields: [{ key: 'profileId', labelKey: 'notif.meta.profileId', fmt: 'id' }],
  },
  teacherLeave_submitted: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'info',
    icon: icon(FileTextOutlined),
    moduleLabelKey: 'notif.mod.studyLoad',
    metaFields: [{ key: 'leaveId', labelKey: 'notif.meta.leaveId', fmt: 'id' }],
  },
  teacherLeave_approved: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'success',
    icon: icon(CheckCircleOutlined),
    moduleLabelKey: 'notif.mod.studyLoad',
    metaFields: [{ key: 'leaveId', labelKey: 'notif.meta.leaveId', fmt: 'id' }],
  },
  teacherLeave_rejected: {
    shape: 'single-line',
    emphasis: 'title',
    tone: 'danger',
    icon: icon(CloseCircleOutlined),
    moduleLabelKey: 'notif.mod.studyLoad',
    metaFields: [{ key: 'leaveId', labelKey: 'notif.meta.leaveId', fmt: 'id' }],
  },
};

export const UNKNOWN_EVENT_ICON = icon(BellOutlined);
