import { describe, expect, it } from 'vitest';
import { mapPersonalPlan, mapPersonalPlanDetail, toWorkItemPayload } from './mapper';
import type { BackendPersonalPlanDetail, BackendPersonalPlanList } from './mapper';

function buildBackendDetail(overrides: Partial<BackendPersonalPlanDetail> = {}): BackendPersonalPlanDetail {
  return {
    _id: 'plan-1',
    name: null,
    teacher: { _id: 't1', firstName: 'Ali', lastName: 'Valiyev' },
    academicYear: { _id: 'ay1', title: '2025-2026' },
    status: 'draft',
    teachingLoad: { autoGenerated: true, plannedHour: 400, completedHour: 0, sciences: [] },
    methodicalWork: [],
    researchWork: [],
    mentoringWork: [],
    organizationalWork: [],
    extraWork: [],
    approvals: [],
    approvedBy: null,
    approvalDate: null,
    approvalComment: null,
    createdAt: '2026-07-30T00:00:00.000Z',
    ...overrides,
  };
}

describe('mapPersonalPlanDetail', () => {
  it("reja nomini (`name`) map qiladi, yo'q bo'lsa null qaytaradi", () => {
    expect(mapPersonalPlanDetail(buildBackendDetail({ name: 'Mening rejam' })).name).toBe(
      'Mening rejam',
    );
    expect(mapPersonalPlanDetail(buildBackendDetail({ name: undefined })).name).toBeNull();
  });

  it("mentoringWork'ni ENDI umumiy WorkItem shakli bilan map qiladi", () => {
    const backend = buildBackendDetail({
      mentoringWork: [
        {
          _id: 'm1',
          title: 'Sardor Alimov — Yurak kasalliklari',
          status: 'planned',
          plannedCount: 1,
          actualCount: 0,
          semester: [1],
          venue: 'Kafedra',
        },
      ],
    });

    const detail = mapPersonalPlanDetail(backend);

    expect(detail.mentoringWork).toHaveLength(1);
    expect(detail.mentoringWork[0]).toMatchObject({
      id: 'm1',
      title: 'Sardor Alimov — Yurak kasalliklari',
      plannedCount: 1,
      actualCount: 0,
      semester: [1],
      venue: 'Kafedra',
    });
  });

  it("umumiy WorkItem yangi maydonlarni (plannedCount, actualCount, semester[], link, verification) map qiladi", () => {
    const backend = buildBackendDetail({
      researchWork: [
        {
          _id: 'r1',
          title: 'Maqola chop etish',
          status: 'completed',
          plannedCount: 2,
          actualCount: 1,
          semester: [1, 2],
          link: 'https://scopus.com/x',
          verification: { status: 'pending', reviewedBy: null, date: null, comment: null },
        },
      ],
    });

    const detail = mapPersonalPlanDetail(backend);

    expect(detail.researchWork[0]).toMatchObject({
      id: 'r1',
      title: 'Maqola chop etish',
      plannedCount: 2,
      actualCount: 1,
      semester: [1, 2],
      link: 'https://scopus.com/x',
      verification: { status: 'pending', date: null, comment: null },
    });
  });

  it("semester bo'sh/yo'q bo'lsa [] qaytaradi, verification yo'q bo'lsa null", () => {
    const backend = buildBackendDetail({
      extraWork: [{ _id: 'e1', title: 'Konferensiya', status: 'planned' }],
    });

    const detail = mapPersonalPlanDetail(backend);

    expect(detail.extraWork[0]).toMatchObject({ semester: [], verification: null });
  });

  it("effectiveStatus (TZ 4.3.9 virtual) status'dan USTUN turadi — 'overdue' shundan keladi", () => {
    const backend = buildBackendDetail({
      methodicalWork: [
        { _id: 'w1', title: "Muddati o'tgan vazifa", status: 'planned', effectiveStatus: 'overdue' },
        { _id: 'w2', title: 'Oddiy vazifa', status: 'planned' },
      ],
    });

    const detail = mapPersonalPlanDetail(backend);

    expect(detail.methodicalWork[0]?.status).toBe('overdue');
    expect(detail.methodicalWork[1]?.status).toBe('planned');
  });

  it("approvals[] ni map qiladi — approvedBy POPULATE QILINGAN bo'lsa approvedByName to'ldiriladi", () => {
    const backend = buildBackendDetail({
      approvals: [
        {
          step: 'teacher',
          label: "Kafedra assistenti (o'qituvchining o'zi)",
          status: 'approved',
          approvedBy: { _id: 'u1', firstName: 'Ali', lastName: 'Valiyev' },
          date: '2026-07-30T00:00:00.000Z',
          comment: null,
        },
        { step: 'kafedraMudiri', label: 'Kafedra mudiri', status: 'pending', approvedBy: null, date: null, comment: null },
      ],
    });

    const detail = mapPersonalPlanDetail(backend);

    expect(detail.approvals).toHaveLength(2);
    expect(detail.approvals[0]).toMatchObject({
      step: 'teacher',
      status: 'approved',
      approvedById: 'u1',
      approvedByName: 'Valiyev Ali',
    });
    expect(detail.approvals[1]).toMatchObject({
      step: 'kafedraMudiri',
      status: 'pending',
      approvedById: null,
      approvedByName: null,
    });
  });

  it("approvals[].approvedBy hali ham string (populate qilinmagan) bo'lsa approvedByName null qaytaradi", () => {
    const backend = buildBackendDetail({
      approvals: [
        { step: 'teacher', label: "Kafedra assistenti", status: 'approved', approvedBy: 'u1', date: '2026-07-30T00:00:00.000Z', comment: null },
      ],
    });

    const detail = mapPersonalPlanDetail(backend);

    expect(detail.approvals[0]).toMatchObject({ approvedById: 'u1', approvedByName: null });
  });
});

describe('mapPersonalPlan — ADR-009 navbat hosilalari', () => {
  const listDoc = (approvals: BackendPersonalPlanList['approvals']): BackendPersonalPlanList => ({
    _id: 'plan-9',
    teacher: { _id: 't9', firstName: 'Ali', lastName: 'Valiyev' },
    academicYear: { _id: 'ay1', title: '2025-2026' },
    status: 'submitted',
    teachingLoad: { autoGenerated: true, plannedHour: 880 },
    approvals,
    createdAt: '2026-07-01T00:00:00.000Z',
  });

  it('`currentStep` — zanjirdagi BIRINCHI `pending` bosqich', () => {
    const plan = mapPersonalPlan(
      listDoc([
        { step: 'teacher', label: 'Assistent', status: 'approved', date: '2026-08-01T09:00:00.000Z' },
        { step: 'kafedraUslubiy', label: "Uslubiy mas'ul", status: 'approved', date: '2026-08-02T09:00:00.000Z' },
        { step: 'kafedraIlmiy', label: "Ilmiy mas'ul", status: 'pending', date: null },
        { step: 'kafedraMudiri', label: 'Kafedra mudiri', status: 'pending', date: null },
      ]),
    );

    expect(plan.currentStep).toBe('kafedraIlmiy');
    expect(plan.currentStepLabel).toBe("Ilmiy mas'ul");
    expect(plan.approvals).toHaveLength(4);
  });

  it('barcha bosqich imzolangan — `currentStep` null', () => {
    const plan = mapPersonalPlan(
      listDoc([
        { step: 'teacher', label: 'Assistent', status: 'approved', date: '2026-08-01T09:00:00.000Z' },
        { step: 'dekan', label: 'Dekan', status: 'approved', date: '2026-08-05T09:00:00.000Z' },
      ]),
    );

    expect(plan.currentStep).toBeNull();
    expect(plan.currentStepLabel).toBeNull();
  });

  it('`approvals` umuman kelmasa — bo`sh massiv, null hosilalar (crash yo`q)', () => {
    const plan = mapPersonalPlan(listDoc(undefined));

    expect(plan.approvals).toEqual([]);
    expect(plan.currentStep).toBeNull();
    expect(plan.submittedAt).toBeNull();
  });

  it('`submittedAt` — 1-bosqich (`teacher`) imzosi sanasi, `createdAt` EMAS', () => {
    const plan = mapPersonalPlan(
      listDoc([
        { step: 'teacher', label: 'Assistent', status: 'approved', date: '2026-08-01T09:00:00.000Z' },
        { step: 'kafedraMudiri', label: 'Kafedra mudiri', status: 'pending', date: null },
      ]),
    );

    expect(plan.submittedAt).toBe('2026-08-01T09:00:00.000Z');
    expect(plan.createdAt).toBe('2026-07-01T00:00:00.000Z');
    expect(plan.submittedAt).not.toBe(plan.createdAt);
  });

  it('hali yuborilmagan (1-bosqich `pending`) — `submittedAt` null', () => {
    const plan = mapPersonalPlan(
      listDoc([{ step: 'teacher', label: 'Assistent', status: 'pending', date: null }]),
    );

    expect(plan.submittedAt).toBeNull();
    expect(plan.currentStep).toBe('teacher');
  });

  it("ro`yxatda imzolovchi ismi bo`lmaydi (populate yo`q) ⇒ jadvalda \"kim imzoladi\" ustuni yo`q", () => {
    const plan = mapPersonalPlan(
      listDoc([
        { step: 'teacher', label: 'Assistent', status: 'approved', approvedBy: 'u1', date: '2026-08-01T09:00:00.000Z' },
      ]),
    );

    expect(plan.approvals[0]).toMatchObject({ approvedById: 'u1', approvedByName: null });
  });
});

describe('toWorkItemPayload', () => {
  it("standart maydonlarni qaytaradi, venue'siz (includeVenue=false)", () => {
    const payload = toWorkItemPayload(
      { title: '  Maqola  ', plannedCount: 3, semester: [1, 2], deadline: '2026-09-01', venue: 'Xona 12' },
      false,
    );

    expect(payload).toEqual({
      title: 'Maqola',
      plannedCount: 3,
      semester: [1, 2],
      deadline: '2026-09-01',
    });
  });

  it('includeVenue=true bo\'lsa venue qo\'shiladi, bo\'sh bo\'lsa null', () => {
    const withVenue = toWorkItemPayload(
      { title: 'Yig\'in', plannedCount: null, semester: [], deadline: null, venue: 'Kafedra zali' },
      true,
    );
    expect(withVenue).toMatchObject({ venue: 'Kafedra zali', plannedCount: 0, deadline: null });

    const emptyVenue = toWorkItemPayload(
      { title: 'Yig\'in', plannedCount: null, semester: [], deadline: null, venue: '  ' },
      true,
    );
    expect(emptyVenue.venue).toBeNull();
  });
});

describe('mapPersonalPlanDetail — I bo\'lim ustunlari (D-3b)', () => {
  const science = (hoursByType: Record<string, number | null | undefined>, extra = {}) => ({
    _id: 'sc1',
    scienceName: 'Odam anatomiyasi',
    course: 2,
    semester: 1,
    totalHour: 226,
    stavka: 0.5,
    hoursByType: { lecture: 24, seminar: 192, laboratory: 0, practical: 0, independent: 10, ...hoursByType },
    ...extra,
  });
  const mapOne = (s: ReturnType<typeof science>) =>
    mapPersonalPlanDetail(
      buildBackendDetail({ teachingLoad: { autoGenerated: true, plannedHour: 226, completedHour: 0, sciences: [s] } }),
    ).sciences[0]!;

  it('yangi qator: ustunlar son, oqim/guruh o\'tadi, `decomposed` = true', () => {
    const r = mapOne(
      science({ on: 0, yan: 0, retake: 10, practiceLead: 0, otherWork: 0, adjustment: 0 }, { streamCount: 1, groupCount: 8 }),
    );
    expect(r.decomposed).toBe(true);
    expect(r.hoursByType.retake).toBe(10);
    expect(r.streamCount).toBe(1);
    expect(r.groupCount).toBe(8);
  });

  it('eski qator (kalitlar yo\'q yoki null): `null` qoladi — 0 EMAS, `decomposed` = false', () => {
    const r = mapOne(science({ on: null }));
    expect(r.decomposed).toBe(false);
    expect(r.hoursByType.on).toBeNull();
    expect(r.hoursByType.retake).toBeNull();
    expect(r.streamCount).toBeNull();
    expect(r.hoursByType.independent).toBe(10);
  });
});
