import type {
  PersonalPlan,
  PersonalPlanDetail,
  PersonalPlanStatus,
  TeachingScience,
  WorkItem,
  WorkItemStatus,
  WorkItemVerification,
  VerificationStatus,
  HoursByType,
  WorkItemFormValues,
  ApprovalStep,
  ApprovalStepKey,
  ApprovalStepStatus,
} from '../model/types';

interface BackendTeacher {
  _id: string;
  firstName?: string | null;
  lastName?: string | null;
  middleName?: string | null;
}

interface BackendApprovedBy {
  _id: string;
  firstName?: string | null;
  lastName?: string | null;
}

interface BackendAcademicYear {
  _id: string;
  title?: string | null;
}

interface BackendHoursByType {
  lecture?: number;
  seminar?: number;
  laboratory?: number;
  practical?: number;
  independent?: number;
  on?: number | null;
  yan?: number | null;
  retake?: number | null;
  practiceLead?: number | null;
  otherWork?: number | null;
  adjustment?: number | null;
}

interface BackendScience {
  _id: string;
  title?: string | null;
}

interface BackendTeachingScience {
  _id: string;
  science?: BackendScience | string | null;
  scienceName?: string | null;
  course?: number;
  semester?: number;
  hoursByType?: BackendHoursByType;
  totalHour?: number;
  stavka?: number;
  streamCount?: number | null;
  groupCount?: number | null;
}

interface BackendWorkItemVerification {
  status?: VerificationStatus;
  reviewedBy?: string | null;
  date?: string | null;
  comment?: string | null;
}

interface BackendWorkItem {
  _id: string;
  title: string;
  description?: string | null;
  deadline?: string | null;
  completedAt?: string | null;
  status?: WorkItemStatus;
  effectiveStatus?: WorkItemStatus;
  fileUrl?: string | null;
  link?: string | null;
  note?: string | null;
  semester?: number[];
  plannedCount?: number;
  actualCount?: number;
  venue?: string | null;
  verification?: BackendWorkItemVerification | null;
}

interface BackendApprovalStep {
  step: string;
  label?: string | null;
  approvedBy?: string | { _id: string; firstName?: string | null; lastName?: string | null } | null;
  status?: ApprovalStepStatus;
  date?: string | null;
  comment?: string | null;
}

export interface BackendPersonalPlanList {
  _id: string;
  teacher?: BackendTeacher | null;
  academicYear?: BackendAcademicYear | string | null;
  status?: PersonalPlanStatus;
  teachingLoad?: {
    autoGenerated?: boolean;
    plannedHour?: number;
    sciences?: BackendTeachingScience[];
  };
  approvals?: BackendApprovalStep[];
  createdAt?: string | null;
}

export interface BackendPersonalPlanDetail extends BackendPersonalPlanList {
  name?: string | null;
  teachingLoad?: {
    autoGenerated?: boolean;
    generatedAt?: string | null;
    plannedHour?: number;
    completedHour?: number;
    sciences?: BackendTeachingScience[];
  };
  methodicalWork?: BackendWorkItem[];
  researchWork?: BackendWorkItem[];
  mentoringWork?: BackendWorkItem[];
  organizationalWork?: BackendWorkItem[];
  extraWork?: BackendWorkItem[];
  approvals?: BackendApprovalStep[];
  approvedBy?: BackendApprovedBy | null;
  approvalDate?: string | null;
  approvalComment?: string | null;
}

function extractTeacherName(teacher: BackendTeacher | null | undefined): string | null {
  if (!teacher) return null;
  return [teacher.lastName, teacher.firstName].filter(Boolean).join(' ') || null;
}

function extractAcademicYearId(
  ay: BackendAcademicYear | string | null | undefined,
): string | null {
  if (!ay) return null;
  if (typeof ay === 'string') return ay;
  return ay._id;
}

function extractAcademicYearTitle(
  ay: BackendAcademicYear | string | null | undefined,
): string | null {
  if (!ay || typeof ay === 'string') return null;
  return ay.title ?? null;
}

function extractScienceName(
  science: BackendScience | string | null | undefined,
  fallback: string | null | undefined,
): string | null {
  if (science && typeof science === 'object') {
    return science.title ?? fallback ?? null;
  }
  return fallback ?? null;
}

const orNull = (v: number | null | undefined): number | null =>
  typeof v === 'number' && Number.isFinite(v) ? v : null;

function mapHoursByType(h: BackendHoursByType | undefined): HoursByType {
  return {
    lecture: h?.lecture ?? 0,
    seminar: h?.seminar ?? 0,
    laboratory: h?.laboratory ?? 0,
    practical: h?.practical ?? 0,
    independent: h?.independent ?? 0,
    on: orNull(h?.on),
    yan: orNull(h?.yan),
    retake: orNull(h?.retake),
    practiceLead: orNull(h?.practiceLead),
    otherWork: orNull(h?.otherWork),
    adjustment: orNull(h?.adjustment),
  };
}

function mapVerification(v: BackendWorkItemVerification | null | undefined): WorkItemVerification | null {
  if (!v || !v.status) return null;
  return {
    status: v.status,
    date: v.date ?? null,
    comment: v.comment ?? null,
  };
}

function mapWorkItem(b: BackendWorkItem): WorkItem {
  return {
    id: b._id,
    title: b.title,
    description: b.description ?? null,
    deadline: b.deadline ?? null,
    completedAt: b.completedAt ?? null,
    status: b.effectiveStatus ?? b.status ?? 'planned',
    fileUrl: b.fileUrl ?? null,
    link: b.link ?? null,
    note: b.note ?? null,
    semester: Array.isArray(b.semester) ? b.semester : [],
    plannedCount: b.plannedCount ?? null,
    actualCount: b.actualCount ?? null,
    venue: b.venue ?? null,
    verification: mapVerification(b.verification),
  };
}

function mapTeachingScience(b: BackendTeachingScience): TeachingScience {
  const hoursByType = mapHoursByType(b.hoursByType);
  return {
    id: b._id,
    scienceName: extractScienceName(b.science, b.scienceName),
    course: b.course ?? 0,
    semester: b.semester ?? 0,
    hoursByType,
    totalHour: b.totalHour ?? 0,
    stavka: b.stavka ?? 1,
    streamCount: orNull(b.streamCount),
    groupCount: orNull(b.groupCount),
    decomposed: hoursByType.on !== null,
  };
}

function extractApprovedById(
  approvedBy: BackendApprovalStep['approvedBy'],
): string | null {
  if (!approvedBy) return null;
  if (typeof approvedBy === 'string') return approvedBy;
  return approvedBy._id;
}

function extractApprovedByName(
  approvedBy: BackendApprovalStep['approvedBy'],
): string | null {
  if (!approvedBy || typeof approvedBy === 'string') return null;
  return [approvedBy.lastName, approvedBy.firstName].filter(Boolean).join(' ') || null;
}

function mapApprovalStep(b: BackendApprovalStep): ApprovalStep {
  return {
    step: b.step as ApprovalStepKey,
    label: b.label ?? b.step,
    status: b.status ?? 'pending',
    approvedById: extractApprovedById(b.approvedBy),
    approvedByName: extractApprovedByName(b.approvedBy),
    date: b.date ?? null,
    comment: b.comment ?? null,
  };
}

function findFirstPendingStep(approvals: ApprovalStep[]): ApprovalStep | null {
  return approvals.find((a) => a.status === 'pending') ?? null;
}

function extractSubmittedAt(approvals: ApprovalStep[]): string | null {
  return approvals.find((a) => a.step === 'teacher')?.date ?? null;
}

export function mapPersonalPlan(b: BackendPersonalPlanList): PersonalPlan {
  const sciences = b.teachingLoad?.sciences ?? [];
  const approvals = (b.approvals ?? []).map(mapApprovalStep);
  const pending = findFirstPendingStep(approvals);

  return {
    id: b._id,
    academicYearId: extractAcademicYearId(b.academicYear),
    academicYearTitle: extractAcademicYearTitle(b.academicYear),
    teacherId: b.teacher?._id ?? null,
    teacherName: extractTeacherName(b.teacher),
    status: b.status ?? 'draft',
    plannedHour: b.teachingLoad?.plannedHour ?? 0,
    scienceCount: sciences.length,
    autoGenerated: b.teachingLoad?.autoGenerated ?? false,
    createdAt: b.createdAt ?? null,
    approvals,
    currentStep: pending?.step ?? null,
    currentStepLabel: pending?.label ?? null,
    submittedAt: extractSubmittedAt(approvals),
  };
}

export function mapPersonalPlanDetail(b: BackendPersonalPlanDetail): PersonalPlanDetail {
  const sciences = (b.teachingLoad?.sciences ?? []).map(mapTeachingScience);

  const approvedByName = b.approvedBy
    ? [b.approvedBy.lastName, b.approvedBy.firstName].filter(Boolean).join(' ') || null
    : null;

  return {
    id: b._id,
    name: b.name ?? null,
    academicYearId: extractAcademicYearId(b.academicYear),
    academicYearTitle: extractAcademicYearTitle(b.academicYear),
    teacherId: b.teacher?._id ?? null,
    teacherName: extractTeacherName(b.teacher),
    status: b.status ?? 'draft',
    plannedHour: b.teachingLoad?.plannedHour ?? 0,
    completedHour: b.teachingLoad?.completedHour ?? 0,
    autoGenerated: b.teachingLoad?.autoGenerated ?? false,
    sciences,
    methodicalWork: (b.methodicalWork ?? []).map(mapWorkItem),
    researchWork: (b.researchWork ?? []).map(mapWorkItem),
    mentoringWork: (b.mentoringWork ?? []).map(mapWorkItem),
    organizationalWork: (b.organizationalWork ?? []).map(mapWorkItem),
    extraWork: (b.extraWork ?? []).map(mapWorkItem),
    approvals: (b.approvals ?? []).map(mapApprovalStep),
    approvedByName,
    approvalDate: b.approvalDate ?? null,
    approvalComment: b.approvalComment ?? null,
    createdAt: b.createdAt ?? null,
  };
}

export function toWorkItemPayload(
  values: WorkItemFormValues,
  includeVenue: boolean,
): Record<string, unknown> {
  const payload: Record<string, unknown> = {
    title: values.title.trim(),
    plannedCount: values.plannedCount ?? 0,
    semester: values.semester,
    deadline: values.deadline || null,
  };
  if (includeVenue) {
    payload.venue = values.venue.trim() || null;
  }
  return payload;
}
