import { lazy } from 'react';
import { defineModule } from '@/shared/lib/module';

export default defineModule({
  name: 'notifications',
  basePath: '/bildirishnomalar',
  routes: [
    { index: true, element: lazy(() => import('./pages/feed-page')) },
    { path: 'sozlamalar', element: lazy(() => import('./pages/settings-page')) },
  ],
  i18n: {
    uz: {
      'notif.title': 'Bildirishnomalar',
      'notif.refresh': 'Yangilash',
      'notif.viewAll': "Barchasini ko'rish",
      'notif.markAll': "Barchasini o'qilgan deb belgilash",
      'notif.markAllConfirm.title': "Barchasini o'qilgan deb belgilaysizmi?",
      'notif.markAllConfirm.desc': "Bu amalni bekor qilib bo'lmaydi.",
      'notif.markAllConfirm.ok': 'Ha',
      'notif.markAllConfirm.cancel': 'Bekor qilish',
      'notif.markOne': "O'qilgan deb belgilash",
      'notif.detail': 'Batafsil',
      'notif.copy': 'Nusxa olish',
      'notif.copied': 'Nusxa olindi',
      'notif.more': "Ko'proq",
      'notif.less': 'Kamroq',
      'notif.empty.title': "Bildirishnoma yo'q",
      'notif.empty.hint': "Yangi bildirishnomalar shu yerda ko'rinadi",
      'notif.error.title': 'Bildirishnomalar yuklanmadi',
      'notif.retry': 'Qayta urinish',
      'notif.offline': 'Oflayn — oxirgi yangilanish {{time}}',
      'notif.offlineNoData': "Oflayn — ma'lumot hali yuklanmagan",
      'notif.badge.stale': 'Soni yangilanmadi',
      'notif.bell.aria': "Bildirishnomalar, {{count}} ta o'qilmagan",
      'notif.bell.empty': "Bildirishnomalar, o'qilmagan yo'q",
      'notif.unread': "o'qilmagan",
      'notif.tab.all': 'Hammasi',
      'notif.tab.unread': "O'qilmagan",
      'notif.filter.type': "Turi bo'yicha",
      'notif.group.today': 'Bugun',
      'notif.group.yesterday': 'Kecha',
      'notif.group.thisWeek': 'Shu hafta',
      'notif.group.older': 'Oldingi',
      'notif.rollup': "{{count}} ta o'xshash bildirishnoma",
      'notif.tech': "Texnik ma'lumot",
      'notif.truncated': "Matn qisqartirilgan — to'liqi manba sahifasida",
      'notif.missingReason': "Rad sababi tizimda ko'rsatilmagan",
      'notif.noLink': 'Havola mavjud emas',
      'notif.noPermission': "Ushbu havolani ochish uchun ruxsatingiz yo'q",
      'notif.contentUzOnly': "Bildirishnoma matnlari hozircha faqat o'zbek tilida",

      'notif.settings.title': 'Bildirishnoma sozlamalari',
      'notif.settings.open': 'Sozlamalar',
      'notif.settings.global': 'Umumiy',
      'notif.settings.pause': "Bildirishnomalarni to'xtatish",
      'notif.settings.pauseHint': "Yoqilganda yangi bildirishnoma yuborilmaydi. Mavjudlari o'chirilmaydi.",
      'notif.settings.digest': 'Xulosa xabari',
      'notif.settings.digestHint': "Har bir hodisa uchun alohida emas, bitta yig'ma xabar yuboriladi.",
      'notif.settings.digestEnable': 'Yoqish',
      'notif.settings.daily': 'Har kuni',
      'notif.settings.weekly': 'Har hafta',
      'notif.settings.channels': 'Kanallar',
      'notif.settings.channelsHint':
        "Belgilanmagan hodisa tizim sozlamasi bo'yicha yuboriladi. Bir marta o'zgartirsangiz, o'sha tanlov saqlanadi.",
      'notif.settings.systemDefault': 'tizim sozlamasi',
      'notif.settings.save': 'Saqlash',
      'notif.settings.cancel': 'Bekor qilish',
      'notif.settings.saved': 'Sozlamalar saqlandi',
      'notif.channel.inApp': 'Tizimda',
      'notif.channel.telegram': 'Telegram',
      'notif.channel.email': 'E-pochta',
      'notif.channel.sms': 'SMS',

      'notif.event.eriExpiring': 'ERI sertifikati muddati tugayapti',
      'notif.event.eriExpired': 'ERI sertifikati muddati tugadi',
      'notif.event.slaOverdue': "SLA bo'yicha kechikish",
      'notif.event.slaEscalated': 'SLA eskalatsiyasi',
      'notif.event.vacancyReassigned': 'Yuklama qayta biriktirildi',
      'notif.event.recalcRequired': 'Qayta hisoblash talab qilinadi',
      'notif.event.residencyPlanReviewed': "Reja ko'rib chiqildi",
      'notif.event.residencyAttendanceWarning': 'Davomat ogohlantirishi',
      'notif.event.residencyAttendanceWarningSupervisor': 'Rezidentda davomat ogohlantirishi',
      'notif.event.residencyExpulsion': "Chetlatish buyrug'i loyihasi",
      'notif.event.residencyDailyLogReviewed': "Kundalik ko'rib chiqildi",
      'notif.event.residencyAnnouncementPublished': "Yangi e'lon",
      'notif.event.residencyExpulsionDraftOffice': "Chetlatish buyrug'i loyihasi (bo'lim)",
      'notif.event.residencyExpulsionSigned': "Chetlatish buyrug'i imzolandi",
      'notif.event.residencyExpulsionRejected': "Chetlatish buyrug'i loyihasi rad etildi",
      'notif.event.residencyExpulsionBasisLostOffice': 'Imzolangan buyruq asosi 72 soatdan tushdi',
      'notif.event.residencyAbsenceNoticeAuto': 'Davomat bildirgisi (avtomatik)',
      'notif.event.residencySamsDigest': "SAMS davomati — kunlik yig'ma",
      'notif.event.residencySamsTenantsChanged': "SAMS klinikalari o'zgardi",
      'notif.event.taskAssigned': 'Topshiriq biriktirildi',
      'notif.event.taskDeadlineChanged': "Topshiriq muddati o'zgartirildi",
      'notif.event.taskRejectedByExecutor': 'Topshiriq ijrochi tomonidan rad etildi',
      'notif.event.taskSubmitted': 'Topshiriq topshirildi',
      'notif.event.taskCompleted': 'Topshiriq bajarildi',
      'notif.event.taskNotNeeded': 'Topshiriq bekor qilindi',
      'notif.event.taskReopened': 'Topshiriq qayta ochildi',
      'notif.event.announcementNew': "Yangi e'lon",
      'notif.event.councilTaskOverdue': "Kengash topshirig'i muddati o'tdi",
      'notif.event.councilRankAccepted': 'Unvon arizasi qabul qilindi',
      'notif.event.councilRankReturned': 'Unvon arizasi qaytarildi',
      'notif.event.councilVotingStarted': 'Ovoz berish boshlandi',
      'notif.event.councilVotingFinished': 'Ovoz berish yakunlandi',
      'notif.event.qualifyingApplicant': 'Malaka oshirish arizasi bo\'yicha yangilanish',
      'notif.event.scientificPost': "Ilmiy e'lon",
      'notif.event.contractSentToRector': 'Shartnoma rektorga yuborildi',
      'notif.event.contractRektorApproved': 'Shartnoma rektor tomonidan tasdiqlandi',
      'notif.event.contractBothApproved': "Shartnoma to'liq tasdiqlandi",
      'notif.event.contractRejected': 'Shartnoma rad etildi',
      'notif.event.scienceWorkSubmitted': 'Yangi ilmiy ish topshirildi',
      'notif.event.scienceWorkStatusChanged': "Ilmiy ish holati o'zgardi",
      'notif.event.scienceDecisionMade': 'Yakuniy qaror qabul qilindi',
      'notif.event.scienceSeminarResultSet': 'Seminar natijasi belgilandi',
      'notif.event.scienceReviewAdded': 'Yangi xulosa qoldirildi',
      'notif.event.scienceMemberAdded': "Kengash a'zoligiga biriktirildi",
      'notif.event.scienceMemberRemoved': "Kengash a'zoligidan chetlashtirildi",
      'notif.event.scienceApplicationAccepted': 'Ariza qabul qilindi',
      'notif.event.scienceApplicationRejected': 'Ariza rad etildi',
      'notif.event.eqSubmissionCreated': "Tekshirish uchun ma'lumot yuborildi",
      'notif.event.eqSubmissionReviewed': "Yuborilgan ma'lumot ko'rib chiqildi",

      'notif.mod.system': 'Tizim',
      'notif.mod.studyLoad': "O'quv yuklamasi",
      'notif.mod.residency': 'Rezidentura',
      'notif.mod.task': 'Topshiriqlar',
      'notif.mod.council': 'Kengash',
      'notif.mod.science': "Ilmiy bo'lim",
      'notif.mod.practice': 'Amaliyot',
      'notif.mod.scienceCouncil': 'Ilmiy kengash',
      'notif.mod.qualityAssurance': "Ta'lim sifati",
      'notif.mod.teacher': "Professor-o'qituvchi",
      'notif.mod.unknown': "Noma'lum",

      'notif.meta.workId': 'Ilmiy ish ID',
      'notif.meta.reviewId': 'Xulosa ID',
      'notif.meta.memberId': "A'zolik ID",
      'notif.meta.submissionId': "Ma'lumot ID",
      'notif.meta.indicatorId': 'Indikator ID',
      'notif.meta.serialNumber': 'Seriya raqami',
      'notif.meta.daysLeft': 'Qolgan kunlar',
      'notif.meta.totalUnexcusedHours': 'Sababsiz soatlar',
      'notif.meta.chainId': 'Zanjir ID',
      'notif.meta.daysOverdue': 'Kechikkan kunlar',
      'notif.meta.originalRole': "Boshlang'ich rol",
      'notif.meta.distributionId': 'Taqsimot ID',
      'notif.meta.entryId': 'Yozuv ID',
      'notif.meta.previousTeacher': "Oldingi o'qituvchi",
      'notif.meta.groupId': 'Guruh ID',
      'notif.meta.oldCount': 'Eski son',
      'notif.meta.newCount': 'Yangi son',
      'notif.meta.affectedWorkloads': "Ta'sirlangan yuklamalar",
      'notif.meta.taskId': 'Topshiriq ID',
      'notif.meta.announcementId': "E'lon ID",
      'notif.meta.applicationId': 'Ariza ID',
      'notif.meta.sessionId': 'Sessiya ID',
      'notif.meta.applicantId': 'Ariza beruvchi ID',
      'notif.meta.postId': 'Post ID',
      'notif.meta.specialtyCode': 'Mutaxassislik kodi',
      'notif.meta.contractId': 'Shartnoma ID',
      'notif.meta.planId': 'Ish reja ID',
      'notif.meta.reportId': 'Hisobot ID',
      'notif.meta.profileId': 'Profil ID',
      'notif.meta.leaveId': 'Ariza ID',
      'notif.meta.orderId': 'Buyruq ID',
      'notif.meta.residentId': 'Rezident ID',
      'notif.meta.reminderStage': 'Eslatma bosqichi',
      'notif.meta.noticeId': 'Bildirgi ID',
      'notif.meta.digestDay': "Yig'ma kuni",
      'notif.meta.arrayCount': '{{count}} ta',
    },
    ru: {
      'notif.title': 'Уведомления',
      'notif.refresh': 'Обновить',
      'notif.viewAll': 'Посмотреть все',
      'notif.markAll': 'Отметить все прочитанными',
      'notif.markAllConfirm.title': 'Отметить все как прочитанные?',
      'notif.markAllConfirm.desc': 'Это действие нельзя отменить.',
      'notif.markAllConfirm.ok': 'Да',
      'notif.markAllConfirm.cancel': 'Отмена',
      'notif.markOne': 'Отметить прочитанным',
      'notif.detail': 'Подробнее',
      'notif.copy': 'Копировать',
      'notif.copied': 'Скопировано',
      'notif.more': 'Показать больше',
      'notif.less': 'Показать меньше',
      'notif.empty.title': 'Уведомлений нет',
      'notif.empty.hint': 'Новые уведомления появятся здесь',
      'notif.error.title': 'Не удалось загрузить уведомления',
      'notif.retry': 'Повторить',
      'notif.offline': 'Офлайн — последнее обновление {{time}}',
      'notif.offlineNoData': 'Офлайн — данные ещё не загружены',
      'notif.badge.stale': 'Счётчик не обновлён',
      'notif.bell.aria': 'Уведомления, непрочитанных: {{count}}',
      'notif.bell.empty': 'Уведомления, непрочитанных нет',
      'notif.unread': 'непрочитанное',
      'notif.tab.all': 'Все',
      'notif.tab.unread': 'Непрочитанные',
      'notif.filter.type': 'По типу',
      'notif.group.today': 'Сегодня',
      'notif.group.yesterday': 'Вчера',
      'notif.group.thisWeek': 'На этой неделе',
      'notif.group.older': 'Ранее',
      'notif.rollup': '{{count}} похожих уведомлений',
      'notif.tech': 'Технические данные',
      'notif.truncated': 'Текст сокращён — полностью на странице источника',
      'notif.missingReason': 'Причина отклонения не указана в системе',
      'notif.noLink': 'Ссылка недоступна',
      'notif.noPermission': 'У вас нет прав для перехода по этой ссылке',
      'notif.contentUzOnly': 'Тексты уведомлений пока доступны только на узбекском',

      'notif.settings.title': 'Настройки уведомлений',
      'notif.settings.open': 'Настройки',
      'notif.settings.global': 'Общие',
      'notif.settings.pause': 'Приостановить уведомления',
      'notif.settings.pauseHint':
        'При включении новые уведомления не отправляются. Уже полученные не удаляются.',
      'notif.settings.digest': 'Сводка',
      'notif.settings.digestHint': 'Вместо отдельного письма по каждому событию отправляется одна сводка.',
      'notif.settings.digestEnable': 'Включить',
      'notif.settings.daily': 'Ежедневно',
      'notif.settings.weekly': 'Еженедельно',
      'notif.settings.channels': 'Каналы',
      'notif.settings.channelsHint':
        'Неотмеченное событие отправляется по системной настройке. После первого изменения сохраняется ваш выбор.',
      'notif.settings.systemDefault': 'системная настройка',
      'notif.settings.save': 'Сохранить',
      'notif.settings.cancel': 'Отмена',
      'notif.settings.saved': 'Настройки сохранены',
      'notif.channel.inApp': 'В системе',
      'notif.channel.telegram': 'Telegram',
      'notif.channel.email': 'Эл. почта',
      'notif.channel.sms': 'SMS',

      'notif.event.eriExpiring': 'Истекает срок сертификата ЭЦП',
      'notif.event.eriExpired': 'Срок сертификата ЭЦП истёк',
      'notif.event.slaOverdue': 'Просрочка по SLA',
      'notif.event.slaEscalated': 'Эскалация SLA',
      'notif.event.vacancyReassigned': 'Нагрузка переназначена',
      'notif.event.recalcRequired': 'Требуется пересчёт',
      'notif.event.residencyPlanReviewed': 'План рассмотрен',
      'notif.event.residencyAttendanceWarning': 'Предупреждение по посещаемости',
      'notif.event.residencyAttendanceWarningSupervisor': 'Предупреждение по посещаемости резидента',
      'notif.event.residencyExpulsion': 'Проект приказа об отчислении',
      'notif.event.residencyDailyLogReviewed': 'Дневник рассмотрен',
      'notif.event.residencyAnnouncementPublished': 'Новое объявление',
      'notif.event.residencyExpulsionDraftOffice': 'Проект приказа об отчислении (отдел)',
      'notif.event.residencyExpulsionSigned': 'Приказ об отчислении подписан',
      'notif.event.residencyExpulsionRejected': 'Проект приказа об отчислении отклонён',
      'notif.event.residencyExpulsionBasisLostOffice': 'Основание подписанного приказа ниже 72 часов',
      'notif.event.residencyAbsenceNoticeAuto': 'Уведомление о посещаемости (автоматическое)',
      'notif.event.residencySamsDigest': 'Посещаемость SAMS — ежедневная сводка',
      'notif.event.residencySamsTenantsChanged': 'Клиники SAMS изменились',
      'notif.event.taskAssigned': 'Задача назначена',
      'notif.event.taskDeadlineChanged': 'Срок задачи изменён',
      'notif.event.taskRejectedByExecutor': 'Задача отклонена исполнителем',
      'notif.event.taskSubmitted': 'Задача отправлена на проверку',
      'notif.event.taskCompleted': 'Задача выполнена',
      'notif.event.taskNotNeeded': 'Задача отменена',
      'notif.event.taskReopened': 'Задача возобновлена',
      'notif.event.announcementNew': 'Новое объявление',
      'notif.event.councilTaskOverdue': 'Задача совета просрочена',
      'notif.event.councilRankAccepted': 'Заявка на звание принята',
      'notif.event.councilRankReturned': 'Заявка на звание возвращена',
      'notif.event.councilVotingStarted': 'Голосование началось',
      'notif.event.councilVotingFinished': 'Голосование завершено',
      'notif.event.qualifyingApplicant': 'Обновление по заявке на повышение квалификации',
      'notif.event.scientificPost': 'Научная публикация',
      'notif.event.contractSentToRector': 'Договор отправлен ректору',
      'notif.event.contractRektorApproved': 'Договор утверждён ректором',
      'notif.event.contractBothApproved': 'Договор полностью утверждён',
      'notif.event.contractRejected': 'Договор отклонён',
      'notif.event.scienceWorkSubmitted': 'Подана новая научная работа',
      'notif.event.scienceWorkStatusChanged': 'Статус научной работы изменён',
      'notif.event.scienceDecisionMade': 'Принято итоговое решение',
      'notif.event.scienceSeminarResultSet': 'Результат семинара установлен',
      'notif.event.scienceReviewAdded': 'Добавлено новое заключение',
      'notif.event.scienceMemberAdded': 'Назначен членом совета',
      'notif.event.scienceMemberRemoved': 'Исключён из членов совета',
      'notif.event.scienceApplicationAccepted': 'Заявка принята',
      'notif.event.scienceApplicationRejected': 'Заявка отклонена',
      'notif.event.eqSubmissionCreated': 'Данные отправлены на проверку',
      'notif.event.eqSubmissionReviewed': 'Отправленные данные рассмотрены',

      'notif.mod.system': 'Система',
      'notif.mod.studyLoad': 'Учебная нагрузка',
      'notif.mod.residency': 'Резидентура',
      'notif.mod.task': 'Задачи',
      'notif.mod.council': 'Совет',
      'notif.mod.science': 'Научный отдел',
      'notif.mod.practice': 'Практика',
      'notif.mod.scienceCouncil': 'Научный совет',
      'notif.mod.qualityAssurance': 'Качество образования',
      'notif.mod.teacher': 'Профессорско-преподавательский состав',
      'notif.mod.unknown': 'Неизвестно',

      'notif.meta.workId': 'ID научной работы',
      'notif.meta.reviewId': 'ID заключения',
      'notif.meta.memberId': 'ID членства',
      'notif.meta.submissionId': 'ID данных',
      'notif.meta.indicatorId': 'ID индикатора',
      'notif.meta.serialNumber': 'Серийный номер',
      'notif.meta.daysLeft': 'Осталось дней',
      'notif.meta.totalUnexcusedHours': 'Часов без уважительной причины',
      'notif.meta.chainId': 'ID цепочки',
      'notif.meta.daysOverdue': 'Дней просрочено',
      'notif.meta.originalRole': 'Исходная роль',
      'notif.meta.distributionId': 'ID распределения',
      'notif.meta.entryId': 'ID записи',
      'notif.meta.previousTeacher': 'Предыдущий преподаватель',
      'notif.meta.groupId': 'ID группы',
      'notif.meta.oldCount': 'Старое количество',
      'notif.meta.newCount': 'Новое количество',
      'notif.meta.affectedWorkloads': 'Затронутые нагрузки',
      'notif.meta.taskId': 'ID задачи',
      'notif.meta.announcementId': 'ID объявления',
      'notif.meta.applicationId': 'ID заявки',
      'notif.meta.sessionId': 'ID сессии',
      'notif.meta.applicantId': 'ID заявителя',
      'notif.meta.postId': 'ID поста',
      'notif.meta.specialtyCode': 'Код специальности',
      'notif.meta.contractId': 'ID договора',
      'notif.meta.planId': 'ID индивидуального плана',
      'notif.meta.reportId': 'ID отчёта',
      'notif.meta.profileId': 'ID профиля',
      'notif.meta.leaveId': 'ID заявления',
      'notif.meta.orderId': 'ID приказа',
      'notif.meta.residentId': 'ID резидента',
      'notif.meta.reminderStage': 'Этап напоминания',
      'notif.meta.noticeId': 'ID уведомления',
      'notif.meta.digestDay': 'День сводки',
      'notif.meta.arrayCount': '{{count}} шт.',
    },
    en: {
      'notif.title': 'Notifications',
      'notif.refresh': 'Refresh',
      'notif.viewAll': 'View all',
      'notif.markAll': 'Mark all as read',
      'notif.markAllConfirm.title': 'Mark all as read?',
      'notif.markAllConfirm.desc': 'This action cannot be undone.',
      'notif.markAllConfirm.ok': 'Yes',
      'notif.markAllConfirm.cancel': 'Cancel',
      'notif.markOne': 'Mark as read',
      'notif.detail': 'Details',
      'notif.copy': 'Copy',
      'notif.copied': 'Copied',
      'notif.more': 'More',
      'notif.less': 'Less',
      'notif.empty.title': 'No notifications',
      'notif.empty.hint': 'New notifications will appear here',
      'notif.error.title': 'Failed to load notifications',
      'notif.retry': 'Retry',
      'notif.offline': 'Offline — last updated {{time}}',
      'notif.offlineNoData': 'Offline — no data loaded yet',
      'notif.badge.stale': 'Count not updated',
      'notif.bell.aria': 'Notifications, {{count}} unread',
      'notif.bell.empty': 'Notifications, none unread',
      'notif.unread': 'unread',
      'notif.tab.all': 'All',
      'notif.tab.unread': 'Unread',
      'notif.filter.type': 'By type',
      'notif.group.today': 'Today',
      'notif.group.yesterday': 'Yesterday',
      'notif.group.thisWeek': 'This week',
      'notif.group.older': 'Older',
      'notif.rollup': '{{count}} similar notifications',
      'notif.tech': 'Technical details',
      'notif.truncated': 'Text truncated — full version on the source page',
      'notif.missingReason': 'The rejection reason is not recorded in the system',
      'notif.noLink': 'Link unavailable',
      'notif.noPermission': "You don't have permission to open this link",
      'notif.contentUzOnly': 'Notification text is currently available in Uzbek only',

      'notif.settings.title': 'Notification settings',
      'notif.settings.open': 'Settings',
      'notif.settings.global': 'General',
      'notif.settings.pause': 'Pause notifications',
      'notif.settings.pauseHint':
        'When enabled, no new notifications are sent. Existing ones are not deleted.',
      'notif.settings.digest': 'Digest',
      'notif.settings.digestHint': 'One combined message instead of a separate one per event.',
      'notif.settings.digestEnable': 'Enable',
      'notif.settings.daily': 'Daily',
      'notif.settings.weekly': 'Weekly',
      'notif.settings.channels': 'Channels',
      'notif.settings.channelsHint':
        'An unset event follows the system default. Once you change it, your choice is kept.',
      'notif.settings.systemDefault': 'system default',
      'notif.settings.save': 'Save',
      'notif.settings.cancel': 'Cancel',
      'notif.settings.saved': 'Settings saved',
      'notif.channel.inApp': 'In app',
      'notif.channel.telegram': 'Telegram',
      'notif.channel.email': 'Email',
      'notif.channel.sms': 'SMS',

      'notif.event.eriExpiring': 'ERI certificate expiring soon',
      'notif.event.eriExpired': 'ERI certificate expired',
      'notif.event.slaOverdue': 'SLA overdue',
      'notif.event.slaEscalated': 'SLA escalated',
      'notif.event.vacancyReassigned': 'Workload reassigned',
      'notif.event.recalcRequired': 'Recalculation required',
      'notif.event.residencyPlanReviewed': 'Plan reviewed',
      'notif.event.residencyAttendanceWarning': 'Attendance warning',
      'notif.event.residencyAttendanceWarningSupervisor': "Resident's attendance warning",
      'notif.event.residencyExpulsion': 'Expulsion order draft',
      'notif.event.residencyDailyLogReviewed': 'Daily log reviewed',
      'notif.event.residencyAnnouncementPublished': 'New announcement',
      'notif.event.residencyExpulsionDraftOffice': 'Expulsion order draft (office)',
      'notif.event.residencyExpulsionSigned': 'Expulsion order signed',
      'notif.event.residencyExpulsionRejected': 'Expulsion order draft rejected',
      'notif.event.residencyExpulsionBasisLostOffice': 'Signed order basis fell below 72 hours',
      'notif.event.residencyAbsenceNoticeAuto': 'Attendance notice (automatic)',
      'notif.event.residencySamsDigest': 'SAMS attendance — daily digest',
      'notif.event.residencySamsTenantsChanged': 'SAMS clinics changed',
      'notif.event.taskAssigned': 'Task assigned',
      'notif.event.taskDeadlineChanged': 'Task deadline changed',
      'notif.event.taskRejectedByExecutor': 'Task rejected by executor',
      'notif.event.taskSubmitted': 'Task submitted',
      'notif.event.taskCompleted': 'Task completed',
      'notif.event.taskNotNeeded': 'Task not needed',
      'notif.event.taskReopened': 'Task reopened',
      'notif.event.announcementNew': 'New announcement',
      'notif.event.councilTaskOverdue': 'Council task overdue',
      'notif.event.councilRankAccepted': 'Rank application accepted',
      'notif.event.councilRankReturned': 'Rank application returned',
      'notif.event.councilVotingStarted': 'Voting started',
      'notif.event.councilVotingFinished': 'Voting finished',
      'notif.event.qualifyingApplicant': 'Qualification applicant update',
      'notif.event.scientificPost': 'Scientific post',
      'notif.event.contractSentToRector': 'Contract sent to rector',
      'notif.event.contractRektorApproved': 'Contract approved by rector',
      'notif.event.contractBothApproved': 'Contract fully approved',
      'notif.event.contractRejected': 'Contract rejected',
      'notif.event.scienceWorkSubmitted': 'New scientific work submitted',
      'notif.event.scienceWorkStatusChanged': 'Scientific work status changed',
      'notif.event.scienceDecisionMade': 'Final decision made',
      'notif.event.scienceSeminarResultSet': 'Seminar result set',
      'notif.event.scienceReviewAdded': 'New review added',
      'notif.event.scienceMemberAdded': 'Added as council member',
      'notif.event.scienceMemberRemoved': 'Removed from council membership',
      'notif.event.scienceApplicationAccepted': 'Application accepted',
      'notif.event.scienceApplicationRejected': 'Application rejected',
      'notif.event.eqSubmissionCreated': 'Data submitted for verification',
      'notif.event.eqSubmissionReviewed': 'Submitted data reviewed',

      'notif.mod.system': 'System',
      'notif.mod.studyLoad': 'Study load',
      'notif.mod.residency': 'Residency',
      'notif.mod.task': 'Tasks',
      'notif.mod.council': 'Council',
      'notif.mod.science': 'Science dept',
      'notif.mod.practice': 'Practice',
      'notif.mod.scienceCouncil': 'Science council',
      'notif.mod.qualityAssurance': 'Education quality',
      'notif.mod.teacher': 'Teaching staff',
      'notif.mod.unknown': 'Unknown',

      'notif.meta.workId': 'Work ID',
      'notif.meta.reviewId': 'Review ID',
      'notif.meta.memberId': 'Membership ID',
      'notif.meta.submissionId': 'Submission ID',
      'notif.meta.indicatorId': 'Indicator ID',
      'notif.meta.serialNumber': 'Serial number',
      'notif.meta.daysLeft': 'Days left',
      'notif.meta.totalUnexcusedHours': 'Unexcused hours',
      'notif.meta.chainId': 'Chain ID',
      'notif.meta.daysOverdue': 'Days overdue',
      'notif.meta.originalRole': 'Original role',
      'notif.meta.distributionId': 'Distribution ID',
      'notif.meta.entryId': 'Entry ID',
      'notif.meta.previousTeacher': 'Previous teacher',
      'notif.meta.groupId': 'Group ID',
      'notif.meta.oldCount': 'Old count',
      'notif.meta.newCount': 'New count',
      'notif.meta.affectedWorkloads': 'Affected workloads',
      'notif.meta.taskId': 'Task ID',
      'notif.meta.announcementId': 'Announcement ID',
      'notif.meta.applicationId': 'Application ID',
      'notif.meta.sessionId': 'Session ID',
      'notif.meta.applicantId': 'Applicant ID',
      'notif.meta.postId': 'Post ID',
      'notif.meta.specialtyCode': 'Specialty code',
      'notif.meta.contractId': 'Contract ID',
      'notif.meta.planId': 'Work plan ID',
      'notif.meta.reportId': 'Report ID',
      'notif.meta.profileId': 'Profile ID',
      'notif.meta.leaveId': 'Leave request ID',
      'notif.meta.orderId': 'Order ID',
      'notif.meta.residentId': 'Resident ID',
      'notif.meta.reminderStage': 'Reminder stage',
      'notif.meta.noticeId': 'Notice ID',
      'notif.meta.digestDay': 'Digest day',
      'notif.meta.arrayCount': '{{count}} items',
    },
  },
});
