import { lazy } from 'react';
import {
  BankOutlined,
  FileTextOutlined,
  SettingOutlined,
  TeamOutlined,
} from '@ant-design/icons';
import { Navigate } from 'react-router-dom';
import { defineModule } from '@/shared/lib/module';

const NotificationsRedirect = () => <Navigate to="/bildirishnomalar" replace />;

export default defineModule({
  name: 'practice',
  menuGroup: { titleKey: 'menuGroup.practice', order: 40 },
  basePath: '/amaliyot',
  routes: [
    { index: true, element: lazy(() => import('./pages/landing-page')) },
    { path: 'bazalar', permission: 'medicalOrganization:readAll', element: lazy(() => import('./pages/bazalar-page')) },
    { path: 'talabalar', permission: 'practiceStudent:readAll', element: lazy(() => import('./pages/talabalar-page')) },
    { path: 'shartnomalar', permission: 'practice:readAll', element: lazy(() => import('./pages/shartnomalar-page')) },
    { path: 'shartnomalar/yangi', permission: 'practice:create', element: lazy(() => import('./pages/shartnoma-form-page')) },
    { path: 'shartnomalar/shablon', permission: 'practice:update', element: lazy(() => import('./pages/shartnoma-shablon-page')) },
    { path: 'shartnomalar/:id', permission: 'practice:read', element: lazy(() => import('./pages/shartnoma-detail-page')) },
    { path: 'shartnomalar/:id/tahrirlash', permission: 'practice:update', element: lazy(() => import('./pages/shartnoma-form-page')) },
    { path: 'bildirishnomalar', element: NotificationsRedirect },
    { path: 'sozlamalar/tashkilot-turlari', permission: 'orgType:create', element: lazy(() => import('./pages/sozlamalar/org-types-page')) },
    { path: 'sozlamalar/viloyatlar', permission: 'province:create', element: lazy(() => import('./pages/sozlamalar/regions-page')) },
    { path: 'sozlamalar/tumanlar', permission: 'region:create', element: lazy(() => import('./pages/sozlamalar/districts-page')) },
    { path: 'sozlamalar/oquv-yillari', permission: 'academicYear:create', element: lazy(() => import('./pages/sozlamalar/academic-years-page')) },
    { path: 'sozlamalar/kurslar', permission: 'course:create', element: lazy(() => import('./pages/sozlamalar/courses-page')) },
  ],
  menu: [
    { titleKey: 'practice.nav.bases', icon: <BankOutlined />, path: '/amaliyot/bazalar', order: 41, permission: 'medicalOrganization:readAll' },
    { titleKey: 'practice.nav.students', icon: <TeamOutlined />, path: '/amaliyot/talabalar', order: 42, permission: 'practiceStudent:readAll' },
    { titleKey: 'practice.nav.contracts', icon: <FileTextOutlined />, path: '/amaliyot/shartnomalar', order: 43, permission: 'practice:readAll' },
    { titleKey: 'practice.nav.settings', icon: <SettingOutlined />, path: '/amaliyot/sozlamalar', order: 47, permission: 'orgType:create' },
    { titleKey: 'practice.nav.orgTypes', path: '/amaliyot/sozlamalar/tashkilot-turlari', parent: '/amaliyot/sozlamalar', order: 1, permission: 'orgType:create' },
    { titleKey: 'practice.nav.regions', path: '/amaliyot/sozlamalar/viloyatlar', parent: '/amaliyot/sozlamalar', order: 2, permission: 'province:create' },
    { titleKey: 'practice.nav.districts', path: '/amaliyot/sozlamalar/tumanlar', parent: '/amaliyot/sozlamalar', order: 3, permission: 'region:create' },
    { titleKey: 'practice.nav.years', path: '/amaliyot/sozlamalar/oquv-yillari', parent: '/amaliyot/sozlamalar', order: 4, permission: 'academicYear:create' },
    { titleKey: 'practice.nav.courses', path: '/amaliyot/sozlamalar/kurslar', parent: '/amaliyot/sozlamalar', order: 5, permission: 'course:create' },
  ],
  i18n: {
    uz: {
      'menuGroup.practice': 'Amaliyot',
      'practice.nav.bases': 'Amaliyot bazalari',
      'practice.nav.students': 'Talabalar',
      'practice.nav.contracts': 'Shartnomalar',
      'practice.nav.notifications': 'Bildirishnomalar',
      'practice.nav.settings': 'Sozlamalar',
      'practice.nav.orgTypes': 'Tashkilot turlari',
      'practice.nav.regions': 'Viloyatlar',
      'practice.nav.districts': 'Shahar / Tumanlar',
      'practice.nav.years': "O'quv yillari",
      'practice.nav.courses': 'Kurslar',
    },
    ru: {
      'menuGroup.practice': 'Практика',
      'practice.nav.bases': 'Базы практики',
      'practice.nav.students': 'Студенты',
      'practice.nav.contracts': 'Договоры',
      'practice.nav.notifications': 'Уведомления',
      'practice.nav.settings': 'Настройки',
      'practice.nav.orgTypes': 'Типы организаций',
      'practice.nav.regions': 'Области',
      'practice.nav.districts': 'Города / Районы',
      'practice.nav.years': 'Учебные годы',
      'practice.nav.courses': 'Курсы',
    },
    en: {
      'menuGroup.practice': 'Practice',
      'practice.nav.bases': 'Practice bases',
      'practice.nav.students': 'Students',
      'practice.nav.contracts': 'Contracts',
      'practice.nav.notifications': 'Notifications',
      'practice.nav.settings': 'Settings',
      'practice.nav.orgTypes': 'Organization types',
      'practice.nav.regions': 'Regions',
      'practice.nav.districts': 'Cities / Districts',
      'practice.nav.years': 'Academic years',
      'practice.nav.courses': 'Courses',
    },
  },
  permissions: [
    { key: 'medicalOrganization:create', description: 'Amaliyot bazasi yaratish' },
    { key: 'medicalOrganization:read', description: 'Amaliyot bazasini ko‘rish' },
    { key: 'medicalOrganization:readAll', description: 'Amaliyot bazalari ro‘yxati' },
    { key: 'medicalOrganization:update', description: 'Amaliyot bazasini tahrirlash' },
    { key: 'medicalOrganization:delete', description: 'Amaliyot bazasini o‘chirish' },
    { key: 'practiceStudent:create', description: 'Talaba qo‘shish' },
    { key: 'practiceStudent:read', description: 'Talabani ko‘rish' },
    { key: 'practiceStudent:readAll', description: 'Talabalar ro‘yxati' },
    { key: 'practiceStudent:update', description: 'Talabani tahrirlash / kurs o‘tkazish' },
    { key: 'practiceStudent:delete', description: 'Talabani o‘chirish' },
    { key: 'practice:create', description: 'Shartnoma yaratish' },
    { key: 'practice:read', description: 'Shartnomani ko‘rish' },
    { key: 'practice:readAll', description: 'Shartnomalar ro‘yxati' },
    { key: 'practice:update', description: 'Shartnomani tahrirlash' },
    { key: 'practice:delete', description: 'Shartnomani o‘chirish' },
    { key: 'practice:changeStatus', description: 'Rektorga yuborish' },
    { key: 'practice:sign', description: 'ERI bilan imzolash' },
    { key: 'practice:reject', description: 'Shartnomani rad etish' },
    { key: 'practice:export', description: 'Shartnomani yuklab olish / eksport' },
    { key: 'notification:read', description: 'Bildirishnomani ko‘rish' },
    { key: 'notification:readAll', description: 'Bildirishnomalar feed' },
    { key: 'notification:update', description: 'O‘qilgan deb belgilash' },
    { key: 'notification:delete', description: 'Bildirishnomani o‘chirish' },
    { key: 'orgType:create', description: 'Tashkilot turi yaratish' },
    { key: 'orgType:read', description: 'Tashkilot turini ko‘rish' },
    { key: 'orgType:readAll', description: 'Tashkilot turlari ro‘yxati' },
    { key: 'orgType:update', description: 'Tashkilot turini tahrirlash' },
    { key: 'orgType:delete', description: 'Tashkilot turini o‘chirish' },
    { key: 'province:create', description: 'Viloyat yaratish' },
    { key: 'province:read', description: 'Viloyatni ko‘rish' },
    { key: 'province:readAll', description: 'Viloyatlar ro‘yxati' },
    { key: 'province:update', description: 'Viloyatni tahrirlash' },
    { key: 'province:delete', description: 'Viloyatni o‘chirish' },
    { key: 'region:create', description: 'Shahar / tuman yaratish' },
    { key: 'region:read', description: 'Shahar / tumanni ko‘rish' },
    { key: 'region:readAll', description: 'Shahar / tumanlar ro‘yxati' },
    { key: 'region:update', description: 'Shahar / tumanni tahrirlash' },
    { key: 'region:delete', description: 'Shahar / tumanni o‘chirish' },
  ],
});
