import { lazy } from 'react';
import {
  ApartmentOutlined,
  BarChartOutlined,
  CalendarOutlined,
  FileTextOutlined,
  FlagOutlined,
  GlobalOutlined,
  MailOutlined,
  ReadOutlined,
  ScheduleOutlined,
  TranslationOutlined,
} from '@ant-design/icons';
import { defineModule } from '@/shared/lib/module';

export default defineModule({
  name: 'foreign-admission',
  menuGroup: { titleKey: 'menuGroup.foreignAdmission', order: 90 },
  routes: [
    { index: true, permission: 'internationalAdmission:readAll', element: lazy(() => import('./pages/index-redirect')) },
    { path: 'dashboard', permission: 'internationalAdmission:readAll', element: lazy(() => import('./pages/dashboard-page')) },
    { path: 'applications', permission: 'internationalAdmission:readAll', element: lazy(() => import('./pages/admin-list-page')) },
    { path: 'applications/:id', permission: 'internationalAdmission:read', element: lazy(() => import('./pages/admin-detail-page')) },

    { path: 'messages', permission: 'admissionMessage:readAll', element: lazy(() => import('./pages/messages-page')) },
    { path: 'seasons', permission: 'admissionSeason:readAll', element: lazy(() => import('./pages/seasons-page')) },

    { path: 'directions', permission: 'admissionDirection:readAll', element: lazy(() => import('./pages/directions-page')) },
    { path: 'education-forms', permission: 'admissionEducationForm:readAll', element: lazy(() => import('./pages/education-forms-page')) },
    { path: 'education-languages', permission: 'admissionEducationLanguage:readAll', element: lazy(() => import('./pages/education-languages-page')) },
    { path: 'countries', permission: 'admissionCountry:readAll', element: lazy(() => import('./pages/countries-page')) },
    { path: 'offer', permission: 'admissionOffer:readAll', element: lazy(() => import('./pages/offer-page')) },
  ],
  menu: [
    { titleKey: 'foreignAdmission.nav.dashboard', icon: <BarChartOutlined />, path: '/foreign-admission/dashboard', order: 50, permission: 'internationalAdmission:readAll' },
    { titleKey: 'foreignAdmission.nav.applications', icon: <GlobalOutlined />, path: '/foreign-admission/applications', order: 51, permission: 'internationalAdmission:readAll' },
    { titleKey: 'foreignAdmission.nav.messages', icon: <MailOutlined />, path: '/foreign-admission/messages', order: 52, permission: 'admissionMessage:readAll' },
    { titleKey: 'foreignAdmission.nav.seasons', icon: <CalendarOutlined />, path: '/foreign-admission/seasons', order: 53, permission: 'admissionSeason:readAll' },

    { titleKey: 'foreignAdmission.nav.structure', icon: <ApartmentOutlined />, path: '/foreign-admission/structure', order: 54, permission: 'admissionDirection:readAll' },
    { titleKey: 'foreignAdmission.nav.directions', icon: <ReadOutlined />, path: '/foreign-admission/directions', parent: '/foreign-admission/structure', order: 1, permission: 'admissionDirection:readAll' },
    { titleKey: 'foreignAdmission.nav.educationForms', icon: <ScheduleOutlined />, path: '/foreign-admission/education-forms', parent: '/foreign-admission/structure', order: 2, permission: 'admissionEducationForm:readAll' },
    { titleKey: 'foreignAdmission.nav.educationLanguages', icon: <TranslationOutlined />, path: '/foreign-admission/education-languages', parent: '/foreign-admission/structure', order: 3, permission: 'admissionEducationLanguage:readAll' },
    { titleKey: 'foreignAdmission.nav.countries', icon: <FlagOutlined />, path: '/foreign-admission/countries', parent: '/foreign-admission/structure', order: 4, permission: 'admissionCountry:readAll' },
    { titleKey: 'foreignAdmission.nav.offer', icon: <FileTextOutlined />, path: '/foreign-admission/offer', parent: '/foreign-admission/structure', order: 5, permission: 'admissionOffer:readAll' },
  ],
  i18n: {
    uz: {
      'menuGroup.foreignAdmission': 'Xorijiy qabul',
      'foreignAdmission.nav.dashboard': 'Statistika',
      'foreignAdmission.nav.applications': 'Arizalar',
      'foreignAdmission.nav.messages': 'Xabarlar',
      'foreignAdmission.nav.seasons': 'Qabul',
      'foreignAdmission.nav.structure': "Ta'lim tuzilmasi",
      'foreignAdmission.nav.directions': "Yoʻnalishlar",
      'foreignAdmission.nav.educationForms': "Taʼlim shakli",
      'foreignAdmission.nav.educationLanguages': "Taʼlim tili",
      'foreignAdmission.nav.countries': 'Davlatlar',
      'foreignAdmission.nav.offer': 'Ommaviy oferta',
      'foreignAdmission.cancel': 'Bekor qilish',
      'foreignAdmission.save': 'Saqlash',
      'foreignAdmission.close': 'Yopish',
      'foreignAdmission.err.required': 'Majburiy maydon',
      'foreignAdmission.view': 'Koʻrish',
      'foreignAdmission.total': 'Jami',
      'foreignAdmission.crud.created': "Yangi yozuv qoʻshildi",
      'foreignAdmission.crud.updated': 'Saqlandi',
      'foreignAdmission.crud.deleted': "Oʻchirildi",
      'foreignAdmission.crud.delete': "Oʻchirish",
      'foreignAdmission.crud.delete_warning': "bu amalni qaytarib boʻlmaydi.",
      'foreignAdmission.col.id': 'Ariza raqami',
      'foreignAdmission.col.name': 'F.I.SH',
      'foreignAdmission.col.country': 'Davlat',
      'foreignAdmission.col.direction': 'Yoʻnalish',
      'foreignAdmission.col.created': 'Sana',
      'foreignAdmission.col.status': 'Status',
      'foreignAdmission.col.actions': 'Amallar',
      'foreignAdmission.filters.search_ph': 'F.I.SH boʻyicha qidirish',
      'foreignAdmission.filters.country_ph': 'Barcha davlatlar',
      'foreignAdmission.filters.status_ph': 'Barcha holatlar',
      'foreignAdmission.filters.rangeFrom': '...dan',
      'foreignAdmission.filters.rangeTo': '...gacha',
      'foreignAdmission.status.yangi': 'Yangi',
      'foreignAdmission.status.tasdiqlangan': 'Tasdiqlangan',
      'foreignAdmission.status.radEtilgan': 'Rad etilgan',
      'foreignAdmission.section.profile': 'Shaxsiy maʼlumotlar',
      'foreignAdmission.section.education': 'Taʼlim maʼlumotlari',
      'foreignAdmission.section.documents': 'Yuklangan hujjatlar',
      'foreignAdmission.field.full_name': 'F.I.SH',
      'foreignAdmission.field.birth_date': 'Tugʻilgan sana',
      'foreignAdmission.field.country': 'Fuqaroligi',
      'foreignAdmission.field.phone': 'Telefon raqam',
      'foreignAdmission.field.parent_phone': 'Ota-onasining telefon raqami',
      'foreignAdmission.field.passport_number': 'Pasport seriyasi va raqami',
      'foreignAdmission.field.passport_expiry': 'Pasport muddati',
      'foreignAdmission.field.email': 'Email',
      'foreignAdmission.field.direction': 'Yoʻnalish',
      'foreignAdmission.field.academic_year': 'Oʻquv yili',
      'foreignAdmission.docs.view': 'Koʻrish',
      'foreignAdmission.docs.empty': 'Hujjat yuklanmagan',
      'foreignAdmission.docs.slot.passport': 'Pasport nusxasi',
      'foreignAdmission.docs.slot.diploma': 'Diplom / Shahodatnoma',
      'foreignAdmission.docs.slot.certificate': 'Sertifikat',
      'foreignAdmission.docs.download': 'Yuklab olish',
      'foreignAdmission.detail.back': 'Orqaga',
      'foreignAdmission.detail.title': 'Ariza',
      'foreignAdmission.detail.print': 'Chop etish',
      'foreignAdmission.detail.until': 'gacha',
      'foreignAdmission.detail.submitted_at': 'Ariza sanasi',
      'foreignAdmission.detail.not_found': 'Ariza topilmadi',
      'foreignAdmission.action.approve': 'Tasdiqlash',
      'foreignAdmission.action.reject': 'Qaytarish',
      'foreignAdmission.approve.confirm_title': 'Arizani tasdiqlaysizmi?',
      'foreignAdmission.approve.done': 'Ariza tasdiqlandi',
      'foreignAdmission.reject.title': 'Arizani qaytarish',
      'foreignAdmission.reject.reason': 'Qaytarish sababi',
      'foreignAdmission.reject.reason_ph': 'Ariza qaytarilishining batafsil sababini yozing',
      'foreignAdmission.reject.reason_min': 'Sabab kamida 10 belgi boʻlishi kerak',
      'foreignAdmission.reject.done': 'Ariza qaytarildi',
      'foreignAdmission.kpi.total': 'Jami arizalar',
      'foreignAdmission.kpi.yangi': 'Koʻrib chiqilmoqda',
      'foreignAdmission.kpi.tasdiqlangan': 'Qabul qilinganlar',
      'foreignAdmission.kpi.radEtilgan': 'Rad etilganlar',
      'foreignAdmission.export.excel': 'Excelga eksport (.xlsx)',
      'foreignAdmission.export.metric': "Ko'rsatkich",
      'foreignAdmission.export.value': 'Qiymat',
      'foreignAdmission.export.name': 'Nomi',
      'foreignAdmission.export.count': 'Soni',
      'foreignAdmission.export.sheetKpi': "Asosiy ko'rsatkichlar",
      'foreignAdmission.export.sheetDirection': "Yo'nalishlar",
      'foreignAdmission.export.sheetMonth': 'Oylar',
      'foreignAdmission.export.sheetCountry': 'Davlatlar',
      'foreignAdmission.chart.by_direction': "Yoʻnalishlar boʻyicha koʻrsatkichlar",
      'foreignAdmission.chart.by_country': 'Davlatlar kesimida',
      'foreignAdmission.chart.by_month': 'Vaqt kesimida',
      'foreignAdmission.directions.name': "Yoʻnalish nomi",
      'foreignAdmission.directions.name_ph': 'Masalan: Davolash ishi',
      'foreignAdmission.directions.new': "Yangi yoʻnalish",
      'foreignAdmission.directions.create': "Yoʻnalish qoʻshish",
      'foreignAdmission.directions.edit': "Yoʻnalishni tahrirlash",
      'foreignAdmission.directions.search_ph': "Yoʻnalish nomi boʻyicha qidirish",
      'foreignAdmission.directions.delete_title': "Yoʻnalishni oʻchirish",
      'foreignAdmission.eduForms.name': "Taʼlim shakli",
      'foreignAdmission.eduForms.name_ph': 'Masalan: Kunduzgi',
      'foreignAdmission.eduForms.desc': 'Izoh',
      'foreignAdmission.eduForms.desc_ph': "Taʼlim shakli haqida qisqacha izoh",
      'foreignAdmission.eduForms.new': "Yangi taʼlim shakli",
      'foreignAdmission.eduForms.create': "Taʼlim shakli qoʻshish",
      'foreignAdmission.eduForms.edit': "Taʼlim shaklini tahrirlash",
      'foreignAdmission.eduForms.search_ph': "Taʼlim shakli boʻyicha qidirish",
      'foreignAdmission.eduForms.delete_title': "Taʼlim shaklini oʻchirish",
      'foreignAdmission.eduLangs.name': "Taʼlim tili",
      'foreignAdmission.eduLangs.name_ph': "Masalan: Oʻzbek",
      'foreignAdmission.eduLangs.new': "Yangi taʼlim tili",
      'foreignAdmission.eduLangs.create': "Taʼlim tili qoʻshish",
      'foreignAdmission.eduLangs.edit': "Taʼlim tilini tahrirlash",
      'foreignAdmission.eduLangs.search_ph': "Taʼlim tili boʻyicha qidirish",
      'foreignAdmission.eduLangs.delete_title': "Taʼlim tilini oʻchirish",
      'foreignAdmission.countries.name': 'Davlat nomi',
      'foreignAdmission.countries.name_ph': "Masalan: Qozogʻiston",
      'foreignAdmission.countries.flag': 'Bayroq',
      'foreignAdmission.countries.flag_hint': 'Bayroqni yuklang',
      'foreignAdmission.countries.passport': 'Pasport namunasi',
      'foreignAdmission.countries.passport_ph': 'AB0000000',
      'foreignAdmission.countries.phone': 'Telefon namunasi',
      'foreignAdmission.countries.phone_ph': '+998 90 123-45-67',
      'foreignAdmission.countries.new': 'Yangi davlat',
      'foreignAdmission.countries.create': "Davlat qoʻshish",
      'foreignAdmission.countries.edit': 'Davlatni tahrirlash',
      'foreignAdmission.countries.search_ph': "Davlat nomi boʻyicha qidirish",
      'foreignAdmission.countries.delete_title': "Davlatni oʻchirish",
      'foreignAdmission.offer.block_title': 'Sarlavha',
      'foreignAdmission.offer.title_ph': 'Oferta nomini yozing',
      'foreignAdmission.offer.body': 'Izoh',
      'foreignAdmission.offer.body_ph': 'Oferta sharti haqida yozing',
      'foreignAdmission.offer.add': "Qoʻshish",
      'foreignAdmission.offer.saved': 'Oferta saqlandi',
      'foreignAdmission.offer.delete_title': "Oferta blokini oʻchirish",
      'foreignAdmission.offer.min_one': 'Kamida 1 ta blok qolishi kerak',
      'foreignAdmission.offer.empty': "Hech boʻlmasa bitta blok toʻldiring",
      'foreignAdmission.offer.uz_required': "Har blokning oʻzbekcha sarlavhasi majburiy",
      'foreignAdmission.seasons.title': 'Sarlavha',
      'foreignAdmission.seasons.title_ph': 'Qabul sarlavhasi',
      'foreignAdmission.seasons.description': 'Izoh',
      'foreignAdmission.seasons.description_ph': 'Qabul haqida qisqacha izoh',
      'foreignAdmission.seasons.season': 'Mavsum',
      'foreignAdmission.seasons.season_ph': 'Mavsumni tanlang',
      'foreignAdmission.seasons.date_ph': 'Sanani tanlang',
      'foreignAdmission.seasons.season_all': 'Barcha mavsum',
      'foreignAdmission.seasons.year_ph': "Oʻquv yilini tanlang yoki yozing",
      'foreignAdmission.seasons.year_format': "Format: 2025/2026",
      'foreignAdmission.seasons.year_all': "Barcha oʻquv yili",
      'foreignAdmission.seasons.open_date': 'Qabul ochilishi',
      'foreignAdmission.seasons.close_date': 'Qabul yopilishi',
      'foreignAdmission.seasons.direction': "Yoʻnalish",
      'foreignAdmission.seasons.direction_ph': "Yoʻnalishni tanlang",
      'foreignAdmission.seasons.forms_ph': "Taʼlim shaklini tanlang",
      'foreignAdmission.seasons.langs_ph': "Taʼlim tilini tanlang",
      'foreignAdmission.seasons.add_direction': "Yoʻnalish qoʻshish",
      'foreignAdmission.seasons.new': 'Yangi qabul vaqti',
      'foreignAdmission.seasons.create': 'Qabul ochish',
      'foreignAdmission.seasons.edit': 'Qabulni tahrirlash',
      'foreignAdmission.seasons.view': "Qabul mavsumi (koʻrish)",
      'foreignAdmission.seasons.created': "Yangi qabul mavsumi qoʻshildi",
      'foreignAdmission.seasons.search_ph': 'Sarlavha boʻyicha qidirish',
      'foreignAdmission.seasons.delete_title': "Qabul mavsumini oʻchirish",
      'foreignAdmission.seasons.date_order': "Yopilish sanasi ochilish sanasidan keyin boʻlishi kerak",
      'foreignAdmission.seasons.close_title': 'Qabulni yopasizmi?',
      'foreignAdmission.seasons.close_warning': "Yopilgandan soʻng mavsum tahrirlanmaydi va qayta ochilmaydi.",
      'foreignAdmission.seasons.close_ok': 'Qabulni yopish',
      'foreignAdmission.seasons.closed': 'Qabul mavsumi yopildi',
      'foreignAdmission.season.bahor': 'Bahor',
      'foreignAdmission.season.yoz': 'Yoz',
      'foreignAdmission.season.kuz': 'Kuz',
      'foreignAdmission.season.qish': 'Qish',
      'foreignAdmission.seasonStatus.rejada': 'Rejada',
      'foreignAdmission.seasonStatus.ochiq': 'Ochiq',
      'foreignAdmission.seasonStatus.yopiq': 'Yopiq',
      'foreignAdmission.messages.text': 'Xabar matni',
      'foreignAdmission.messages.text_ph': 'Xabar matnini kiriting',
      'foreignAdmission.messages.send': 'Xabar yuborish',
      'foreignAdmission.messages.send_ok': 'Yuborish',
      'foreignAdmission.messages.search_ph': 'Xabar matni boʻyicha qidirish',
      'foreignAdmission.messages.direction_all': 'Barcha yoʻnalishlar',
      'foreignAdmission.messages.lang_all': 'Barcha tillar',
      'foreignAdmission.messages.info': 'Arizasi tasdiqlangan abituriyentlarga yuboriladi.',
      'foreignAdmission.messages.counting': 'Qabul qiluvchilar hisoblanmoqda...',
      'foreignAdmission.messages.recipients': 'Hozirgi filtr boʻyicha: {{n}} ta abituriyent',
      'foreignAdmission.messages.confirm_title': 'Xabar yuborilsinmi?',
      'foreignAdmission.messages.confirm_body': "{{n}} ta abituriyentning elektron manziliga xabar yuboriladi. Bu amalni qaytarib boʻlmaydi.",
      'foreignAdmission.messages.confirm_ok': 'Tasdiqlash',
      'foreignAdmission.messages.sent': 'Xabar yuborildi ({{delivered}}/{{total}})',
      'foreignAdmission.messages.delivered': 'Yetkazildi',
      'foreignAdmission.messages.export': 'Excelga yuklash',
      'foreignAdmission.messages.export_empty': 'Eksport uchun maʼlumot yoʻq',
    },
    en: {
      'menuGroup.foreignAdmission': 'Foreign admission',
      'foreignAdmission.nav.dashboard': 'Statistics',
      'foreignAdmission.nav.applications': 'Applications',
      'foreignAdmission.nav.messages': 'Messages',
      'foreignAdmission.nav.seasons': 'Admission',
      'foreignAdmission.nav.structure': 'Education structure',
      'foreignAdmission.nav.directions': 'Directions',
      'foreignAdmission.nav.educationForms': 'Education forms',
      'foreignAdmission.nav.educationLanguages': 'Languages',
      'foreignAdmission.nav.countries': 'Countries',
      'foreignAdmission.nav.offer': 'Public offer',
      'foreignAdmission.cancel': 'Cancel',
      'foreignAdmission.save': 'Save',
      'foreignAdmission.close': 'Close',
      'foreignAdmission.err.required': 'Required',
      'foreignAdmission.view': 'View',
      'foreignAdmission.total': 'Total',
      'foreignAdmission.crud.created': 'Record created',
      'foreignAdmission.crud.updated': 'Saved',
      'foreignAdmission.crud.deleted': 'Deleted',
      'foreignAdmission.crud.delete': 'Delete',
      'foreignAdmission.crud.delete_warning': 'this action cannot be undone.',
      'foreignAdmission.col.id': 'Application №',
      'foreignAdmission.col.name': 'Full name',
      'foreignAdmission.col.country': 'Country',
      'foreignAdmission.col.direction': 'Direction',
      'foreignAdmission.col.created': 'Date',
      'foreignAdmission.col.status': 'Status',
      'foreignAdmission.col.actions': 'Actions',
      'foreignAdmission.filters.search_ph': 'Search by full name',
      'foreignAdmission.filters.country_ph': 'All countries',
      'foreignAdmission.filters.status_ph': 'All statuses',
      'foreignAdmission.filters.rangeFrom': 'From',
      'foreignAdmission.filters.rangeTo': 'To',
      'foreignAdmission.status.yangi': 'New',
      'foreignAdmission.status.tasdiqlangan': 'Approved',
      'foreignAdmission.status.radEtilgan': 'Rejected',
      'foreignAdmission.section.profile': 'Personal info',
      'foreignAdmission.section.education': 'Education',
      'foreignAdmission.section.documents': 'Uploaded documents',
      'foreignAdmission.field.full_name': 'Full name',
      'foreignAdmission.field.birth_date': 'Date of birth',
      'foreignAdmission.field.country': 'Citizenship',
      'foreignAdmission.field.phone': 'Phone',
      'foreignAdmission.field.parent_phone': "Parent's phone",
      'foreignAdmission.field.passport_number': 'Passport number',
      'foreignAdmission.field.passport_expiry': 'Passport valid through',
      'foreignAdmission.field.email': 'Email',
      'foreignAdmission.field.direction': 'Direction',
      'foreignAdmission.field.academic_year': 'Academic year',
      'foreignAdmission.docs.view': 'View',
      'foreignAdmission.docs.empty': 'No documents uploaded',
      'foreignAdmission.docs.slot.passport': 'Passport copy',
      'foreignAdmission.docs.slot.diploma': 'Diploma / Certificate',
      'foreignAdmission.docs.slot.certificate': 'Certificate',
      'foreignAdmission.docs.download': 'Download',
      'foreignAdmission.detail.back': 'Back',
      'foreignAdmission.detail.title': 'Application',
      'foreignAdmission.detail.print': 'Print',
      'foreignAdmission.detail.until': 'valid through',
      'foreignAdmission.detail.submitted_at': 'Submitted',
      'foreignAdmission.detail.not_found': 'Application not found',
      'foreignAdmission.action.approve': 'Approve',
      'foreignAdmission.action.reject': 'Return',
      'foreignAdmission.approve.confirm_title': 'Approve this application?',
      'foreignAdmission.approve.done': 'Application approved',
      'foreignAdmission.reject.title': 'Return application',
      'foreignAdmission.reject.reason': 'Reason',
      'foreignAdmission.reject.reason_ph': 'Describe why the application is returned',
      'foreignAdmission.reject.reason_min': 'Reason must be at least 10 characters',
      'foreignAdmission.reject.done': 'Application returned',
      'foreignAdmission.kpi.total': 'Total applications',
      'foreignAdmission.kpi.yangi': 'Under review',
      'foreignAdmission.kpi.tasdiqlangan': 'Approved',
      'foreignAdmission.kpi.radEtilgan': 'Rejected',
      'foreignAdmission.export.excel': 'Export to Excel (.xlsx)',
      'foreignAdmission.export.metric': 'Metric',
      'foreignAdmission.export.value': 'Value',
      'foreignAdmission.export.name': 'Name',
      'foreignAdmission.export.count': 'Count',
      'foreignAdmission.export.sheetKpi': 'Key metrics',
      'foreignAdmission.export.sheetDirection': 'Directions',
      'foreignAdmission.export.sheetMonth': 'Months',
      'foreignAdmission.export.sheetCountry': 'Countries',
      'foreignAdmission.chart.by_direction': 'By direction',
      'foreignAdmission.chart.by_country': 'By country',
      'foreignAdmission.chart.by_month': 'Over time',
      'foreignAdmission.directions.name': 'Direction name',
      'foreignAdmission.directions.name_ph': 'e.g. General medicine',
      'foreignAdmission.directions.new': 'New direction',
      'foreignAdmission.directions.create': 'Add direction',
      'foreignAdmission.directions.edit': 'Edit direction',
      'foreignAdmission.directions.search_ph': 'Search by direction name',
      'foreignAdmission.directions.delete_title': 'Delete direction',
      'foreignAdmission.eduForms.name': 'Education form',
      'foreignAdmission.eduForms.name_ph': 'e.g. Full-time',
      'foreignAdmission.eduForms.desc': 'Description',
      'foreignAdmission.eduForms.desc_ph': 'Short description',
      'foreignAdmission.eduForms.new': 'New education form',
      'foreignAdmission.eduForms.create': 'Add education form',
      'foreignAdmission.eduForms.edit': 'Edit education form',
      'foreignAdmission.eduForms.search_ph': 'Search by education form',
      'foreignAdmission.eduForms.delete_title': 'Delete education form',
      'foreignAdmission.eduLangs.name': 'Language',
      'foreignAdmission.eduLangs.name_ph': 'e.g. Uzbek',
      'foreignAdmission.eduLangs.new': 'New language',
      'foreignAdmission.eduLangs.create': 'Add language',
      'foreignAdmission.eduLangs.edit': 'Edit language',
      'foreignAdmission.eduLangs.search_ph': 'Search by language',
      'foreignAdmission.eduLangs.delete_title': 'Delete language',
      'foreignAdmission.countries.name': 'Country name',
      'foreignAdmission.countries.name_ph': 'e.g. Kazakhstan',
      'foreignAdmission.countries.flag': 'Flag',
      'foreignAdmission.countries.flag_hint': 'Upload the flag',
      'foreignAdmission.countries.passport': 'Passport sample',
      'foreignAdmission.countries.passport_ph': 'AB0000000',
      'foreignAdmission.countries.phone': 'Phone sample',
      'foreignAdmission.countries.phone_ph': '+998 90 123-45-67',
      'foreignAdmission.countries.new': 'New country',
      'foreignAdmission.countries.create': 'Add country',
      'foreignAdmission.countries.edit': 'Edit country',
      'foreignAdmission.countries.search_ph': 'Search by country name',
      'foreignAdmission.countries.delete_title': 'Delete country',
      'foreignAdmission.offer.block_title': 'Heading',
      'foreignAdmission.offer.title_ph': 'Enter the offer heading',
      'foreignAdmission.offer.body': 'Text',
      'foreignAdmission.offer.body_ph': 'Describe the offer term',
      'foreignAdmission.offer.add': 'Add',
      'foreignAdmission.offer.saved': 'Offer saved',
      'foreignAdmission.offer.delete_title': 'Delete offer block',
      'foreignAdmission.offer.min_one': 'At least one block must remain',
      'foreignAdmission.offer.empty': 'Fill at least one block',
      'foreignAdmission.offer.uz_required': 'Uzbek heading is required for every block',
      'foreignAdmission.seasons.title': 'Title',
      'foreignAdmission.seasons.title_ph': 'Admission title',
      'foreignAdmission.seasons.description': 'Description',
      'foreignAdmission.seasons.description_ph': 'Short description',
      'foreignAdmission.seasons.season': 'Season',
      'foreignAdmission.seasons.season_ph': 'Select a season',
      'foreignAdmission.seasons.date_ph': 'Select date',
      'foreignAdmission.seasons.season_all': 'All seasons',
      'foreignAdmission.seasons.year_ph': 'Select or type an academic year',
      'foreignAdmission.seasons.year_format': 'Format: 2025/2026',
      'foreignAdmission.seasons.year_all': 'All academic years',
      'foreignAdmission.seasons.open_date': 'Opens',
      'foreignAdmission.seasons.close_date': 'Closes',
      'foreignAdmission.seasons.direction': 'Direction',
      'foreignAdmission.seasons.direction_ph': 'Select a direction',
      'foreignAdmission.seasons.forms_ph': 'Select education forms',
      'foreignAdmission.seasons.langs_ph': 'Select languages',
      'foreignAdmission.seasons.add_direction': 'Add direction',
      'foreignAdmission.seasons.new': 'New admission period',
      'foreignAdmission.seasons.create': 'Open admission',
      'foreignAdmission.seasons.edit': 'Edit admission',
      'foreignAdmission.seasons.view': 'Admission period (view)',
      'foreignAdmission.seasons.created': 'Admission period created',
      'foreignAdmission.seasons.search_ph': 'Search by title',
      'foreignAdmission.seasons.delete_title': 'Delete admission period',
      'foreignAdmission.seasons.date_order': 'The closing date must be after the opening date',
      'foreignAdmission.seasons.close_title': 'Close this admission?',
      'foreignAdmission.seasons.close_warning': 'Once closed it cannot be edited or reopened.',
      'foreignAdmission.seasons.close_ok': 'Close admission',
      'foreignAdmission.seasons.closed': 'Admission period closed',
      'foreignAdmission.season.bahor': 'Spring',
      'foreignAdmission.season.yoz': 'Summer',
      'foreignAdmission.season.kuz': 'Autumn',
      'foreignAdmission.season.qish': 'Winter',
      'foreignAdmission.seasonStatus.rejada': 'Planned',
      'foreignAdmission.seasonStatus.ochiq': 'Open',
      'foreignAdmission.seasonStatus.yopiq': 'Closed',
      'foreignAdmission.messages.text': 'Message',
      'foreignAdmission.messages.text_ph': 'Enter the message text',
      'foreignAdmission.messages.send': 'Send message',
      'foreignAdmission.messages.send_ok': 'Send',
      'foreignAdmission.messages.search_ph': 'Search by message text',
      'foreignAdmission.messages.direction_all': 'All directions',
      'foreignAdmission.messages.lang_all': 'All languages',
      'foreignAdmission.messages.info': 'Sent to applicants whose application is approved.',
      'foreignAdmission.messages.counting': 'Counting recipients...',
      'foreignAdmission.messages.recipients': 'Current filter: {{n}} applicants',
      'foreignAdmission.messages.confirm_title': 'Send the message?',
      'foreignAdmission.messages.confirm_body': 'The message will be emailed to {{n}} applicants. This cannot be undone.',
      'foreignAdmission.messages.confirm_ok': 'Confirm',
      'foreignAdmission.messages.sent': 'Message sent ({{delivered}}/{{total}})',
      'foreignAdmission.messages.delivered': 'Delivered',
      'foreignAdmission.messages.export': 'Export to Excel',
      'foreignAdmission.messages.export_empty': 'Nothing to export',
    },
    ru: {
      'menuGroup.foreignAdmission': 'Международный приём',
      'foreignAdmission.nav.dashboard': 'Статистика',
      'foreignAdmission.nav.applications': 'Заявки',
      'foreignAdmission.nav.messages': 'Сообщения',
      'foreignAdmission.nav.seasons': 'Приём',
      'foreignAdmission.nav.structure': 'Структура образования',
      'foreignAdmission.nav.directions': 'Направления',
      'foreignAdmission.nav.educationForms': 'Формы обучения',
      'foreignAdmission.nav.educationLanguages': 'Языки обучения',
      'foreignAdmission.nav.countries': 'Страны',
      'foreignAdmission.nav.offer': 'Публичная оферта',
      'foreignAdmission.cancel': 'Отмена',
      'foreignAdmission.save': 'Сохранить',
      'foreignAdmission.close': 'Закрыть',
      'foreignAdmission.err.required': 'Обязательное поле',
      'foreignAdmission.view': 'Открыть',
      'foreignAdmission.total': 'Всего',
      'foreignAdmission.crud.created': 'Запись добавлена',
      'foreignAdmission.crud.updated': 'Сохранено',
      'foreignAdmission.crud.deleted': 'Удалено',
      'foreignAdmission.crud.delete': 'Удалить',
      'foreignAdmission.crud.delete_warning': 'это действие нельзя отменить.',
      'foreignAdmission.col.id': 'Номер заявки',
      'foreignAdmission.col.name': 'Ф.И.О.',
      'foreignAdmission.col.country': 'Страна',
      'foreignAdmission.col.direction': 'Направление',
      'foreignAdmission.col.created': 'Дата',
      'foreignAdmission.col.status': 'Статус',
      'foreignAdmission.col.actions': 'Действия',
      'foreignAdmission.filters.search_ph': 'Поиск по Ф.И.О.',
      'foreignAdmission.filters.country_ph': 'Все страны',
      'foreignAdmission.filters.status_ph': 'Все статусы',
      'foreignAdmission.filters.rangeFrom': 'От',
      'foreignAdmission.filters.rangeTo': 'До',
      'foreignAdmission.status.yangi': 'Новая',
      'foreignAdmission.status.tasdiqlangan': 'Подтверждена',
      'foreignAdmission.status.radEtilgan': 'Отклонена',
      'foreignAdmission.section.profile': 'Личные данные',
      'foreignAdmission.section.education': 'Образование',
      'foreignAdmission.section.documents': 'Загруженные документы',
      'foreignAdmission.field.full_name': 'Ф.И.О.',
      'foreignAdmission.field.birth_date': 'Дата рождения',
      'foreignAdmission.field.country': 'Гражданство',
      'foreignAdmission.field.phone': 'Телефон',
      'foreignAdmission.field.parent_phone': 'Телефон родителей',
      'foreignAdmission.field.passport_number': 'Серия и номер паспорта',
      'foreignAdmission.field.passport_expiry': 'Срок действия паспорта',
      'foreignAdmission.field.email': 'Email',
      'foreignAdmission.field.direction': 'Направление',
      'foreignAdmission.field.academic_year': 'Учебный год',
      'foreignAdmission.docs.view': 'Открыть',
      'foreignAdmission.docs.empty': 'Документы не загружены',
      'foreignAdmission.docs.slot.passport': 'Копия паспорта',
      'foreignAdmission.docs.slot.diploma': 'Диплом / Аттестат',
      'foreignAdmission.docs.slot.certificate': 'Сертификат',
      'foreignAdmission.docs.download': 'Скачать',
      'foreignAdmission.detail.back': 'Назад',
      'foreignAdmission.detail.title': 'Заявка',
      'foreignAdmission.detail.print': 'Печать',
      'foreignAdmission.detail.until': 'до',
      'foreignAdmission.detail.submitted_at': 'Дата заявки',
      'foreignAdmission.detail.not_found': 'Заявка не найдена',
      'foreignAdmission.action.approve': 'Подтвердить',
      'foreignAdmission.action.reject': 'Вернуть',
      'foreignAdmission.approve.confirm_title': 'Подтвердить заявку?',
      'foreignAdmission.approve.done': 'Заявка подтверждена',
      'foreignAdmission.reject.title': 'Вернуть заявку',
      'foreignAdmission.reject.reason': 'Причина возврата',
      'foreignAdmission.reject.reason_ph': 'Опишите подробную причину возврата заявки',
      'foreignAdmission.reject.reason_min': 'Причина должна содержать минимум 10 символов',
      'foreignAdmission.reject.done': 'Заявка возвращена',
      'foreignAdmission.kpi.total': 'Всего заявок',
      'foreignAdmission.kpi.yangi': 'На рассмотрении',
      'foreignAdmission.kpi.tasdiqlangan': 'Подтверждённые',
      'foreignAdmission.kpi.radEtilgan': 'Отклонённые',
      'foreignAdmission.export.excel': 'Экспорт в Excel (.xlsx)',
      'foreignAdmission.export.metric': 'Показатель',
      'foreignAdmission.export.value': 'Значение',
      'foreignAdmission.export.name': 'Название',
      'foreignAdmission.export.count': 'Количество',
      'foreignAdmission.export.sheetKpi': 'Основные показатели',
      'foreignAdmission.export.sheetDirection': 'Направления',
      'foreignAdmission.export.sheetMonth': 'Месяцы',
      'foreignAdmission.export.sheetCountry': 'Страны',
      'foreignAdmission.chart.by_direction': 'По направлениям',
      'foreignAdmission.chart.by_country': 'По странам',
      'foreignAdmission.chart.by_month': 'В разрезе времени',
      'foreignAdmission.directions.name': 'Название направления',
      'foreignAdmission.directions.name_ph': 'Например: Лечебное дело',
      'foreignAdmission.directions.new': 'Новое направление',
      'foreignAdmission.directions.create': 'Добавить направление',
      'foreignAdmission.directions.edit': 'Редактировать направление',
      'foreignAdmission.directions.search_ph': 'Поиск по названию направления',
      'foreignAdmission.directions.delete_title': 'Удалить направление',
      'foreignAdmission.eduForms.name': 'Форма обучения',
      'foreignAdmission.eduForms.name_ph': 'Например: Очная',
      'foreignAdmission.eduForms.desc': 'Описание',
      'foreignAdmission.eduForms.desc_ph': 'Краткое описание',
      'foreignAdmission.eduForms.new': 'Новая форма обучения',
      'foreignAdmission.eduForms.create': 'Добавить форму обучения',
      'foreignAdmission.eduForms.edit': 'Редактировать форму обучения',
      'foreignAdmission.eduForms.search_ph': 'Поиск по форме обучения',
      'foreignAdmission.eduForms.delete_title': 'Удалить форму обучения',
      'foreignAdmission.eduLangs.name': 'Язык обучения',
      'foreignAdmission.eduLangs.name_ph': 'Например: Узбекский',
      'foreignAdmission.eduLangs.new': 'Новый язык обучения',
      'foreignAdmission.eduLangs.create': 'Добавить язык обучения',
      'foreignAdmission.eduLangs.edit': 'Редактировать язык обучения',
      'foreignAdmission.eduLangs.search_ph': 'Поиск по языку обучения',
      'foreignAdmission.eduLangs.delete_title': 'Удалить язык обучения',
      'foreignAdmission.countries.name': 'Название страны',
      'foreignAdmission.countries.name_ph': 'Например: Казахстан',
      'foreignAdmission.countries.flag': 'Флаг',
      'foreignAdmission.countries.flag_hint': 'Загрузите флаг',
      'foreignAdmission.countries.passport': 'Образец паспорта',
      'foreignAdmission.countries.passport_ph': 'AB0000000',
      'foreignAdmission.countries.phone': 'Образец телефона',
      'foreignAdmission.countries.phone_ph': '+998 90 123-45-67',
      'foreignAdmission.countries.new': 'Новая страна',
      'foreignAdmission.countries.create': 'Добавить страну',
      'foreignAdmission.countries.edit': 'Редактировать страну',
      'foreignAdmission.countries.search_ph': 'Поиск по названию страны',
      'foreignAdmission.countries.delete_title': 'Удалить страну',
      'foreignAdmission.offer.block_title': 'Заголовок',
      'foreignAdmission.offer.title_ph': 'Введите заголовок оферты',
      'foreignAdmission.offer.body': 'Текст',
      'foreignAdmission.offer.body_ph': 'Опишите условие оферты',
      'foreignAdmission.offer.add': 'Добавить',
      'foreignAdmission.offer.saved': 'Оферта сохранена',
      'foreignAdmission.offer.delete_title': 'Удалить блок оферты',
      'foreignAdmission.offer.min_one': 'Должен остаться минимум 1 блок',
      'foreignAdmission.offer.empty': 'Заполните хотя бы один блок',
      'foreignAdmission.offer.uz_required': 'Узбекский заголовок обязателен для каждого блока',
      'foreignAdmission.seasons.title': 'Заголовок',
      'foreignAdmission.seasons.title_ph': 'Заголовок приёма',
      'foreignAdmission.seasons.description': 'Описание',
      'foreignAdmission.seasons.description_ph': 'Краткое описание приёма',
      'foreignAdmission.seasons.season': 'Сезон',
      'foreignAdmission.seasons.season_ph': 'Выберите сезон',
      'foreignAdmission.seasons.date_ph': 'Выберите дату',
      'foreignAdmission.seasons.season_all': 'Все сезоны',
      'foreignAdmission.seasons.year_ph': 'Выберите или введите учебный год',
      'foreignAdmission.seasons.year_format': 'Формат: 2025/2026',
      'foreignAdmission.seasons.year_all': 'Все учебные годы',
      'foreignAdmission.seasons.open_date': 'Открытие приёма',
      'foreignAdmission.seasons.close_date': 'Закрытие приёма',
      'foreignAdmission.seasons.direction': 'Направление',
      'foreignAdmission.seasons.direction_ph': 'Выберите направление',
      'foreignAdmission.seasons.forms_ph': 'Выберите формы обучения',
      'foreignAdmission.seasons.langs_ph': 'Выберите языки обучения',
      'foreignAdmission.seasons.add_direction': 'Добавить направление',
      'foreignAdmission.seasons.new': 'Новый период приёма',
      'foreignAdmission.seasons.create': 'Открыть приём',
      'foreignAdmission.seasons.edit': 'Редактировать приём',
      'foreignAdmission.seasons.view': 'Период приёма (просмотр)',
      'foreignAdmission.seasons.created': 'Период приёма создан',
      'foreignAdmission.seasons.search_ph': 'Поиск по заголовку',
      'foreignAdmission.seasons.delete_title': 'Удалить период приёма',
      'foreignAdmission.seasons.date_order': 'Дата закрытия должна быть позже даты открытия',
      'foreignAdmission.seasons.close_title': 'Закрыть приём?',
      'foreignAdmission.seasons.close_warning': 'После закрытия период нельзя редактировать и открыть заново.',
      'foreignAdmission.seasons.close_ok': 'Закрыть приём',
      'foreignAdmission.seasons.closed': 'Период приёма закрыт',
      'foreignAdmission.season.bahor': 'Весна',
      'foreignAdmission.season.yoz': 'Лето',
      'foreignAdmission.season.kuz': 'Осень',
      'foreignAdmission.season.qish': 'Зима',
      'foreignAdmission.seasonStatus.rejada': 'Запланирован',
      'foreignAdmission.seasonStatus.ochiq': 'Открыт',
      'foreignAdmission.seasonStatus.yopiq': 'Закрыт',
      'foreignAdmission.messages.text': 'Текст сообщения',
      'foreignAdmission.messages.text_ph': 'Введите текст сообщения',
      'foreignAdmission.messages.send': 'Отправить сообщение',
      'foreignAdmission.messages.send_ok': 'Отправить',
      'foreignAdmission.messages.search_ph': 'Поиск по тексту сообщения',
      'foreignAdmission.messages.direction_all': 'Все направления',
      'foreignAdmission.messages.lang_all': 'Все языки',
      'foreignAdmission.messages.info': 'Отправляется абитуриентам с подтверждённой заявкой.',
      'foreignAdmission.messages.counting': 'Подсчёт получателей...',
      'foreignAdmission.messages.recipients': 'По текущему фильтру: {{n}} абитуриентов',
      'foreignAdmission.messages.confirm_title': 'Отправить сообщение?',
      'foreignAdmission.messages.confirm_body': 'Сообщение будет отправлено на email {{n}} абитуриентов. Это действие нельзя отменить.',
      'foreignAdmission.messages.confirm_ok': 'Подтвердить',
      'foreignAdmission.messages.sent': 'Сообщение отправлено ({{delivered}}/{{total}})',
      'foreignAdmission.messages.delivered': 'Доставлено',
      'foreignAdmission.messages.export': 'Выгрузить в Excel',
      'foreignAdmission.messages.export_empty': 'Нет данных для выгрузки',
    },
  },
  permissions: [
    { key: 'internationalAdmission:read', description: 'View one application' },
    { key: 'internationalAdmission:readAll', description: 'List applications + dashboard' },
    { key: 'internationalAdmission:update', description: 'Update application data' },
    { key: 'internationalAdmission:delete', description: 'Delete application' },
    { key: 'internationalAdmission:approve', description: 'Approve application' },
    { key: 'internationalAdmission:reject', description: 'Return application with a reason' },

    { key: 'admissionSeason:create', description: 'Create admission period' },
    { key: 'admissionSeason:read', description: 'View one admission period' },
    { key: 'admissionSeason:readAll', description: 'List admission periods' },
    { key: 'admissionSeason:update', description: 'Update admission period' },
    { key: 'admissionSeason:delete', description: 'Delete admission period' },
    { key: 'admissionSeason:changeStatus', description: 'Close an admission period early' },

    { key: 'admissionDirection:create', description: 'Create admission direction' },
    { key: 'admissionDirection:read', description: 'View one admission direction' },
    { key: 'admissionDirection:readAll', description: 'List admission directions' },
    { key: 'admissionDirection:update', description: 'Update admission direction' },
    { key: 'admissionDirection:delete', description: 'Delete admission direction' },

    { key: 'admissionEducationForm:create', description: 'Create admission education form' },
    { key: 'admissionEducationForm:read', description: 'View one admission education form' },
    { key: 'admissionEducationForm:readAll', description: 'List admission education forms' },
    { key: 'admissionEducationForm:update', description: 'Update admission education form' },
    { key: 'admissionEducationForm:delete', description: 'Delete admission education form' },

    { key: 'admissionEducationLanguage:create', description: 'Create admission language' },
    { key: 'admissionEducationLanguage:read', description: 'View one admission language' },
    { key: 'admissionEducationLanguage:readAll', description: 'List admission languages' },
    { key: 'admissionEducationLanguage:update', description: 'Update admission language' },
    { key: 'admissionEducationLanguage:delete', description: 'Delete admission language' },

    { key: 'admissionCountry:create', description: 'Create admission country' },
    { key: 'admissionCountry:read', description: 'View one admission country' },
    { key: 'admissionCountry:readAll', description: 'List admission countries' },
    { key: 'admissionCountry:update', description: 'Update admission country' },
    { key: 'admissionCountry:delete', description: 'Delete admission country' },

    { key: 'admissionOffer:read', description: 'View admission public offer' },
    { key: 'admissionOffer:readAll', description: 'Open the admission public offer page' },
    { key: 'admissionOffer:update', description: 'Edit admission public offer' },

    { key: 'admissionMessage:create', description: 'Send message to applicants' },
    { key: 'admissionMessage:read', description: 'View one sent message' },
    { key: 'admissionMessage:readAll', description: 'List sent messages' },
    { key: 'admissionMessage:export', description: 'Export sent messages to Excel' },
  ],
});
