import type { ModulePermission } from '@/shared/lib/module';

export const STUDY_LOAD_PERMISSIONS: ModulePermission[] = [
  { key: 'statistics:read', description: "O'UB O'quv statistikasi dashboardini ko'rish" },

  { key: 'learningProcess:create', description: 'Create learning process (upload study plan)' },
  { key: 'learningProcess:update', description: 'Update learning process (study plan content)' },

  { key: 'studyPlan:create',   description: 'Create study plan' },
  { key: 'studyPlan:read',     description: 'View one study plan' },
  { key: 'studyPlan:readAll',  description: 'List study plans' },
  { key: 'studyPlan:update',   description: 'Update study plan' },
  { key: 'studyPlan:delete',   description: 'Delete study plan' },
  { key: 'studyPlan:export',   description: 'View / download study plan PDF' },

  { key: 'workingPlan:create',   description: 'Create working plan' },
  { key: 'workingPlan:read',     description: 'View one working plan' },
  { key: 'workingPlan:readAll',  description: 'List working plans' },
  { key: 'workingPlan:update',   description: 'Update working plan' },
  { key: 'workingPlan:delete',   description: 'Delete working plan' },

  { key: 'workingSchedule:create',      description: 'Create working schedule' },
  { key: 'workingSchedule:read',        description: 'View one working schedule' },
  { key: 'workingSchedule:readAll',     description: 'List working schedules' },
  { key: 'workingSchedule:update',      description: 'Update working schedule (incl. generate-stream)' },
  { key: 'workingSchedule:delete',      description: 'Delete working schedule' },
  { key: 'workingSchedule:approve',     description: 'Approve working schedule (chain step)' },
  { key: 'workingSchedule:reject',      description: 'Reject working schedule (chain step)' },

  { key: 'workload:create',       description: 'Create workload' },
  { key: 'workload:read',         description: 'View one workload' },
  { key: 'workload:readAll',      description: 'List workloads' },
  { key: 'workload:update',       description: 'Update workload' },
  { key: 'workload:delete',       description: 'Delete workload' },
  { key: 'workload:changeStatus', description: 'Change workload status' },
  { key: 'workload:approve',      description: 'Approve workload (PATCH /workloads/approve/:id)' },
  { key: 'workload:reject',       description: 'Reject workload (PATCH /workloads/reject/:id)' },
  { key: 'workloadSummary:create',  description: "Create departments hours summary document (POST /workload-summaries)" },
  { key: 'workloadSummary:read',    description: 'View one summary document (+ xlsx/pdf export)' },
  { key: 'workloadSummary:readAll', description: 'List summary documents' },
  { key: 'workloadSummary:approve', description: 'Submit / approve chain step (PATCH /workload-summaries/approve/:id)' },
  { key: 'workloadSummary:reject',  description: 'Reject chain step (PATCH /workload-summaries/reject/:id)' },
  { key: 'workloadSummary:delete',  description: 'Delete draft summary (DELETE /workload-summaries/:id)' },
  { key: 'contingentReport:create',  description: 'Create contingent report (POST /contingent-reports)' },
  { key: 'contingentReport:read',    description: 'View one contingent report' },
  { key: 'contingentReport:readAll', description: 'List contingent reports / institute summary' },
  { key: 'contingentReport:update',  description: 'Edit rows, prefill, submit / reopen (PUT, POST /:id/prefill, PATCH approve)' },
  { key: 'contingentReport:approve', description: 'Dean approves (PATCH /contingent-reports/approve/:id)' },
  { key: 'contingentReport:reject',  description: 'Dean returns (PATCH /contingent-reports/reject/:id)' },
  { key: 'contingentReport:export',  description: 'PDF / Excel (faculty document and institute summary)' },
  { key: 'contingentReport:delete',  description: 'Delete draft/rejected report (DELETE /contingent-reports/:id)' },
  { key: 'departmentContingent:create',  description: 'Create department contingent / stream suggestion (POST /, GET /prefill)' },
  { key: 'departmentContingent:read',    description: 'View one department contingent' },
  { key: 'departmentContingent:readAll', description: 'List department contingents / institute summary' },
  { key: 'departmentContingent:update',  description: 'Edit rows — stream split (PUT /department-contingents/:id)' },
  { key: 'departmentContingent:delete',  description: 'Soft-delete department contingent (DELETE /department-contingents/:id)' },

  { key: 'workloadDistribution:create',       description: 'Create distribution' },
  { key: 'workloadDistribution:read',         description: 'View one distribution' },
  { key: 'workloadDistribution:readAll',      description: 'List distributions' },
  { key: 'workloadDistribution:update',       description: 'Update distribution' },
  { key: 'workloadDistribution:delete',       description: 'Delete distribution' },
  { key: 'workloadDistribution:changeStatus', description: 'Change distribution status (teacher accept/reject own workload — /respond)' },
  { key: 'workloadDistribution:approve',      description: 'Approve distribution (PATCH /distributions/approve/:id)' },
  { key: 'workloadDistribution:reject',       description: 'Reject distribution (PATCH /distributions/reject/:id)' },

  { key: 'scienceProgram:create',  description: 'Create science program' },
  { key: 'scienceProgram:read',    description: 'View one science program' },
  { key: 'scienceProgram:readAll', description: 'List science programs' },
  { key: 'scienceProgram:update',  description: 'Update science program' },
  { key: 'scienceProgram:delete',  description: 'Delete science program' },
  { key: 'scienceProgram:approve', description: 'Approve science program' },
  { key: 'scienceProgram:reject',  description: 'Reject science program' },

  { key: 'syllabus:create',  description: 'Create syllabus' },
  { key: 'syllabus:read',    description: 'View one syllabus' },
  { key: 'syllabus:readAll', description: 'List syllabi' },
  { key: 'syllabus:update',  description: 'Update syllabus' },
  { key: 'syllabus:delete',  description: 'Delete syllabus' },
  { key: 'syllabus:approve', description: 'Approve syllabus' },
  { key: 'syllabus:reject',  description: 'Reject syllabus' },

  { key: 'teacherLeave:create',  description: 'Submit teacher leave/resignation/transfer request' },
  { key: 'teacherLeave:read',    description: 'View one teacher leave request' },
  { key: 'teacherLeave:readAll', description: 'List teacher leave requests' },
  { key: 'teacherLeave:update',  description: 'Update/approve/reject teacher leave request' },
  { key: 'teacherLeave:delete',  description: 'Delete teacher leave request' },
];
