export type PersonalPlanStatus = 'draft' | 'submitted' | 'approved' | 'rejected' | 'completed';

export type WorkItemStatus = 'planned' | 'completed' | 'overdue' | 'cancelled';

export type VerificationStatus = 'pending' | 'approved' | 'rejected';

export type ActivitySection =
  | 'methodicalWork'
  | 'researchWork'
  | 'mentoringWork'
  | 'organizationalWork'
  | 'extraWork';

export type ApprovalStepKey =
  | 'teacher'
  | 'kafedraUslubiy'
  | 'kafedraIlmiy'
  | 'kafedraUstozShogird'
  | 'kafedraMudiri'
  | 'oquvUslubiy'
  | 'dekan'
  | 'ichkiNazorat';

export type ApprovalStepStatus = 'pending' | 'approved' | 'rejected';

export interface ApprovalStep {
  step: ApprovalStepKey;
  label: string;
  status: ApprovalStepStatus;
  approvedById: string | null;
  approvedByName: string | null;
  date: string | null;
  comment: string | null;
}

export interface HoursByType {
  lecture: number;
  seminar: number;
  laboratory: number;
  practical: number;
  independent: number;
  on: number | null;
  yan: number | null;
  retake: number | null;
  practiceLead: number | null;
  otherWork: number | null;
  adjustment: number | null;
}

export interface TeachingScience {
  id: string;
  scienceName: string | null;
  course: number;
  semester: number;
  hoursByType: HoursByType;
  totalHour: number;
  stavka: number;
  streamCount: number | null;
  groupCount: number | null;
  decomposed: boolean;
}

export interface WorkItemVerification {
  status: VerificationStatus;
  date: string | null;
  comment: string | null;
}

export interface WorkItem {
  id: string;
  title: string;
  description: string | null;
  deadline: string | null;
  completedAt: string | null;
  status: WorkItemStatus;
  fileUrl: string | null;
  link: string | null;
  note: string | null;
  semester: number[];
  plannedCount: number | null;
  actualCount: number | null;
  venue: string | null;
  verification: WorkItemVerification | null;
}

export interface WorkItemFormValues {
  title: string;
  plannedCount: number | null;
  semester: number[];
  deadline: string | null;
  venue: string;
}

export interface PersonalPlan {
  id: string;
  academicYearId: string | null;
  academicYearTitle: string | null;
  teacherId: string | null;
  teacherName: string | null;
  status: PersonalPlanStatus;
  plannedHour: number;
  scienceCount: number;
  autoGenerated: boolean;
  createdAt: string | null;
  approvals: ApprovalStep[];
  currentStep: ApprovalStepKey | null;
  currentStepLabel: string | null;
  submittedAt: string | null;
}

export interface PersonalPlanDetail {
  id: string;
  name: string | null;
  academicYearId: string | null;
  academicYearTitle: string | null;
  teacherId: string | null;
  teacherName: string | null;
  status: PersonalPlanStatus;
  plannedHour: number;
  completedHour: number;
  autoGenerated: boolean;
  sciences: TeachingScience[];
  methodicalWork: WorkItem[];
  researchWork: WorkItem[];
  mentoringWork: WorkItem[];
  organizationalWork: WorkItem[];
  extraWork: WorkItem[];
  approvals: ApprovalStep[];
  approvedByName: string | null;
  approvalDate: string | null;
  approvalComment: string | null;
  createdAt: string | null;
}

export interface GenerateFormValues {
  academicYear: string;
}
