module.exports = {
  ROLES: {
    SUPER_ADMIN: "super_admin",
    ADMIN: "admin",
    REKTOR: "rektor",
    PROREKTOR: "prorektor",
    DEKAN: "dekan",
    KAFEDRA_MUDIRI: "kafedra_mudiri",
    OQITUVCHI: "oqituvchi",
    TALABA: "talaba",
    REZIDENT: "rezident",
    MAGISTRANT: "magistrant",
    TINGLOVCHI: "tinglovchi",
    ILMIY_KENGASH_KOTIBI: "ilmiy_kengash_kotibi",
    ILMIY_KENGASH_AZOSI: "ilmiy_kengash_azosi",
    TASHQI_TADQIQOTCHI: "tashqi_tadqiqotchi",
    KADRLAR: "kadrlar",
    REJA_MOLIYA: "reja_moliya",
    ARM: "arm",
    MALAKA_MENEJER: "malaka_menejer",
    MALAKA_OQITUVCHI: "malaka_oqituvchi",
    MALAKA_TINGLOVCHI: "malaka_tinglovchi",
    AMALIYOT_BOLIMI: "amaliyot_bolimi",
    TIBBIYOT_BIRLASHMASI_RAHBARI: "tibbiyot_birlashmasi_rahbari",
    SIFAT_BOLIMI: "sifat_bolimi",
    TALIM_SIFATI_NAZORATI: "talim_sifati_nazorati",
    IQTIDORLI_BOLIM: "iqtidorli_bolim",
    HAKAM: "hakam",
    ILMIY_BOLIM: "ilmiy_bolim",
    MAGISTRATURA_BOLIM: "magistratura_bolim",
    QABUL_BOLIMI: "qabul_bolimi",
    KLINIK_USTOZ: "klinik_ustoz",
    ILMIY_RAHBAR: "ilmiy_rahbar",
    OQUV_USLUBIY_BOSHQARMA: "oquv_uslubiy_boshqarma",
    KAFEDRA_USLUBIY_MASUL: "kafedra_uslubiy_masul",
    KAFEDRA_ILMIY_MASUL: "kafedra_ilmiy_masul",
    KAFEDRA_USTOZ_SHOGIRD_MASUL: "kafedra_ustoz_shogird_masul",
    ICHKI_NAZORAT: "ichki_nazorat",
    FAKULTET_KENGASH_KOTIBI: "fakultet_kengash_kotibi",
    MODERATOR: "moderator",
  },

  USER_STATUSES: {
    FAOL: "faol",
    BLOKLANGAN: "bloklangan",
  },

  APPROVAL_STATUSES: {
    PENDING: "pending",
    APPROVED: "approved",
    REJECTED: "rejected",
    RETURNED: "returned",
  },

  MODULES: {
    AUTH: "auth",
    USER: "user",
    ROLE: "role",
    PERMISSION: "permission",
    PERMISSION_GROUP: "permissionGroup",
    AUDIT_LOG: "auditLog",
    DASHBOARD: "dashboard",
    STATISTICS: "statistics",

    FACULTY: "faculty",
    DEPARTMENT: "department",
    COURSE: "course",
    GROUP: "group",
    ROOM: "room",
    POSITION: "position",
    DIRECTION: "direction",
    DIVISION: "division",
    SCIENCE: "science",
    SCIENCE_BRANCH: "scienceBranch",
    ACADEMIC_LEVEL: "academicLevel",
    ACADEMIC_TITLE: "academicTitle",
    AUDITORIUM_HOUR: "auditoriumHour",
    EDUCATION_FORM: "educationForm",
    EDUCATION_ACTIVITY_TYPE: "educationActivityType",
    READING_FORM: "readingForm",
    SPECIALIZATION: "specialization",
    STUDY_PERIOD: "studyPeriod",
    ACADEMIC_YEAR: "academicYear",
    ASSESSMENT_TYPE: "assessmentType",

    WORKLOAD: "workload",
    WORKLOAD_SUMMARY: "workloadSummary",
    CONTINGENT_REPORT: "contingentReport",
    DEPARTMENT_CONTINGENT: "departmentContingent",
    WORKLOAD_DISTRIBUTION: "workloadDistribution",
    WORKING_PLAN: "workingPlan",
    WORKING_SCHEDULE: "workingSchedule",
    STUDY_PLAN: "studyPlan",
    SYLLABUS: "syllabus",
    SCIENCE_PROGRAM: "scienceProgram",
    LEARNING_PROCESS: "learningProcess",
    TEACHER_LEAVE: "teacherLeave",

    SCHEDULE: "schedule",
    TIME_SLOT: "timeSlot",

    TEACHER: "teacher",
    PERSONAL_WORK_PLAN: "personalWorkPlan",
    STAFF: "staff",

    STUDENT: "student",
    STUDENT_ATTENDANCE: "studentAttendance",

    GRADEBOOK: "gradebook",
    EXAM: "exam",

    QUAL_COURSE: "qualCourse",
    QUAL_COURSE_TYPE: "qualCourseType",
    QUAL_COURSE_SUBSCRIPTION: "qualCourseSubscription",
    QUAL_CALENDAR_PLAN: "qualCalendarPlan",
    QUAL_CONTRACT: "qualContract",
    QUAL_PAYMENT: "qualPayment",
    QUAL_PETITION: "qualPetition",
    QUAL_SOURCE: "qualSource",
    QUAL_TEACHER: "qualTeacher",
    QUAL_TOPIC: "qualTopic",
    QUAL_NOTIFICATION: "qualNotification",
    QUAL_ACCESS_TEST_RESULT: "qualAccessTestResult",
    QUAL_FINAL_TEST_RESULT: "qualFinalTestResult",
    QUAL_EXIT_TEST_RESULT: "qualExitTestResult",
    QUAL_TOPIC_COMPLETION: "qualTopicCompletion",
    QUAL_TOPIC_LECTURE: "qualTopicLecture",
    QUAL_TOPIC_PRACTICAL: "qualTopicPractical",
    QUAL_TOPIC_VIDEO: "qualTopicVideo",
    QUAL_TOPIC_SCENARIO: "qualTopicScenario",
    QUAL_TOPIC_FINAL_TEST: "qualTopicFinalTest",
    QUAL_ACCESS_TEST: "qualAccessTest",
    QUAL_EXIT_TEST: "qualExitTest",
    QUAL_SURVEY: "qualSurvey",
    QUAL_SURVEY_ANSWER: "qualSurveyAnswer",
    QUAL_CERTIFICATE: "qualCertificate",
    QUAL_TEST_CONFIG: "qualTestConfig",
    QUAL_LISTENER_PORTAL: "qualListenerPortal",

    RESIDENT: "resident",
    RESIDENCY_SPECIALTY: "residencySpecialty",
    RESIDENCY_ACTIVITY_PLAN: "residencyActivityPlan",
    RESIDENCY_DISSERTATION_PLAN: "residencyDissertationPlan",
    RESIDENCY_THEORY_TOPIC: "residencyTheoryTopic",
    RESIDENCY_SKILL: "residencySkill",
    RESIDENCY_ATTESTATION: "residencyAttestation",
    RESIDENCY_CURRICULUM: "residencyCurriculum",
    RESIDENCY_LESSON: "residencyLesson",
    RESIDENCY_NOTICE: "residencyNotice",
    RESIDENCY_PROBLEM_STUDENT: "residencyProblemStudent",
    RESIDENCY_ANNOUNCEMENT: "residencyAnnouncement",
    RESIDENCY_REPORT: "residencyReport",
    RESIDENT_APPLICATION: "residentApplication",
    RESIDENT_ATTENDANCE: "residentAttendance",
    RESIDENT_DAILY_LOG: "residentDailyLog",
    RESIDENT_ASSESSMENT: "residentAssessment",
    RESIDENT_RESOURCE: "residentResource",
    RESIDENCY_OPEN_LESSON: "residencyOpenLesson",
    DISSERTATION: "dissertation",

    COUNCIL_MEMBER: "councilMember",
    COUNCIL_TASK: "councilTask",
    RANK_APPLICATION: "rankApplication",
    VOTING_SESSION: "votingSession",
    ANONYMOUS_VOTE: "anonymousVote",

    SCIENTIFIC_WORK: "scientificWork",
    WORK_REVIEW: "workReview",
    WORK_DECISION: "workDecision",
    SCIENCE_COUNCIL: "scienceCouncil",

    ARTICLE: "article",
    MONOGRAPH: "monograph",
    THESIS: "thesis",
    PATENT: "patent",
    COPYRIGHT: "copyright",
    CONFERENCE: "conference",
    METHODICAL_RECOMMENDATION: "methodicalRecommendation",
    METHODICAL_SPECIALTY: "methodicalSpecialty",
    ANNUAL_REPORT: "annualReport",
    DEPARTMENT_WORK_PLAN: "departmentWorkPlan",
    QUALIFYING_APPLICANT: "qualifyingApplicant",
    ECONOMIC_CONTRACT: "economicContract",
    OAK_JOURNAL: "oakJournal",
    THESIS_CATEGORY: "thesisCategory",
    SCIENTIFIC_TEMPLATE: "scientificTemplate",
    H_INDEX: "hIndex",
    SCIENTIFIC_DEGREE: "scientificDegree",
    SCIENTIFIC_TITLE: "scientificTitle",
    DEFENSE: "defense",
    EXAM_SPECIALTY: "examSpecialty",
    SCIENTIFIC_POST: "scientificPost",
    STARTUP: "startup",
    STARTUP_TYPE: "startupType",
    SCIENTIFIC_PORTAL: "scientificPortal",

    INDICATOR: "indicator",
    INDICATOR_SUBMISSION: "indicatorSubmission",
    EQ_INDICATOR: "eqIndicator",
    EQ_SUBMISSION: "eqSubmission",
    EQ_ANNOUNCEMENT: "eqAnnouncement",
    EQ_REPORT: "eqReport",

    GIFTED_STUDENT: "giftedStudent",
    EVALUATION_CRITERIA: "evaluationCriteria",
    STUDENT_ACHIEVEMENT: "studentAchievement",
    SCHOLARSHIP_APPLICATION: "scholarshipApplication",
    SCHOLARSHIP: "scholarship",
    DOCUMENT_TYPE: "documentType",

    PRACTICE: "practice",
    MEDICAL_ORGANIZATION: "medicalOrganization",
    ORG_TYPE: "orgType",
    PROVINCE: "province",
    REGION: "region",
    PRACTICE_STUDENT: "practiceStudent",

    TASK: "task",
    TASK_CATEGORY: "taskCategory",
    ANNOUNCEMENT: "announcement",
    CHAT: "chat",
    APPROVAL_CHAIN: "approvalChain",
    REPORT: "report",
    INTERNATIONAL_ADMISSION: "internationalAdmission",
    COUNTRY: "country",
    PUBLIC_OFFER: "publicOffer",
    LANGUAGE_OF_INSTRUCTION: "languageOfInstruction",

    ADMISSION_SEASON: "admissionSeason",
    ADMISSION_DIRECTION: "admissionDirection",
    ADMISSION_EDUCATION_FORM: "admissionEducationForm",
    ADMISSION_EDUCATION_LANGUAGE: "admissionEducationLanguage",
    ADMISSION_COUNTRY: "admissionCountry",
    ADMISSION_OFFER: "admissionOffer",
    ADMISSION_MESSAGE: "admissionMessage",

    NOTIFICATION: "notification",
    NOTIFICATION_PREFERENCE: "notificationPreference",

    SLA_CONFIG: "slaConfig",
  },

  ACTIONS: {
    CREATE: "create",
    READ: "read",
    READ_ALL: "readAll",
    UPDATE: "update",
    DELETE: "delete",
    APPROVE: "approve",
    REJECT: "reject",
    SIGN: "sign",
    EXPORT: "export",
    SEARCH: "search",
    FILTER: "filter",
    ID_FILTER: "idFilter",
    CHANGE_STATUS: "changeStatus",
    READ_OWN: "readOwn",
    REVIEW: "review",
    SCORE: "score",
    DASHBOARD: "dashboard",
    MANAGE_MEMBERS: "manageMembers",
    SUBMIT_WORK: "submitWork",
    NOTIFICATIONS: "notifications",
    GRANT_ANY: "grantAny",
  },

  LESSON_TYPES: {
    MARUZA: "maruza",
    AMALIY: "amaliy",
    LABORATORIYA: "laboratoriya",
    SEMINAR: "seminar",
    KLINIK_AMALIYOT: "klinik_amaliyot",
    MUSTAQIL_ISH: "mustaqil_ish",
  },

  PAGINATION: {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 10,
    MAX_LIMIT: 100,
  },

  FILE_LIMITS: {
    MAX_SIZE: 50 * 1024 * 1024,
    ALLOWED_TYPES: [
      "image/jpeg",
      "image/png",
      "image/jpg",
      "image/gif",
      "image/bmp",
      "image/webp",
      "image/heic",
      "image/heif",

      "video/mp4",
      "video/mpeg",
      "video/quicktime",
      "video/x-msvideo",
      "video/x-flv",
      "video/x-matroska",
      "video/webm",

      "audio/mpeg",
      "audio/ogg",
      "audio/midi",
      "audio/x-wav",
      "audio/3gpp",
      "audio/webm",

      "application/pdf",
      "application/msword",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "application/vnd.ms-excel",
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "application/vnd.ms-powerpoint",
      "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      "application/rtf",

      "text/plain",

      "application/zip",
      "application/x-rar-compressed",
      "application/x-tar",
      "application/x-7z-compressed",
    ],
    ALLOWED_EXTENSIONS: [
      ".jpeg",
      ".jpg",
      ".png",
      ".gif",
      ".bmp",
      ".webp",
      ".heic",
      ".mp4",
      ".mpeg",
      ".mov",
      ".avi",
      ".flv",
      ".mkv",
      ".mp3",
      ".ogg",
      ".midi",
      ".wav",
      ".3gpp",
      ".webm",
      ".pdf",
      ".doc",
      ".docx",
      ".xls",
      ".xlsx",
      ".ppt",
      ".pptx",
      ".rtf",
      ".zip",
      ".rar",
      ".tar",
      ".7z",
      ".txt",
    ],
  },

  QUALIFICATION_TYPES: [72, 36, 144, 504, 720],

  PAYMENT_METHODS: {
    CLICK: "click",
    PAYME: "payme",
    BANK: "bank",
  },

  EDUCATION_TYPES: {
    KUNDUZGI: "kunduzgi",
    SIRTQI: "sirtqi",
  },

  ATTENDANCE_STATUSES: {
    PRESENT: "present",
    ABSENT: "absent",
    EXCUSED: "excused",
  },

  ASSESSMENT_TYPES: {
    ORALIQ: "oraliq",
    YAKUNIY: "yakuniy",
    ATTESTATSIYA: "attestatsiya",
  },

  SCIENTIFIC_WORK_STATUSES: {
    SUBMITTED: "submitted",
    UNDER_REVIEW: "under_review",
    SEMINAR: "seminar",
    REVISION: "revision",
    APPROVED: "approved",
    REJECTED: "rejected",
  },

  ARTICLE_TYPES: {
    SCOPUS: "scopus",
    OAK: "oak",
    NATIONAL: "national",
  },

  RANK_TYPES: {
    DOTSENT: "dotsent",
    PROFESSOR: "professor",
  },

  CERTIFICATE_TYPES: {
    SERTIFIKAT: "sertifikat",
    MALUMOTNOMA: "malumotnoma",
  },

  RESOURCE_CATEGORIES: {
    VIDEO: "video",
    PRESENTATION: "presentation",
    LECTURE: "lecture",
    IMAGE: "image",
  },
};
