"use strict";

const { runModuleSeed, CRUD_ACTIONS } = require("./_module-permission-lib");
const { MODULES, ACTIONS } = require("../src/config/constants");

const SECTIONS = [
  MODULES.INTERNATIONAL_ADMISSION,
  MODULES.ADMISSION_SEASON,
  MODULES.ADMISSION_DIRECTION,
  MODULES.ADMISSION_EDUCATION_FORM,
  MODULES.ADMISSION_EDUCATION_LANGUAGE,
  MODULES.ADMISSION_COUNTRY,
  MODULES.ADMISSION_OFFER,
  MODULES.ADMISSION_MESSAGE,
];

const ACTIONS_OVERRIDE = {
  [MODULES.INTERNATIONAL_ADMISSION]: [
    ...CRUD_ACTIONS,
    ACTIONS.APPROVE,
    ACTIONS.REJECT,
    ACTIONS.EXPORT,
  ],

  [MODULES.ADMISSION_SEASON]: [...CRUD_ACTIONS, ACTIONS.CHANGE_STATUS],

  [MODULES.ADMISSION_DIRECTION]: CRUD_ACTIONS,
  [MODULES.ADMISSION_EDUCATION_FORM]: CRUD_ACTIONS,
  [MODULES.ADMISSION_EDUCATION_LANGUAGE]: CRUD_ACTIONS,
  [MODULES.ADMISSION_COUNTRY]: CRUD_ACTIONS,

  [MODULES.ADMISSION_OFFER]: [ACTIONS.READ, ACTIONS.READ_ALL, ACTIONS.UPDATE],

  [MODULES.ADMISSION_MESSAGE]: [
    ACTIONS.CREATE,
    ACTIONS.READ,
    ACTIONS.READ_ALL,
    ACTIONS.SEARCH,
    ACTIONS.FILTER,
    ACTIONS.EXPORT,
  ],
};

const TITLES = {
  [MODULES.INTERNATIONAL_ADMISSION]: "Xorijiy qabul (4.8)",
  [MODULES.ADMISSION_SEASON]: "Qabul mavsumlari (4.8)",
  [MODULES.ADMISSION_DIRECTION]: "Qabul yo'nalishlari (4.8)",
  [MODULES.ADMISSION_EDUCATION_FORM]: "Qabul ta'lim shakllari (4.8)",
  [MODULES.ADMISSION_EDUCATION_LANGUAGE]: "Qabul ta'lim tillari (4.8)",
  [MODULES.ADMISSION_COUNTRY]: "Qabul davlatlari (4.8)",
  [MODULES.ADMISSION_OFFER]: "Qabul ommaviy ofertasi (4.8)",
  [MODULES.ADMISSION_MESSAGE]: "Abituriyent xabarlari (4.8)",
};

runModuleSeed({
  label: "4.8 Xalqaro qabul",
  groupCode: "4.8",
  sections: SECTIONS,
  actionsOverride: ACTIONS_OVERRIDE,
  titles: TITLES,
});
