"use strict";

const {
  runModuleSeed,
  CRUD_ACTIONS,
  APPROVAL_ACTIONS,
  APPROVAL_WITH_STATUS,
} = require("./_module-permission-lib");
const { MODULES } = require("../src/config/constants");

const SECTIONS = [
  MODULES.STUDY_PLAN,
  MODULES.WORKING_PLAN,
  MODULES.WORKING_SCHEDULE,
  MODULES.WORKLOAD,
  MODULES.WORKLOAD_DISTRIBUTION,
  MODULES.WORKLOAD_SUMMARY,
  MODULES.CONTINGENT_REPORT,
  MODULES.DEPARTMENT_CONTINGENT,
  MODULES.SYLLABUS,
  MODULES.SCIENCE_PROGRAM,
  MODULES.LEARNING_PROCESS,
  MODULES.TEACHER_LEAVE,
  MODULES.SCHEDULE,
  MODULES.TIME_SLOT,
];

const ACTIONS_OVERRIDE = {
  [MODULES.STUDY_PLAN]: APPROVAL_ACTIONS,
  [MODULES.WORKING_PLAN]: APPROVAL_ACTIONS,
  [MODULES.WORKING_SCHEDULE]: APPROVAL_ACTIONS,
  [MODULES.WORKLOAD]: APPROVAL_WITH_STATUS,
  [MODULES.WORKLOAD_DISTRIBUTION]: APPROVAL_WITH_STATUS,
  [MODULES.WORKLOAD_SUMMARY]: APPROVAL_ACTIONS,
  [MODULES.CONTINGENT_REPORT]: APPROVAL_ACTIONS,
  [MODULES.SYLLABUS]: APPROVAL_ACTIONS,
  [MODULES.SCIENCE_PROGRAM]: APPROVAL_ACTIONS,
  [MODULES.LEARNING_PROCESS]: APPROVAL_ACTIONS,
  [MODULES.TEACHER_LEAVE]: APPROVAL_ACTIONS,
};

const TITLES = {
  [MODULES.STUDY_PLAN]: "O'quv reja",
  [MODULES.WORKING_PLAN]: "Ishchi o'quv reja",
  [MODULES.WORKING_SCHEDULE]: "Ishchi o'quv jadval",
  [MODULES.WORKLOAD]: "O'quv yuklamasi",
  [MODULES.WORKLOAD_DISTRIBUTION]: "Yuklama taqsimoti",
  [MODULES.WORKLOAD_SUMMARY]: "Kafedralar soatlar hisobi",
  [MODULES.CONTINGENT_REPORT]: "Talabalar kontingenti hisoboti",
  [MODULES.DEPARTMENT_CONTINGENT]: "Kafedra kontingenti",
  [MODULES.SYLLABUS]: "Sillabus",
  [MODULES.SCIENCE_PROGRAM]: "Fan dasturi",
  [MODULES.LEARNING_PROCESS]: "O'quv jarayoni",
  [MODULES.TEACHER_LEAVE]: "O'qituvchi arizalari (4.2.9)",
  [MODULES.SCHEDULE]: "Dars jadvali",
  [MODULES.TIME_SLOT]: "Vaqt oraliqlari",
};

runModuleSeed({
  label: "4.2 O'quv yuklamasi",
  groupCode: "4.2",
  sections: SECTIONS,
  actionsOverride: ACTIONS_OVERRIDE,
  titles: TITLES,
});
