"use strict";

const {
  runModuleSeed,
  CRUD_ACTIONS,
  APPROVAL_ACTIONS,
} = require("./_module-permission-lib");
const { MODULES, ACTIONS } = require("../src/config/constants");

const SECTIONS = [
  MODULES.RESIDENT,
  MODULES.RESIDENCY_SPECIALTY,
  MODULES.RESIDENCY_ACTIVITY_PLAN,
  MODULES.RESIDENCY_DISSERTATION_PLAN,
  MODULES.RESIDENCY_THEORY_TOPIC,
  MODULES.RESIDENCY_SKILL,
  MODULES.RESIDENCY_ATTESTATION,
  MODULES.RESIDENCY_CURRICULUM,
  MODULES.RESIDENCY_LESSON,
  MODULES.RESIDENCY_NOTICE,
  MODULES.RESIDENCY_PROBLEM_STUDENT,
  MODULES.RESIDENCY_ANNOUNCEMENT,
  MODULES.RESIDENCY_REPORT,
  MODULES.RESIDENT_APPLICATION,
  MODULES.RESIDENT_ATTENDANCE,
  MODULES.RESIDENT_DAILY_LOG,
  MODULES.RESIDENT_ASSESSMENT,
  MODULES.RESIDENT_RESOURCE,
  MODULES.RESIDENCY_OPEN_LESSON,
];

const ACTIONS_OVERRIDE = {
  [MODULES.RESIDENT]: [...CRUD_ACTIONS, ACTIONS.EXPORT, ACTIONS.CHANGE_STATUS],
  [MODULES.RESIDENCY_ACTIVITY_PLAN]: APPROVAL_ACTIONS,
  [MODULES.RESIDENCY_DISSERTATION_PLAN]: APPROVAL_ACTIONS,
  [MODULES.RESIDENCY_NOTICE]: APPROVAL_ACTIONS,
  [MODULES.RESIDENCY_REPORT]: [ACTIONS.READ_ALL],
  [MODULES.RESIDENT_APPLICATION]: APPROVAL_ACTIONS,
  [MODULES.RESIDENT_DAILY_LOG]: APPROVAL_ACTIONS,
  [MODULES.RESIDENT_ASSESSMENT]: [...CRUD_ACTIONS, ACTIONS.EXPORT, ACTIONS.SCORE],
  [MODULES.RESIDENT_ATTENDANCE]: [...CRUD_ACTIONS, ACTIONS.APPROVE],
};

const TITLES = {
  [MODULES.RESIDENT]: "Rezidentlar",
  [MODULES.RESIDENCY_SPECIALTY]: "Rezidentura mutaxassisliklari",
  [MODULES.RESIDENCY_ACTIVITY_PLAN]: "Faoliyat rejasi",
  [MODULES.RESIDENCY_DISSERTATION_PLAN]: "Dissertatsiya rejasi",
  [MODULES.RESIDENCY_THEORY_TOPIC]: "Nazariy va umumiy bilim",
  [MODULES.RESIDENCY_SKILL]: "Klinik ko'nikmalar",
  [MODULES.RESIDENCY_ATTESTATION]: "Attestatsiyalar",
  [MODULES.RESIDENCY_CURRICULUM]: "O'quv reja",
  [MODULES.RESIDENCY_LESSON]: "Umumiy darslar",
  [MODULES.RESIDENCY_NOTICE]: "Bildirgilar",
  [MODULES.RESIDENCY_PROBLEM_STUDENT]: "Muammoli talabalar",
  [MODULES.RESIDENCY_ANNOUNCEMENT]: "Rezidentura e'lonlari",
  [MODULES.RESIDENCY_REPORT]: "Rezidentura hisobotlari",
  [MODULES.RESIDENT_APPLICATION]: "Rezident arizalari",
  [MODULES.RESIDENT_ATTENDANCE]: "Rezident davomati",
  [MODULES.RESIDENT_DAILY_LOG]: "Klinik kundalik",
  [MODULES.RESIDENT_ASSESSMENT]: "Rezident baholash",
  [MODULES.RESIDENT_RESOURCE]: "Rezident manbalari",
  [MODULES.RESIDENCY_OPEN_LESSON]: "Ochiq dars biriktirish",
};

runModuleSeed({
  label: "4.5 Magistratura va klinik ordinatura",
  groupCode: "4.5",
  sections: SECTIONS,
  actionsOverride: ACTIONS_OVERRIDE,
  titles: TITLES,
});
