import { lazy } from 'react';
import {
  ExperimentOutlined,
  TeamOutlined,
  FileTextOutlined,
  AppstoreOutlined,
  UserOutlined,
  FileDoneOutlined,
  CalendarOutlined,
  TrophyOutlined,
  SettingOutlined,
  ProfileOutlined,
  NumberOutlined,
  FormOutlined,
} from '@ant-design/icons';
import { Navigate } from 'react-router-dom';
import { defineModule } from '@/shared/lib/module';

const NotificationsRedirect = () => <Navigate to="/bildirishnomalar" replace />;

export default defineModule({
  name: 'science-council',
  menuGroup: { titleKey: 'menuGroup.scienceCouncil', order: 50 },
  routes: [
    { index: true, permission: 'scienceCouncil:dashboard', element: lazy(() => import('./pages/dashboard-page')) },
    { path: 'works', permission: 'scienceCouncil:readAll', element: lazy(() => import('./pages/works-list-page')) },
    { path: 'works/:id', permission: 'scienceCouncil:read', element: lazy(() => import('./pages/work-detail-page')) },
    { path: 'seminars', permission: 'scienceCouncil:changeStatus', element: lazy(() => import('./pages/seminars-page')) },
    { path: 'defenses', permission: 'scienceCouncil:changeStatus', element: lazy(() => import('./pages/defenses-page')) },
    { path: 'members', permission: 'scienceCouncil:manageMembers', element: lazy(() => import('./pages/members-page')) },
    { path: 'documents', permission: 'scienceCouncil:read', element: lazy(() => import('./pages/documents-page')) },
    { path: 'settings/work-documents', permission: 'scienceCouncil:read', element: lazy(() => import('./pages/documents-page')) },
    { path: 'settings/specialties', permission: 'scienceCouncil:read', element: lazy(() => import('./pages/specialties-page')) },
    { path: 'settings/council-numbers', permission: 'scienceCouncil:read', element: lazy(() => import('./pages/council-numbers-page')) },
    { path: 'settings/application-template', permission: 'scienceCouncil:read', element: lazy(() => import('./pages/application-template-page')) },
    { path: 'notifications', element: NotificationsRedirect },
    { path: 'assigned', permission: 'scienceCouncil:review', element: lazy(() => import('./pages/assigned-works-page')) },
    { path: 'my-work', permission: 'scienceCouncil:submitWork', element: lazy(() => import('./pages/my-work-page')) },
    { path: 'ariza', public: true, element: lazy(() => import('./pages/public-application-page')) },
  ],
  menu: [
    { titleKey: 'scienceCouncil.nav.dashboard', icon: <AppstoreOutlined />, path: '/science-council', order: 60, permission: 'scienceCouncil:dashboard' },
    {
      titleKey: 'scienceCouncil.nav.works',
      icon: <ExperimentOutlined />,
      path: '/science-council/works-group',
      order: 61,
      permission: ['scienceCouncil:readAll', 'scienceCouncil:changeStatus'],
    },
    { titleKey: 'scienceCouncil.nav.works', icon: <ExperimentOutlined />, path: '/science-council/works', order: 61, permission: 'scienceCouncil:readAll', parent: '/science-council/works-group' },
    { titleKey: 'scienceCouncil.nav.seminars', icon: <CalendarOutlined />, path: '/science-council/seminars', order: 62, permission: 'scienceCouncil:changeStatus', parent: '/science-council/works-group' },
    { titleKey: 'scienceCouncil.nav.defenses', icon: <TrophyOutlined />, path: '/science-council/defenses', order: 63, permission: 'scienceCouncil:changeStatus', parent: '/science-council/works-group' },
    { titleKey: 'scienceCouncil.nav.members', icon: <TeamOutlined />, path: '/science-council/members', order: 63, permission: 'scienceCouncil:manageMembers' },
    { titleKey: 'scienceCouncil.nav.settings', icon: <SettingOutlined />, path: '/science-council/settings-group', order: 64, permission: 'scienceCouncil:readAll' },
    { titleKey: 'scienceCouncil.nav.specialties', icon: <ProfileOutlined />, path: '/science-council/settings/specialties', order: 64.1, permission: 'scienceCouncil:readAll', parent: '/science-council/settings-group' },
    { titleKey: 'scienceCouncil.nav.workDocuments', icon: <FileTextOutlined />, path: '/science-council/settings/work-documents', order: 64.2, permission: 'scienceCouncil:readAll', parent: '/science-council/settings-group' },
    { titleKey: 'scienceCouncil.nav.councilNumbers', icon: <NumberOutlined />, path: '/science-council/settings/council-numbers', order: 64.3, permission: 'scienceCouncil:readAll', parent: '/science-council/settings-group' },
    { titleKey: 'scienceCouncil.nav.applicationTemplate', icon: <FormOutlined />, path: '/science-council/settings/application-template', order: 64.4, permission: 'scienceCouncil:readAll', parent: '/science-council/settings-group' },
    { titleKey: 'scienceCouncil.nav.assigned', icon: <FileDoneOutlined />, path: '/science-council/assigned', order: 65, permission: 'scienceCouncil:review' },
    { titleKey: 'scienceCouncil.nav.myWork', icon: <UserOutlined />, path: '/science-council/my-work', order: 66, permission: 'scienceCouncil:submitWork' },
  ],
  i18n: {
    uz: {
      'menuGroup.scienceCouncil': 'Ilmiy kengash',
      'scienceCouncil.nav.dashboard': 'Boshqaruv paneli',
      'scienceCouncil.nav.works': 'Ilmiy ishlar',
      'scienceCouncil.nav.members': "Kengash a'zolari",
      'scienceCouncil.nav.documents': 'Hujjatlar',
      'scienceCouncil.form.scientificTitle': 'Ilmiy unvon',
      'scienceCouncil.form.scientificTitlePlaceholder': 'Masalan: dotsent',
      'scienceCouncil.form.selectScientificTitle': 'Ilmiy unvonni tanlang',
      'scienceCouncil.form.selectDegree': 'Ilmiy darajani tanlang',
      'scienceCouncil.form.refEmpty': "Ma'lumotnoma bo'sh \u2014 administrator to'ldirishi kerak",
      'scienceCouncil.form.specialtyTitle': 'Ixtisoslik nomi',
      'scienceCouncil.form.specialtyCode': 'Ixtisoslik shifri',
      'scienceCouncil.form.selectSpecialty': 'Ixtisoslikni tanlang',
      'scienceCouncil.form.selectCode': 'Shifrni tanlang',
      'scienceCouncil.form.email': 'Elektron pochta',
      'scienceCouncil.form.emailPlaceholder': 'masalan: rahbar@example.uz',
      'scienceCouncil.form.emailInvalid': "Elektron pochta noto'g'ri",
      'scienceCouncil.form.phone': 'Telefon raqami',
      'scienceCouncil.form.phonePlaceholder': '+998 90 123 45 67',
      'scienceCouncil.nav.settings': 'Sozlamalar',
      'scienceCouncil.nav.specialties': 'Ixtisosliklar',
      'scienceCouncil.nav.workDocuments': 'Ilmiy ish hujjatlari',
      'scienceCouncil.nav.councilNumbers': 'Ilmiy kengash raqamlari',
      'scienceCouncil.nav.applicationTemplate': 'Ariza namunasi',
      'scienceCouncil.settings.add': "Qo'shish",
      'scienceCouncil.settings.saved': 'Saqlandi',
      'scienceCouncil.settings.added': "Qo'shildi",
      'scienceCouncil.settings.deleted': "O'chirildi",
      'scienceCouncil.settings.saveFailed': 'Saqlashda xatolik',
      'scienceCouncil.settings.deleteFailed': "O'chirishda xatolik",
      'scienceCouncil.settings.status': 'Holati',
      'scienceCouncil.settings.active': 'Faol',
      'scienceCouncil.settings.inactive': 'Nofaol',
      'scienceCouncil.settings.specialtyTitle': 'Ixtisoslik nomi',
      'scienceCouncil.settings.specialtyTitlePh': 'Masalan: Pediatriya',
      'scienceCouncil.settings.specialtyCode': 'Ixtisoslik shifri',
      'scienceCouncil.settings.specialtyCodePh': 'Masalan: 14.00.09',
      'scienceCouncil.settings.branch': "Fan tarmog'i",
      'scienceCouncil.settings.branchPh': 'Masalan: Tibbiyot fanlari',
      'scienceCouncil.settings.searchSpecialty': "Nom yoki shifr bo'yicha qidirish",
      'scienceCouncil.settings.newSpecialty': 'Yangi ixtisoslik',
      'scienceCouncil.settings.editSpecialty': 'Ixtisoslikni tahrirlash',
      'scienceCouncil.settings.deleteSpecialty': "Ixtisoslik o'chirilsinmi?",
      'scienceCouncil.settings.deleteSpecialtyDesc':
        "Kengash raqamiga biriktirilgan ixtisoslikni o'chirib bo'lmaydi.",
      'scienceCouncil.settings.councilNumber': 'Ilmiy kengash raqami',
      'scienceCouncil.settings.councilNumberPh': 'Masalan: DSc.03/30.12.2019.Tib.50.01',
      'scienceCouncil.settings.attachedCodes': 'Biriktirilgan ixtisoslik shifri',
      'scienceCouncil.settings.attachedCodesPh': 'Ixtisosliklarni tanlang',
      'scienceCouncil.settings.attachedCodesHint':
        "Bir nechtasini tanlash mumkin. Faqat BO'SH ixtisosliklar chiqadi — bitta ixtisoslik ayni paytda faqat bitta FAOL raqamga biriktiriladi.",
      'scienceCouncil.settings.viewCodes': "Biriktirilgan ixtisosliklarni ko'rish",
      'scienceCouncil.settings.noFreeCodes': "Bo'sh ixtisoslik qolmadi",
      'scienceCouncil.settings.searchNumber': "Kengash raqami bo'yicha qidirish",
      'scienceCouncil.settings.newNumber': 'Yangi kengash raqami',
      'scienceCouncil.settings.editNumber': 'Kengash raqamini tahrirlash',
      'scienceCouncil.settings.deleteNumber': "Kengash raqami o'chirilsinmi?",
      'scienceCouncil.settings.deleteNumberDesc': "Bu amalni bekor qilib bo'lmaydi.",
      'scienceCouncil.settings.templateInfo':
        "Ushbu ariza namunasi pdf formatda, o'z ilmiy ishini himoya qilishga ariza topshirmoqchi bo'lgan tadqiqotchining tegishli sahifasida ko'rinadi.",
      'scienceCouncil.settings.templateField': 'Ariza namunasi',
      'scienceCouncil.settings.templateEmpty': 'Namuna yuklanmagan',
      'scienceCouncil.settings.templateEmptyHint':
        "Tadqiqotchiga ko'rsatish uchun PDF namunani yuklang",
      'scienceCouncil.settings.templateUpload': 'Yuklash',
      'scienceCouncil.settings.templateReplace': 'Almashtirish',
      'scienceCouncil.settings.templateDownload': 'Yuklab olish',
      'scienceCouncil.settings.templateUploaded': 'Ariza namunasi yuklandi',
      'scienceCouncil.settings.templateFailed': 'Namunani yuklashda xatolik',
      'scienceCouncil.settings.deleteTemplate': "Ariza namunasi o'chirilsinmi?",
      'scienceCouncil.apply.templateTitle': 'Ariza namunasi',
      'scienceCouncil.apply.templateHint':
        "Namunani yuklab oling, to'ldiring va imzolangan PDF nusxasini biriktiring.",
      'scienceCouncil.nav.assigned': 'Biriktirilgan ishlar',
      'scienceCouncil.nav.myWork': 'Mening ilmiy ishlarim',
      'scienceCouncil.nav.notifications': 'Bildirishnomalar',
      'scienceCouncil.notifications.newWork': 'Yangi ilmiy ish topshirildi',
      'scienceCouncil.notifications.pendingReview': "Ko'rib chiqish kutilmoqda",
      'scienceCouncil.notifications.revision': "Qayta ishlashga qaytarildi",
      'scienceCouncil.notifications.approved': 'Ilmiy ish tasdiqlandi',
      'scienceCouncil.notifications.rejected': 'Hujjat rad etildi',
      'scienceCouncil.notifications.newDoc': 'Yangi hujjat yuklandi',
      'scienceCouncil.notifications.newReview': 'Yangi xulosa qoldirildi',
      'scienceCouncil.notifications.empty': 'Bildirishnomalar yo\'q',
      'scienceCouncil.notifications.unreadCount': '{count} ta o\'qilmagan bildirishnoma',
      'scienceCouncil.notifications.allRead': 'Barcha bildirishnomalar o\'qilgan',
      'scienceCouncil.notifications.markAllRead': 'Barchasini o\'qilgan deb belgilash',
      'scienceCouncil.title': 'Ilmiy kengash',
      'scienceCouncil.work.title': 'Ilmiy ish nomi',
      'scienceCouncil.work.author': 'Muallif',
      'scienceCouncil.work.status': 'Holat',
      'scienceCouncil.work.year': "O'quv yili",
      'scienceCouncil.work.type': 'Turi',
      'scienceCouncil.work.create': 'Yangi ilmiy ish',
      'scienceCouncil.work.edit': 'Tahrirlash',
      'scienceCouncil.work.authorType': 'Muallif turi',
      'scienceCouncil.work.date': 'Sana',
      'scienceCouncil.work.reviews': 'Xulosalar',
      'scienceCouncil.work.internal': 'Ichki',
      'scienceCouncil.work.external': 'Tashqi',
      'scienceCouncil.status.new': 'Yangi',
      'scienceCouncil.status.accepted': 'Tekshirish boshlanmagan',
      'scienceCouncil.status.pending': 'Tekshirilmoqda',
      'scienceCouncil.status.reviewed': 'Tekshirilgan',
      'scienceCouncil.status.not_evaluated': 'Baholanmagan',
      'scienceCouncil.status.not_recommended': "Seminarga qo'yilmagan",
      'scienceCouncil.status.rejected': 'Rad etilgan',
      'scienceCouncil.status.revision': "Qayta ko'rib chiqish",
      'scienceCouncil.tab.info': 'Umumiy',
      'scienceCouncil.tab.documents': 'Hujjatlar',
      'scienceCouncil.tab.members': "Kengash a'zolari",
      'scienceCouncil.tab.reviews': 'Xulosalar',
      'scienceCouncil.tab.protocol': 'Dalolatnoma',
      'scienceCouncil.tab.audit': 'Audit jurnali',
      'scienceCouncil.review.add': 'Xulosa qoldirish',
      'scienceCouncil.review.positive': 'Ijobiy',
      'scienceCouncil.review.neutral': 'Neytral',
      'scienceCouncil.review.negative': 'Salbiy',
      'scienceCouncil.decision.seminar': 'Seminarga tavsiya etish',
      'scienceCouncil.decision.revision': 'Qayta ishlashga qaytarish',
      'scienceCouncil.decision.reject': 'Rad etish',
      'scienceCouncil.protocol.generate': 'Dalolatnoma yaratish',
      'scienceCouncil.protocol.sign': 'E-imzo bilan tasdiqlash',
      'scienceCouncil.protocol.finalConclusion': 'Yakuniy xulosa',
      'scienceCouncil.protocol.intro': 'Kirish qismi',
      'scienceCouncil.protocol.introPlaceholder':
        "Muassasa, tadqiqotchi, ilmiy ish nomi va ixtisoslik ko'rsatilgan kirish matni",
      'scienceCouncil.protocol.noIntroYet': "kirish qismi kiritilmagan",
      'scienceCouncil.protocol.noReviewsYet': "Kengash a'zolari hali xulosa yozmagan",
      'scienceCouncil.protocol.short': 'Dalolatnoma',
      'scienceCouncil.protocol.download': 'Dalolatnomani PDF sifatida saqlash',
      'scienceCouncil.protocol.downloadDraft':
        "Dalolatnoma hali yaratilmagan — loyiha nusxasini PDF sifatida saqlash",
      'scienceCouncil.protocol.pdf': 'PDF',
      'scienceCouncil.protocol.downloadFailed': "Dalolatnomani tayyorlashda xatolik",
      'scienceCouncil.protocol.title': 'DALOLATNOMA',
      'scienceCouncil.protocol.subtitle': 'Ilmiy-tadqiqot ishini dastlabki hujjatlarni tekshirish',
      'scienceCouncil.protocol.date': 'Sana',
      'scienceCouncil.protocol.institution': "Farg'ona jamoat salomatligi tibbiyot instituti",
      'scienceCouncil.protocol.work': 'Ilmiy ish',
      'scienceCouncil.protocol.researcher': 'Tadqiqotchi',
      'scienceCouncil.protocol.memberReviews': "Kengash a'zolari xulosalari",
      'scienceCouncil.protocol.awaitingReview': 'xulosa kutilmoqda',
      'scienceCouncil.protocol.docChecked': 'mavjudligi tekshirildi',
      'scienceCouncil.protocol.noConclusionYet': 'Yakuniy xulosa kiritilmagan',
      'scienceCouncil.protocol.conclusionPlaceholder': "Kengash a'zolari xulosalari asosida yakuniy xulosani kiriting...",
      'scienceCouncil.protocol.viewFull': "Dalolatnomani to'liq ko'rish",
      'scienceCouncil.protocol.viewFullDesc': "Tekshirilgan hujjatlar, kengash a'zolari xulosalari va yakuniy tavsiya",
      'scienceCouncil.protocol.view': "Ko'rish",
      'scienceCouncil.protocol.close': 'Yopish',
      'scienceCouncil.protocol.signed': 'Dalolatnoma E-imzo bilan imzolangan',
      'scienceCouncil.protocol.signedBy': 'Imzolagan',
      'scienceCouncil.protocol.signedDate': 'Imzolangan sana',
      'scienceCouncil.protocol.certificate': 'Sertifikat (CN)',
      'scienceCouncil.protocol.cryptoSign': 'Kriptografik imzo',
      'scienceCouncil.protocol.immutableWarning': "Bu dalolatnoma E-imzo bilan tasdiqlangan va o'zgartirib bo'lmaydi",
      'scienceCouncil.protocol.eSignConfirm': 'E-imzo bilan tasdiqlash',
      'scienceCouncil.protocol.eSignDesc': "Ushbu dalolatnomani E-imzo bilan imzolashni tasdiqlaysizmi? Imzolangandan so'ng mazmunni o'zgartirib bo'lmaydi.",
      'scienceCouncil.protocol.signing': 'Imzolanmoqda...',
      'scienceCouncil.protocol.previewTitle': "Dalolatnoma ko'rib chiqish va E-imzo",
      'scienceCouncil.stats.total': 'Jami ishlar',
      'scienceCouncil.table.rows': 'Jadval qatorlari',
      'scienceCouncil.stats.new': 'Yangi',
      'scienceCouncil.stats.pending': 'Tekshirilmoqda',
      'scienceCouncil.stats.approved': 'Tasdiqlangan',
      'scienceCouncil.stats.rejected': 'Rad etilgan',
      'scienceCouncil.stats.revision': 'Qayta ishlashda',
      'scienceCouncil.member.name': 'Ism',
      'scienceCouncil.member.type': "A'zo turi",
      'scienceCouncil.member.position': 'Lavozim',
      'scienceCouncil.member.degree': 'Ilmiy daraja',
      'scienceCouncil.member.organization': 'Tashkilot',
      'scienceCouncil.member.email': 'Email',
      'scienceCouncil.member.phone': 'Telefon',
      'scienceCouncil.member.assigned': 'Biriktirilgan ishlar',
      'scienceCouncil.member.assignedWorks': 'Biriktirilgan ilmiy ishlar',
      'scienceCouncil.member.status': 'Holat',
      'scienceCouncil.member.active': 'Faol',
      'scienceCouncil.member.inactive': 'Nofaol',
      'scienceCouncil.member.addMember': "A'zo qo'shish",
      'scienceCouncil.member.editMember': "A'zoni tahrirlash",
      'scienceCouncil.member.deleteMember': "A'zoni o'chirish",
      'scienceCouncil.member.deleteConfirm': "Ushbu a'zoni o'chirib tashlashni xohlaysizmi? Bu amalni qaytarib bo'lmaydi.",
      'scienceCouncil.member.deleteWarning': "Diqqat: bu a'zo {count} ta ishga biriktirilgan.",
      'scienceCouncil.member.searchPlaceholder': 'Ism yoki tashkilot...',
      'scienceCouncil.member.noAssigned': 'Hali ish biriktirilmagan',
      'scienceCouncil.member.review': 'xulosa',
      'scienceCouncil.member.works': 'ta ish',
      'scienceCouncil.member.fullNamePlaceholder': 'Familiya Ism Sharif',
      'scienceCouncil.member.degreePlaceholder': 'Tibbiyot fanlari doktori...',
      'scienceCouncil.member.added': "A'zo qo'shildi!",
      'scienceCouncil.member.saveFailed': "A'zoni saqlashda xatolik",
      'scienceCouncil.member.councilNumberHint': "Shifrlarni toraytirish uchun (saqlanmaydi)",
      'scienceCouncil.member.deleteFailed': "A'zoni o'chirishda xatolik",
      'scienceCouncil.member.updated': "A'zo ma'lumotlari yangilandi!",
      'scienceCouncil.member.deleted': "A'zo o'chirildi",
      'scienceCouncil.member.total': 'Jami',
      'scienceCouncil.doc.upload': 'Yuklash',
      'scienceCouncil.doc.uploaded': 'Yuklangan',
      'scienceCouncil.doc.notUploaded': 'Yuklanmagan',
      'scienceCouncil.doc.totalTypes': 'Jami hujjat turi',
      'scienceCouncil.doc.requiredDocs': 'Majburiy',
      'scienceCouncil.doc.optionalDocs': 'Ixtiyoriy',
      'scienceCouncil.doc.addCategory': "Hujjat kategoriyasi qo'shish",
      'scienceCouncil.doc.editCategory': 'Hujjat kategoriyasini tahrirlash',
      'scienceCouncil.doc.newCategory': 'Yangi hujjat kategoriyasi',
      'scienceCouncil.doc.docName': 'Hujjat nomi',
      'scienceCouncil.doc.docNamePlaceholder': 'Masalan: Avtoreferat',
      'scienceCouncil.doc.format': 'Format',
      'scienceCouncil.doc.isRequired': 'Majburiymi?',
      'scienceCouncil.doc.deleteConfirm': "Kategoriyani o'chirish?",
      'scienceCouncil.doc.deleteDesc': "Bu amal qaytarilmaydi.",
      'scienceCouncil.doc.deleteOk': "Ha, o'chirish",
      'scienceCouncil.doc.deleted': "Hujjat kategoriyasi o'chirildi",
      'scienceCouncil.doc.added': "Yangi hujjat kategoriyasi qo'shildi!",
      'scienceCouncil.doc.updated': "Hujjat kategoriyasi yangilandi!",
      'scienceCouncil.doc.hint': "Majburiy belgilangan hujjatlar bo'lmasa, o'qituvchi ilmiy ish topshira olmaydi.",
      'scienceCouncil.doc.anyFormat': 'Har qanday',
      'scienceCouncil.form.required': "Majburiy maydon",
      'scienceCouncil.form.titlePlaceholder': 'Ilmiy ish nomini kiriting...',
      'scienceCouncil.form.division': "Bo'lim (akademik bo'lmagan)",
      'scienceCouncil.form.divisionTooltip': "Buxgalteriya, Kadrlar kabi bo'limlar uchun",
      'scienceCouncil.form.selectDivision': "Bo'limni tanlang",
      'scienceCouncil.form.faculty': 'Fakultet',
      'scienceCouncil.form.selectFaculty': 'Fakultetni tanlang',
      'scienceCouncil.form.department': 'Kafedra',
      'scienceCouncil.form.selectDepartment': 'Kafedrani tanlang',
      'scienceCouncil.form.selectDivisionStaff': "Bo'lim xodimini tanlang",
      'scienceCouncil.form.selectFacultyFirst': "Avval fakultet/kafedra yoki bo'limni tanlang",
      'scienceCouncil.form.selectTeacher': "O'qituvchini tanlang",
      'scienceCouncil.form.fullName': 'F.I.Sh',
      'scienceCouncil.form.fullNamePlaceholder': 'Familiya Ism Sharif',
      'scienceCouncil.form.workplace': 'Ish joyi',
      'scienceCouncil.form.workplacePlaceholder': 'Tashkilot nomi',
      'scienceCouncil.form.position': 'Lavozimi',
      'scienceCouncil.form.positionPlaceholder': 'Lavozim',
      'scienceCouncil.form.academicTitle': 'Akademik unvon',
      'scienceCouncil.form.academicTitlePlaceholder': "Masalan: Dotsent",
      'scienceCouncil.form.degree': 'Ilmiy daraja',
      'scienceCouncil.form.degreePlaceholder': 'Masalan: PhD',
      'scienceCouncil.form.passportSeries': 'Pasport seriyasi',
      'scienceCouncil.form.passportNumber': 'Pasport raqami',
      'scienceCouncil.form.pinfl': 'PINFL (JSHSHIR)',
      'scienceCouncil.form.selectMembers': "Kengash a'zolarini tanlang",
      'scienceCouncil.form.supervisor': 'Ilmiy rahbar',
      'scienceCouncil.form.supervisorType': 'Rahbar turi',
      'scienceCouncil.form.selectSupervisor': 'Ilmiy rahbarni tanlang',
      'scienceCouncil.form.noStaffInUnit': "Tanlangan bo'linmada xodim yo'q — filtrni tozalang",
      'scienceCouncil.form.next': 'Keyingi',
      'scienceCouncil.form.back': 'Orqaga',
      'scienceCouncil.step.general': 'Umumiy',
      'scienceCouncil.step.author': 'Muallif',
      'scienceCouncil.step.supervisor': 'Ilmiy rahbar',
      'scienceCouncil.step.members': "Kengash a'zolari",
      'scienceCouncil.apply.button': 'Ariza berish',
      'scienceCouncil.apply.title': 'Ilmiy ishga ariza',
      'scienceCouncil.apply.submit': 'Ariza yuborish',
      'scienceCouncil.apply.file': "Ariza fayli (PDF)",
      'scienceCouncil.apply.chooseFile': 'Fayl tanlash uchun bosing',
      'scienceCouncil.apply.chooseAnother': 'Boshqa fayl tanlash',
      'scienceCouncil.apply.fileRequired': "Davom etish uchun PDF faylni tanlang",
      'scienceCouncil.apply.fileTypeError': 'Faqat PDF formatdagi fayl qabul qilinadi',
      'scienceCouncil.apply.success': 'Ariza muvaffaqiyatli yuborildi',
      'scienceCouncil.apply.fileUploadError': "Ish yaratildi, lekin faylni yuklashda xatolik yuz berdi. Ilmiy kengash kotibiga murojaat qiling",

      'scienceCouncil.public.pageTitle': 'Ilmiy ishga ariza topshirish',
      'scienceCouncil.public.subtitle':
        "Quyidagi formani to'ldirib, ilmiy ishingizni himoya qilish uchun ariza topshirasiz. Ariza ilmiy kengash kotibiga yuboriladi va ko'rib chiqilgach siz bilan bog'lanishadi.",
      'scienceCouncil.public.researcherSection': "Tadqiqotchi ma'lumotlari",
      'scienceCouncil.public.supervisorNote':
        "Ilmiy rahbaringiz haqidagi ma'lumotlarni kiriting. Unvon va daraja ixtiyoriy.",
      'scienceCouncil.public.successTitle': 'Arizangiz qabul qilindi',
      'scienceCouncil.public.successText':
        "Ariza ilmiy kengash kotibiga yuborildi. Natija haqida siz ko'rsatgan elektron pochta orqali xabar beriladi.",
      'scienceCouncil.public.refLabel': 'Ariza raqami',
      'scienceCouncil.public.newApplication': 'Yangi ariza topshirish',
      'scienceCouncil.public.loadError':
        "Ma'lumotlarni yuklab bo'lmadi. Internet aloqasini tekshirib, qayta urinib ko'ring.",
      'scienceCouncil.public.retry': 'Qayta urinish',
      'scienceCouncil.public.submitError': "Arizani yuborishda xatolik yuz berdi",
      'scienceCouncil.public.pinflPlaceholder': '14 ta raqam',
      'scienceCouncil.public.pinflInvalid': "JSHSHIR 14 ta raqamdan iborat bo'lishi kerak",
      'scienceCouncil.public.passportSeriesInvalid': 'Ikki harf kiriting (masalan: AA)',
      'scienceCouncil.public.passportNumberInvalid': '7 ta raqam kiriting',
      'scienceCouncil.nav.seminars': 'Seminarlar',
      'scienceCouncil.nav.defenses': 'Himoyalar',
      'scienceCouncil.seminar.title': 'Seminarlar',
      'scienceCouncil.seminar.subtitle': 'Seminar sanasi kelgan ilmiy ishlar',
      'scienceCouncil.seminar.label': 'Seminar',
      'scienceCouncil.seminar.date': 'Seminar sanasi',
      'scienceCouncil.seminar.result': 'Seminar natijasi',
      'scienceCouncil.seminar.defended': "Himoyaga qo'yilgan",
      'scienceCouncil.seminar.notDefended': "Himoyaga qo'yilmagan",
      'scienceCouncil.seminar.notSet': 'Baholanmagan',
      'scienceCouncil.seminar.defenseDate': 'Himoya sanasi',
      'scienceCouncil.seminar.editResult': "Seminar natijasini o'zgartirish",
      'scienceCouncil.seminar.searchPlaceholder': 'Ilmiy ish yoki muallif nomi...',
      'scienceCouncil.seminar.resultSaved': 'Seminar natijasi saqlandi',
      'scienceCouncil.seminar.resultFailed': "Natijani saqlashda xatolik",
      'scienceCouncil.seminar.setDate': 'Sanani tanlang',
      'scienceCouncil.seminar.dateSaved': 'Seminar sanasi saqlandi',
      'scienceCouncil.seminar.dateFailed': "Sanani saqlashda xatolik",
      'scienceCouncil.seminar.dateLocked': "Natija belgilangan — sanani o'zgartirib bo'lmaydi",
      'scienceCouncil.seminar.needDate': "Avval seminar sanasini belgilang",
      'scienceCouncil.seminar.notYetHeld': "Seminar sanasi hali yetib kelmagan",
      'scienceCouncil.seminar.movesToDefenses':
        "Saqlangach ilmiy ish “Himoyalar” bo'limiga o'tadi — himoya sanasi o'sha yerda belgilanadi",
      'scienceCouncil.defense.setDate': 'Sanani tanlang',
      'scienceCouncil.defense.dateSaved': 'Himoya sanasi saqlandi',
      'scienceCouncil.defense.dateFailed': "Sanani saqlashda xatolik",
      'scienceCouncil.defense.dateLocked': "Natija belgilangan — sanani o'zgartirib bo'lmaydi",
      'scienceCouncil.seminar.empty': "Seminar sanasi kelgan ilmiy ish yo'q",
      'scienceCouncil.defense.title': 'Himoyalar',
      'scienceCouncil.defense.date': 'Himoya sanasi',
      'scienceCouncil.defense.result': 'Himoya natijasi',
      'scienceCouncil.defense.defended': 'Himoya qilindi',
      'scienceCouncil.defense.notDefended': 'Himoya qilinmadi',
      'scienceCouncil.defense.notSet': 'Baholanmagan',
      'scienceCouncil.defense.editResult': "Himoya natijasini o'zgartirish",
      'scienceCouncil.defense.searchPlaceholder': 'Ilmiy ish yoki muallif nomi...',
      'scienceCouncil.defense.resultSaved': 'Himoya natijasi saqlandi',
      'scienceCouncil.defense.empty': "Himoya sanasi kelgan ilmiy ish yo'q",
      'scienceCouncil.noData': "Ma'lumot topilmadi",
      'scienceCouncil.actions': 'Amallar',
      'scienceCouncil.actions.view': "Ko'rish",
      'scienceCouncil.actions.edit': 'Tahrirlash',
      'scienceCouncil.actions.accept': 'Qabul qilish',
      'scienceCouncil.actions.reject': 'Rad etish',
      'scienceCouncil.rejection.reason': 'Rad etish sababi:',
      'scienceCouncil.delete': "O'chirish",
      'scienceCouncil.save': 'Saqlash',
      'scienceCouncil.cancel': 'Bekor qilish',
      'scienceCouncil.confirm': 'Tasdiqlash',
      'scienceCouncil.search': 'Qidirish...',
      'scienceCouncil.quick.acceptTitle': "Ishni qabul qilish",
      'scienceCouncil.quick.acceptConfirm': "Ushbu ilmiy ishni qabul qilib, kengash a'zolarini biriktiring:",
      'scienceCouncil.quick.acceptOk': "Qabul qilish",
      'scienceCouncil.quick.acceptMembersRequired': "Qabul qilish uchun kamida bitta kengash a'zosini tanlang",
      'scienceCouncil.quick.revisionTitle': "Qayta ishlashga qaytarish",
      'scienceCouncil.quick.revisionOk': "Qaytarish",
      'scienceCouncil.quick.revisionPlaceholder': "Qayta ishlash sababini kiriting...",
      'scienceCouncil.quick.rejectTitle': "Ishni rad etish",
      'scienceCouncil.quick.rejectOk': "Rad etish",
      'scienceCouncil.quick.rejectPlaceholder': "Rad etish sababini kiriting...",
      'scienceCouncil.quick.reasonLabel': 'Sabab',
      'scienceCouncil.detail.back': 'Orqaga',
      'scienceCouncil.detail.workInfo': "Ilmiy ish ma'lumotlari",
      'scienceCouncil.detail.specialty': 'Ixtisoslik',
      'scienceCouncil.detail.assignedToMe': 'Menga biriktirilgan',
      'scienceCouncil.export.xlsx': 'Eksport .xlsx',
      'scienceCouncil.export.failed': "Faylni yuklab olishda xatolik",
      'scienceCouncil.export.empty': "Eksport qilinadigan ma'lumot yo'q",
      'scienceCouncil.export.all': 'Barchasi',
      'scienceCouncil.export.statsSheet': 'Statistika',
      'scienceCouncil.detail.downloadApplication': 'Arizani yuklab olish',
      'scienceCouncil.detail.createdAt': 'Yaratilgan sana',
      'scienceCouncil.detail.updatedAt': 'Oxirgi yangilash',
      'scienceCouncil.detail.seminarDate': 'Seminar sanasi',
      'scienceCouncil.detail.secretary': 'Kotib',
      'scienceCouncil.detail.finalDecision': 'Yakuniy qaror',
      'scienceCouncil.detail.required': 'Majburiy',
      'scienceCouncil.detail.mandatory': 'Majburiy',
      'scienceCouncil.detail.optional': 'Ixtiyoriy',
      'scienceCouncil.detail.requiredDoc': 'Yuklanmagan (majburiy)',
      'scienceCouncil.detail.optionalDoc': 'Yuklanmagan (ixtiyoriy)',
      'scienceCouncil.detail.assigned': "ta a'zo biriktirilgan",
      'scienceCouncil.detail.reviewCount': 'ta xulosa',
      'scienceCouncil.detail.docs': 'ta hujjat',
      'scienceCouncil.detail.docAssignments': "Hujjat — a'zo birikmalari",
      'scienceCouncil.detail.noProtocol': "Dalolatnoma hali yaratilmagan",
      'scienceCouncil.detail.generatedAt': 'Yaratilgan sana',
      'scienceCouncil.detail.notSigned': 'Imzolanmagan',
      'scienceCouncil.detail.decisionHistory': 'Qarorlar tarixi',
      'scienceCouncil.detail.memberCount': "a'zo",
      'scienceCouncil.detail.reviewsAwaiting': 'Xulosalar kutilmoqda',
      'scienceCouncil.detail.reviewsAwaitingDesc': "Kengash a'zolari: {done}/{total} xulosa qoldirdi. Barcha a'zolar xulosa qoldirgach \"Dalolatnoma yaratish\" tugmasi paydo bo'ladi.",
      'scienceCouncil.detail.allReviewsDone': "Barcha xulosalar qoldirildi",
      'scienceCouncil.detail.allReviewsDoneDesc': "Barcha kengash a'zolari xulosa qoldirdi. Endi dalolatnoma yaratish mumkin.",
    },
    ru: {
      'menuGroup.scienceCouncil': 'Научный совет',
      'scienceCouncil.nav.dashboard': 'Панель управления',
      'scienceCouncil.nav.works': 'Научные работы',
      'scienceCouncil.nav.members': 'Члены совета',
      'scienceCouncil.nav.documents': 'Документы',
      'scienceCouncil.form.scientificTitle': 'Научное звание',
      'scienceCouncil.form.scientificTitlePlaceholder': 'Например: доцент',
      'scienceCouncil.form.selectScientificTitle': 'Выберите научное звание',
      'scienceCouncil.form.selectDegree': 'Выберите учёную степень',
      'scienceCouncil.form.refEmpty': 'Справочник пуст \u2014 заполняет администратор',
      'scienceCouncil.form.specialtyTitle': 'Название специальности',
      'scienceCouncil.form.specialtyCode': 'Шифр специальности',
      'scienceCouncil.form.selectSpecialty': 'Выберите специальность',
      'scienceCouncil.form.selectCode': 'Выберите шифр',
      'scienceCouncil.form.email': 'Электронная почта',
      'scienceCouncil.form.emailPlaceholder': 'например: rahbar@example.uz',
      'scienceCouncil.form.emailInvalid': 'Некорректная электронная почта',
      'scienceCouncil.form.phone': 'Номер телефона',
      'scienceCouncil.form.phonePlaceholder': '+998 90 123 45 67',
      'scienceCouncil.nav.settings': 'Настройки',
      'scienceCouncil.nav.specialties': 'Специальности',
      'scienceCouncil.nav.workDocuments': 'Документы научной работы',
      'scienceCouncil.nav.councilNumbers': 'Номера научного совета',
      'scienceCouncil.nav.applicationTemplate': 'Образец заявления',
      'scienceCouncil.settings.add': 'Добавить',
      'scienceCouncil.settings.saved': 'Сохранено',
      'scienceCouncil.settings.added': 'Добавлено',
      'scienceCouncil.settings.deleted': 'Удалено',
      'scienceCouncil.settings.saveFailed': 'Ошибка при сохранении',
      'scienceCouncil.settings.deleteFailed': 'Ошибка при удалении',
      'scienceCouncil.settings.status': 'Статус',
      'scienceCouncil.settings.active': 'Активен',
      'scienceCouncil.settings.inactive': 'Неактивен',
      'scienceCouncil.settings.specialtyTitle': 'Название специальности',
      'scienceCouncil.settings.specialtyTitlePh': 'Например: Педиатрия',
      'scienceCouncil.settings.specialtyCode': 'Шифр специальности',
      'scienceCouncil.settings.specialtyCodePh': 'Например: 14.00.09',
      'scienceCouncil.settings.branch': 'Отрасль науки',
      'scienceCouncil.settings.branchPh': 'Например: Медицинские науки',
      'scienceCouncil.settings.searchSpecialty': 'Поиск по названию или шифру',
      'scienceCouncil.settings.newSpecialty': 'Новая специальность',
      'scienceCouncil.settings.editSpecialty': 'Редактировать специальность',
      'scienceCouncil.settings.deleteSpecialty': 'Удалить специальность?',
      'scienceCouncil.settings.deleteSpecialtyDesc':
        'Специальность, привязанную к номеру совета, удалить нельзя.',
      'scienceCouncil.settings.councilNumber': 'Номер научного совета',
      'scienceCouncil.settings.councilNumberPh': 'Например: DSc.03/30.12.2019.Tib.50.01',
      'scienceCouncil.settings.attachedCodes': 'Привязанные шифры специальностей',
      'scienceCouncil.settings.attachedCodesPh': 'Выберите специальности',
      'scienceCouncil.settings.attachedCodesHint':
        'Можно выбрать несколько. Показаны только СВОБОДНЫЕ специальности — одна специальность может быть привязана только к одному АКТИВНОМУ номеру.',
      'scienceCouncil.settings.viewCodes': 'Посмотреть привязанные специальности',
      'scienceCouncil.settings.noFreeCodes': 'Свободных специальностей нет',
      'scienceCouncil.settings.searchNumber': 'Поиск по номеру совета',
      'scienceCouncil.settings.newNumber': 'Новый номер совета',
      'scienceCouncil.settings.editNumber': 'Редактировать номер совета',
      'scienceCouncil.settings.deleteNumber': 'Удалить номер совета?',
      'scienceCouncil.settings.deleteNumberDesc': 'Это действие необратимо.',
      'scienceCouncil.settings.templateInfo':
        'Данный образец заявления в формате PDF отображается на соответствующей странице исследователя, желающего подать заявление на защиту своей научной работы.',
      'scienceCouncil.settings.templateField': 'Образец заявления',
      'scienceCouncil.settings.templateEmpty': 'Образец не загружен',
      'scienceCouncil.settings.templateEmptyHint':
        'Загрузите PDF-образец для отображения исследователю',
      'scienceCouncil.settings.templateUpload': 'Загрузить',
      'scienceCouncil.settings.templateReplace': 'Заменить',
      'scienceCouncil.settings.templateDownload': 'Скачать',
      'scienceCouncil.settings.templateUploaded': 'Образец заявления загружен',
      'scienceCouncil.settings.templateFailed': 'Ошибка при загрузке образца',
      'scienceCouncil.settings.deleteTemplate': 'Удалить образец заявления?',
      'scienceCouncil.apply.templateTitle': 'Образец заявления',
      'scienceCouncil.apply.templateHint':
        'Скачайте образец, заполните и приложите подписанную PDF-копию.',
      'scienceCouncil.nav.assigned': 'Назначенные работы',
      'scienceCouncil.nav.myWork': 'Мои научные работы',
      'scienceCouncil.nav.notifications': 'Уведомления',
      'scienceCouncil.notifications.newWork': 'Подана новая научная работа',
      'scienceCouncil.notifications.pendingReview': 'Ожидает рассмотрения',
      'scienceCouncil.notifications.revision': 'Возвращена на доработку',
      'scienceCouncil.notifications.approved': 'Научная работа утверждена',
      'scienceCouncil.notifications.rejected': 'Документ отклонён',
      'scienceCouncil.notifications.newDoc': 'Загружен новый документ',
      'scienceCouncil.notifications.newReview': 'Оставлено новое заключение',
      'scienceCouncil.notifications.empty': 'Нет уведомлений',
      'scienceCouncil.notifications.unreadCount': '{count} непрочитанных уведомлений',
      'scienceCouncil.notifications.allRead': 'Все уведомления прочитаны',
      'scienceCouncil.notifications.markAllRead': 'Отметить все как прочитанные',
      'scienceCouncil.title': 'Научный совет',
      'scienceCouncil.work.title': 'Название научной работы',
      'scienceCouncil.work.author': 'Автор',
      'scienceCouncil.work.status': 'Статус',
      'scienceCouncil.work.year': 'Учебный год',
      'scienceCouncil.work.type': 'Тип',
      'scienceCouncil.work.create': 'Новая научная работа',
      'scienceCouncil.work.edit': 'Редактировать',
      'scienceCouncil.work.authorType': 'Тип автора',
      'scienceCouncil.work.date': 'Дата',
      'scienceCouncil.work.reviews': 'Заключения',
      'scienceCouncil.work.internal': 'Внутренний',
      'scienceCouncil.work.external': 'Внешний',
      'scienceCouncil.status.new': 'Новый',
      'scienceCouncil.status.accepted': 'Проверка не начата',
      'scienceCouncil.status.pending': 'На проверке',
      'scienceCouncil.status.reviewed': 'Проверено',
      'scienceCouncil.status.not_evaluated': 'Не оценено',
      'scienceCouncil.status.not_recommended': 'Не рекомендовано на семинар',
      'scienceCouncil.status.rejected': 'Отклонено',
      'scienceCouncil.status.revision': 'На доработке',
      'scienceCouncil.tab.info': 'Общее',
      'scienceCouncil.tab.documents': 'Документы',
      'scienceCouncil.tab.members': 'Члены совета',
      'scienceCouncil.tab.reviews': 'Заключения',
      'scienceCouncil.tab.protocol': 'Протокол',
      'scienceCouncil.tab.audit': 'Журнал аудита',
      'scienceCouncil.review.add': 'Оставить заключение',
      'scienceCouncil.review.positive': 'Положительно',
      'scienceCouncil.review.neutral': 'Нейтрально',
      'scienceCouncil.review.negative': 'Отрицательно',
      'scienceCouncil.decision.seminar': 'Рекомендовать на семинар',
      'scienceCouncil.decision.revision': 'Вернуть на доработку',
      'scienceCouncil.decision.reject': 'Отклонить',
      'scienceCouncil.protocol.generate': 'Создать протокол',
      'scienceCouncil.protocol.sign': 'Подписать с ЭЦП',
      'scienceCouncil.protocol.finalConclusion': 'Итоговое заключение',
      'scienceCouncil.protocol.intro': 'Вводная часть',
      'scienceCouncil.protocol.introPlaceholder':
        'Вводный текст: учреждение, исследователь, название работы и специальность',
      'scienceCouncil.protocol.noIntroYet': 'вводная часть не заполнена',
      'scienceCouncil.protocol.noReviewsYet': 'Члены совета ещё не написали заключений',
      'scienceCouncil.protocol.short': 'Акт',
      'scienceCouncil.protocol.download': 'Сохранить акт в PDF',
      'scienceCouncil.protocol.downloadDraft': 'Акт ещё не создан — сохранить черновик в PDF',
      'scienceCouncil.protocol.pdf': 'PDF',
      'scienceCouncil.protocol.downloadFailed': 'Ошибка при подготовке акта',
      'scienceCouncil.protocol.title': 'АКТ ПРОВЕРКИ',
      'scienceCouncil.protocol.subtitle': 'Первичная проверка документов научно-исследовательской работы',
      'scienceCouncil.protocol.date': 'Дата',
      'scienceCouncil.protocol.institution': 'Ферганский институт общественного здравоохранения',
      'scienceCouncil.protocol.work': 'Тема',
      'scienceCouncil.protocol.researcher': 'Исследователь',
      'scienceCouncil.protocol.memberReviews': 'Заключения членов совета',
      'scienceCouncil.protocol.awaitingReview': 'ожидается заключение',
      'scienceCouncil.protocol.docChecked': 'наличие проверено',
      'scienceCouncil.protocol.noConclusionYet': 'Итоговое заключение не указано',
      'scienceCouncil.protocol.conclusionPlaceholder': 'Введите итоговое заключение на основе заключений членов совета...',
      'scienceCouncil.protocol.viewFull': 'Посмотреть акт полностью',
      'scienceCouncil.protocol.viewFullDesc': 'Проверенные документы, заключения членов совета и итоговая рекомендация',
      'scienceCouncil.protocol.view': 'Открыть',
      'scienceCouncil.protocol.close': 'Закрыть',
      'scienceCouncil.protocol.signed': 'Акт подписан E-подписью',
      'scienceCouncil.protocol.signedBy': 'Подписал',
      'scienceCouncil.protocol.signedDate': 'Дата подписания',
      'scienceCouncil.protocol.certificate': 'Сертификат (CN)',
      'scienceCouncil.protocol.cryptoSign': 'Криптоподпись',
      'scienceCouncil.protocol.immutableWarning': 'Этот акт подписан E-подписью и не подлежит изменению',
      'scienceCouncil.protocol.eSignConfirm': 'Подписать E-подписью',
      'scienceCouncil.protocol.eSignDesc': 'Вы подтверждаете подписание данного акта E-подписью? После подписания содержимое нельзя будет изменить.',
      'scienceCouncil.protocol.signing': 'Подписывается...',
      'scienceCouncil.protocol.previewTitle': 'Просмотр акта и E-подпись',
      'scienceCouncil.stats.total': 'Всего работ',
      'scienceCouncil.table.rows': 'Строк таблицы',
      'scienceCouncil.stats.new': 'Новые',
      'scienceCouncil.stats.pending': 'На проверке',
      'scienceCouncil.stats.approved': 'Утверждённые',
      'scienceCouncil.stats.rejected': 'Отклонённые',
      'scienceCouncil.stats.revision': 'На доработке',
      'scienceCouncil.member.name': 'Имя',
      'scienceCouncil.member.type': 'Тип члена',
      'scienceCouncil.member.position': 'Должность',
      'scienceCouncil.member.degree': 'Учёная степень',
      'scienceCouncil.member.organization': 'Организация',
      'scienceCouncil.member.email': 'Email',
      'scienceCouncil.member.phone': 'Телефон',
      'scienceCouncil.member.assigned': 'Назначенные работы',
      'scienceCouncil.member.assignedWorks': 'Назначенные научные работы',
      'scienceCouncil.member.status': 'Статус',
      'scienceCouncil.member.active': 'Активен',
      'scienceCouncil.member.inactive': 'Неактивен',
      'scienceCouncil.member.addMember': 'Добавить члена',
      'scienceCouncil.member.editMember': 'Редактировать члена',
      'scienceCouncil.member.deleteMember': 'Удалить члена',
      'scienceCouncil.member.deleteConfirm': 'Вы действительно хотите удалить этого члена? Это действие нельзя отменить.',
      'scienceCouncil.member.deleteWarning': 'Внимание: член назначен на {count} работ.',
      'scienceCouncil.member.searchPlaceholder': 'Имя или организация...',
      'scienceCouncil.member.noAssigned': 'Работы ещё не назначены',
      'scienceCouncil.member.review': 'закл.',
      'scienceCouncil.member.works': 'работ',
      'scienceCouncil.member.fullNamePlaceholder': 'Фамилия Имя Отчество',
      'scienceCouncil.member.degreePlaceholder': 'Доктор медицинских наук...',
      'scienceCouncil.member.added': 'Член добавлен!',
      'scienceCouncil.member.saveFailed': 'Ошибка при сохранении члена совета',
      'scienceCouncil.member.councilNumberHint': 'Для сужения списка шифров (не сохраняется)',
      'scienceCouncil.member.deleteFailed': 'Ошибка при удалении члена совета',
      'scienceCouncil.member.updated': 'Данные обновлены!',
      'scienceCouncil.member.deleted': 'Член удалён',
      'scienceCouncil.member.total': 'Всего',
      'scienceCouncil.doc.upload': 'Загрузить',
      'scienceCouncil.doc.uploaded': 'Загружен',
      'scienceCouncil.doc.notUploaded': 'Не загружен',
      'scienceCouncil.doc.totalTypes': 'Всего типов документов',
      'scienceCouncil.doc.requiredDocs': 'Обязательные',
      'scienceCouncil.doc.optionalDocs': 'Необязательные',
      'scienceCouncil.doc.addCategory': 'Добавить категорию документа',
      'scienceCouncil.doc.editCategory': 'Редактировать категорию',
      'scienceCouncil.doc.newCategory': 'Новая категория документа',
      'scienceCouncil.doc.docName': 'Название документа',
      'scienceCouncil.doc.docNamePlaceholder': 'Например: Автореферат',
      'scienceCouncil.doc.format': 'Формат',
      'scienceCouncil.doc.isRequired': 'Обязательный?',
      'scienceCouncil.doc.deleteConfirm': 'Удалить категорию?',
      'scienceCouncil.doc.deleteDesc': 'Это действие необратимо.',
      'scienceCouncil.doc.deleteOk': 'Да, удалить',
      'scienceCouncil.doc.deleted': 'Категория документа удалена',
      'scienceCouncil.doc.added': 'Новая категория документа добавлена!',
      'scienceCouncil.doc.updated': 'Категория документа обновлена!',
      'scienceCouncil.doc.hint': 'Без обязательных документов преподаватель не сможет подать работу.',
      'scienceCouncil.doc.anyFormat': 'Любой',
      'scienceCouncil.form.required': 'Обязательное поле',
      'scienceCouncil.form.titlePlaceholder': 'Введите название научной работы...',
      'scienceCouncil.form.division': 'Отдел (неакадемический)',
      'scienceCouncil.form.divisionTooltip': 'Для отделов: бухгалтерия, кадры и т.д.',
      'scienceCouncil.form.selectDivision': 'Выберите отдел',
      'scienceCouncil.form.faculty': 'Факультет',
      'scienceCouncil.form.selectFaculty': 'Выберите факультет',
      'scienceCouncil.form.department': 'Кафедра',
      'scienceCouncil.form.selectDepartment': 'Выберите кафедру',
      'scienceCouncil.form.selectDivisionStaff': 'Выберите сотрудника отдела',
      'scienceCouncil.form.selectFacultyFirst': 'Сначала выберите факультет/кафедру или отдел',
      'scienceCouncil.form.selectTeacher': 'Выберите преподавателя',
      'scienceCouncil.form.fullName': 'Ф.И.О',
      'scienceCouncil.form.fullNamePlaceholder': 'Фамилия Имя Отчество',
      'scienceCouncil.form.workplace': 'Место работы',
      'scienceCouncil.form.workplacePlaceholder': 'Название организации',
      'scienceCouncil.form.position': 'Должность',
      'scienceCouncil.form.positionPlaceholder': 'Должность',
      'scienceCouncil.form.academicTitle': 'Академическое звание',
      'scienceCouncil.form.academicTitlePlaceholder': 'Например: Доцент',
      'scienceCouncil.form.degree': 'Учёная степень',
      'scienceCouncil.form.degreePlaceholder': 'Например: PhD',
      'scienceCouncil.form.passportSeries': 'Серия паспорта',
      'scienceCouncil.form.passportNumber': 'Номер паспорта',
      'scienceCouncil.form.pinfl': 'ПИНФЛ (ЖШШИР)',
      'scienceCouncil.form.selectMembers': 'Выберите членов совета',
      'scienceCouncil.form.supervisor': 'Научный руководитель',
      'scienceCouncil.form.supervisorType': 'Тип руководителя',
      'scienceCouncil.form.selectSupervisor': 'Выберите научного руководителя',
      'scienceCouncil.form.noStaffInUnit': 'В выбранном подразделении нет сотрудников — очистите фильтр',
      'scienceCouncil.form.next': 'Далее',
      'scienceCouncil.form.back': 'Назад',
      'scienceCouncil.step.general': 'Общее',
      'scienceCouncil.step.author': 'Автор',
      'scienceCouncil.step.supervisor': 'Научный руководитель',
      'scienceCouncil.step.members': 'Члены совета',
      'scienceCouncil.apply.button': 'Подать заявку',
      'scienceCouncil.apply.title': 'Заявка на научную работу',
      'scienceCouncil.apply.submit': 'Отправить заявку',
      'scienceCouncil.apply.file': 'Файл заявления (PDF)',
      'scienceCouncil.apply.chooseFile': 'Нажмите для выбора файла',
      'scienceCouncil.apply.chooseAnother': 'Выбрать другой файл',
      'scienceCouncil.apply.fileRequired': 'Выберите PDF файл, чтобы продолжить',
      'scienceCouncil.apply.fileTypeError': 'Принимается только файл формата PDF',
      'scienceCouncil.apply.success': 'Заявка успешно отправлена',
      'scienceCouncil.apply.fileUploadError': 'Работа создана, но при загрузке файла произошла ошибка. Обратитесь к секретарю совета',

      'scienceCouncil.public.pageTitle': 'Подача заявки на научную работу',
      'scienceCouncil.public.subtitle':
        'Заполнив форму ниже, вы подаёте заявку на защиту научной работы. Заявка направляется секретарю научного совета — после рассмотрения с вами свяжутся.',
      'scienceCouncil.public.researcherSection': 'Данные исследователя',
      'scienceCouncil.public.supervisorNote':
        'Укажите данные вашего научного руководителя. Звание и степень — необязательны.',
      'scienceCouncil.public.successTitle': 'Заявка принята',
      'scienceCouncil.public.successText':
        'Заявка направлена секретарю научного совета. О результате вам сообщат на указанную электронную почту.',
      'scienceCouncil.public.refLabel': 'Номер заявки',
      'scienceCouncil.public.newApplication': 'Подать новую заявку',
      'scienceCouncil.public.loadError':
        'Не удалось загрузить данные. Проверьте подключение к интернету и попробуйте снова.',
      'scienceCouncil.public.retry': 'Повторить',
      'scienceCouncil.public.submitError': 'Ошибка при отправке заявки',
      'scienceCouncil.public.pinflPlaceholder': '14 цифр',
      'scienceCouncil.public.pinflInvalid': 'ПИНФЛ должен состоять из 14 цифр',
      'scienceCouncil.public.passportSeriesInvalid': 'Введите две буквы (например: AA)',
      'scienceCouncil.public.passportNumberInvalid': 'Введите 7 цифр',
      'scienceCouncil.nav.seminars': 'Семинары',
      'scienceCouncil.nav.defenses': 'Защиты',
      'scienceCouncil.seminar.title': 'Семинары',
      'scienceCouncil.seminar.subtitle': 'Научные работы с наступившей датой семинара',
      'scienceCouncil.seminar.label': 'Семинар',
      'scienceCouncil.seminar.date': 'Дата семинара',
      'scienceCouncil.seminar.result': 'Результат семинара',
      'scienceCouncil.seminar.defended': 'Допущена к защите',
      'scienceCouncil.seminar.notDefended': 'Не допущена к защите',
      'scienceCouncil.seminar.notSet': 'Не оценено',
      'scienceCouncil.seminar.defenseDate': 'Дата защиты',
      'scienceCouncil.seminar.editResult': 'Изменить результат семинара',
      'scienceCouncil.seminar.searchPlaceholder': 'Название работы или автор...',
      'scienceCouncil.seminar.resultSaved': 'Результат семинара сохранён',
      'scienceCouncil.seminar.resultFailed': 'Ошибка при сохранении результата',
      'scienceCouncil.seminar.setDate': 'Выберите дату',
      'scienceCouncil.seminar.dateSaved': 'Дата семинара сохранена',
      'scienceCouncil.seminar.dateFailed': 'Ошибка при сохранении даты',
      'scienceCouncil.seminar.dateLocked': 'Результат зафиксирован — дату изменить нельзя',
      'scienceCouncil.seminar.needDate': 'Сначала укажите дату семинара',
      'scienceCouncil.seminar.notYetHeld': 'Дата семинара ещё не наступила',
      'scienceCouncil.seminar.movesToDefenses':
        'После сохранения работа перейдёт в раздел «Защиты» — дата защиты указывается там',
      'scienceCouncil.defense.setDate': 'Выберите дату',
      'scienceCouncil.defense.dateSaved': 'Дата защиты сохранена',
      'scienceCouncil.defense.dateFailed': 'Ошибка при сохранении даты',
      'scienceCouncil.defense.dateLocked': 'Результат зафиксирован — дату изменить нельзя',
      'scienceCouncil.seminar.empty': 'Нет работ с наступившей датой семинара',
      'scienceCouncil.defense.title': 'Защиты',
      'scienceCouncil.defense.date': 'Дата защиты',
      'scienceCouncil.defense.result': 'Результат защиты',
      'scienceCouncil.defense.defended': 'Защитился',
      'scienceCouncil.defense.notDefended': 'Не защитился',
      'scienceCouncil.defense.notSet': 'Не оценено',
      'scienceCouncil.defense.editResult': 'Изменить результат защиты',
      'scienceCouncil.defense.searchPlaceholder': 'Название работы или автор...',
      'scienceCouncil.defense.resultSaved': 'Результат защиты сохранён',
      'scienceCouncil.defense.empty': 'Нет работ с наступившей датой защиты',
      'scienceCouncil.noData': 'Данные не найдены',
      'scienceCouncil.actions': 'Действия',
      'scienceCouncil.actions.view': 'Просмотр',
      'scienceCouncil.actions.edit': 'Редактировать',
      'scienceCouncil.actions.accept': 'Принять',
      'scienceCouncil.actions.reject': 'Отклонить',
      'scienceCouncil.rejection.reason': 'Причина отклонения:',
      'scienceCouncil.delete': 'Удалить',
      'scienceCouncil.save': 'Сохранить',
      'scienceCouncil.cancel': 'Отмена',
      'scienceCouncil.confirm': 'Подтвердить',
      'scienceCouncil.search': 'Поиск...',
      'scienceCouncil.quick.acceptTitle': 'Принять работу',
      'scienceCouncil.quick.acceptConfirm': 'Примите данную научную работу и назначьте членов совета:',
      'scienceCouncil.quick.acceptOk': 'Принять',
      'scienceCouncil.quick.acceptMembersRequired': 'Для принятия выберите хотя бы одного члена совета',
      'scienceCouncil.quick.revisionTitle': 'Вернуть на доработку',
      'scienceCouncil.quick.revisionOk': 'Вернуть',
      'scienceCouncil.quick.revisionPlaceholder': 'Укажите причину возврата на доработку...',
      'scienceCouncil.quick.rejectTitle': 'Отклонить работу',
      'scienceCouncil.quick.rejectOk': 'Отклонить',
      'scienceCouncil.quick.rejectPlaceholder': 'Укажите причину отклонения...',
      'scienceCouncil.quick.reasonLabel': 'Причина',
      'scienceCouncil.detail.back': 'Назад',
      'scienceCouncil.detail.workInfo': 'Сведения о работе',
      'scienceCouncil.detail.specialty': 'Специальность',
      'scienceCouncil.detail.assignedToMe': 'Назначено мне',
      'scienceCouncil.export.xlsx': 'Экспорт .xlsx',
      'scienceCouncil.export.failed': 'Ошибка при скачивании файла',
      'scienceCouncil.export.empty': 'Нет данных для экспорта',
      'scienceCouncil.export.all': 'Все',
      'scienceCouncil.export.statsSheet': 'Статистика',
      'scienceCouncil.detail.downloadApplication': 'Скачать заявление',
      'scienceCouncil.detail.createdAt': 'Дата создания',
      'scienceCouncil.detail.updatedAt': 'Последнее обновление',
      'scienceCouncil.detail.seminarDate': 'Дата семинара',
      'scienceCouncil.detail.secretary': 'Секретарь',
      'scienceCouncil.detail.finalDecision': 'Итоговое решение',
      'scienceCouncil.detail.required': 'Обязательные',
      'scienceCouncil.detail.mandatory': 'Обязательный',
      'scienceCouncil.detail.optional': 'Необязательный',
      'scienceCouncil.detail.requiredDoc': 'Не загружен (обязательный)',
      'scienceCouncil.detail.optionalDoc': 'Не загружен (необязательный)',
      'scienceCouncil.detail.assigned': 'членов назначено',
      'scienceCouncil.detail.reviewCount': 'заключений',
      'scienceCouncil.detail.docs': 'документов',
      'scienceCouncil.detail.docAssignments': 'Назначения документов — членам',
      'scienceCouncil.detail.noProtocol': 'Протокол ещё не создан',
      'scienceCouncil.detail.generatedAt': 'Дата создания',
      'scienceCouncil.detail.notSigned': 'Не подписан',
      'scienceCouncil.detail.decisionHistory': 'История решений',
      'scienceCouncil.detail.memberCount': 'членов',
      'scienceCouncil.detail.reviewsAwaiting': 'Ожидание заключений',
      'scienceCouncil.detail.reviewsAwaitingDesc': 'Члены совета: {done}/{total} заключений подано. Кнопка «Создать протокол» появится после подачи всех заключений.',
      'scienceCouncil.detail.allReviewsDone': 'Все заключения поданы',
      'scienceCouncil.detail.allReviewsDoneDesc': 'Все члены совета подали заключения. Теперь можно создать протокол.',
    },
  },
  permissions: [
    { key: 'scienceCouncil:dashboard', description: 'View science council dashboard' },
    { key: 'scienceCouncil:readAll', description: 'View all scientific works list' },
    { key: 'scienceCouncil:read', description: 'View single scientific work detail' },
    { key: 'scienceCouncil:create', description: 'Create new scientific work' },
    { key: 'scienceCouncil:update', description: 'Update scientific work' },
    { key: 'scienceCouncil:delete', description: 'Delete scientific work' },
    { key: 'scienceCouncil:changeStatus', description: 'Change work status' },
    { key: 'scienceCouncil:manageMembers', description: 'Manage council members and assignments' },
    { key: 'scienceCouncil:review', description: 'Submit document review/conclusion' },
    { key: 'scienceCouncil:submitWork', description: 'Submit own scientific work and upload documents' },
    { key: 'scienceCouncil:sign', description: 'E-sign protocol (dalolatnoma)' },
    { key: 'scienceCouncil:notifications', description: 'View science council notifications' },
  ],
});
